$B/algo/force_stat/imp.o: $S/algo/force_stat/imp.cu; $N -I$S/algo/force_stat -I$S/.
$B/algo/minmax/imp.o: $S/algo/minmax/imp.cu; $N -I$S/algo/minmax -I$S/.
$B/algo/scan/imp.o: $S/algo/scan/imp.cu; $N -I$S/algo/scan -I$S/.
$B/clist/imp.o: $S/clist/imp.cu; $N -I$S/clist -I$S/.
$B/cnt/imp.o: $S/cnt/imp.cu; $N -I$S/cnt -I$S/.
$B/color/flux.o: $S/color/flux.cu; $N -I$S/color -I$S/.
$B/comm/imp.o: $S/comm/imp.cpp; $X -I$S/comm -I$S/.
$B/control/den/imp.o: $S/control/den/imp.cu; $N -I$S/control/den -I$S/.
$B/control/inflow/conf.o: $S/control/inflow/conf.cpp; $X -I$S/control/inflow -I$S/.
$B/control/inflow/imp.o: $S/control/inflow/imp.cu; $N -I$S/control/inflow -I$S/.
$B/control/outflow/imp.o: $S/control/outflow/imp.cu; $N -I$S/control/outflow -I$S/.
$B/control/vel/conf.o: $S/control/vel/conf.cpp; $X -I$S/control/vel -I$S/.
$B/control/vel/imp.o: $S/control/vel/imp.cu; $N -I$S/control/vel -I$S/.
$B/coords/conf.o: $S/coords/conf.cpp; $X -I$S/coords -I$S/.
$B/coords/imp.o: $S/coords/imp.cpp; $X -I$S/coords -I$S/.
$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/dbg/conf.o: $S/dbg/conf.cpp; $X -I$S/dbg -I$S/.
$B/dbg/imp.o: $S/dbg/imp.cu; $N -I$S/dbg -I$S/.
$B/distr/common/imp.o: $S/distr/common/imp.cu; $N -I$S/distr/common -I$S/.
$B/distr/flu/imp.o: $S/distr/flu/imp.cu; $N -I$S/distr/flu -I$S/.
$B/distr/flu/status/imp.o: $S/distr/flu/status/imp.cpp; $X -I$S/distr/flu/status -I$S/.
$B/distr/map/imp.o: $S/distr/map/imp.cu; $N -I$S/distr/map -I$S/.
$B/distr/rbc/imp.o: $S/distr/rbc/imp.cu; $N -I$S/distr/rbc -I$S/.
$B/distr/rig/imp.o: $S/distr/rig/imp.cu; $N -I$S/distr/rig -I$S/.
$B/exch/common/imp.o: $S/exch/common/imp.cu; $N -I$S/exch/common -I$S/.
$B/exch/flu/imp.o: $S/exch/flu/imp.cu; $N -I$S/exch/flu -I$S/.
$B/exch/map/imp.o: $S/exch/map/imp.cu; $N -I$S/exch/map -I$S/.
$B/exch/mesh/imp.o: $S/exch/mesh/imp.cu; $N -I$S/exch/mesh -I$S/.
$B/exch/obj/imp.o: $S/exch/obj/imp.cu; $N -I$S/exch/obj -I$S/.
$B/farray/imp.o: $S/farray/imp.cpp; $X -I$S/farray -I$S/.
$B/fluforces/bulk/imp.o: $S/fluforces/bulk/imp.cu; $N -I$S/fluforces/bulk -I$S/.
$B/fluforces/halo/imp.o: $S/fluforces/halo/imp.cu; $N -I$S/fluforces/halo -I$S/.
$B/fluforces/imp.o: $S/fluforces/imp.cu; $N -I$S/fluforces -I$S/.
$B/flu/imp.o: $S/flu/imp.cpp; $X -I$S/flu -I$S/.
$B/frag/imp.o: $S/frag/imp.cpp; $X -I$S/frag -I$S/.
$B/fsi/imp.o: $S/fsi/imp.cu; $N -I$S/fsi -I$S/.
$B/generate/rig/imp.o: $S/generate/rig/imp.cpp; $X -I$S/generate/rig -I$S/.
$B/inter/color/conf.o: $S/inter/color/conf.cpp; $X -I$S/inter/color -I$S/.
$B/inter/color/imp.o: $S/inter/color/imp.cpp; $X -I$S/inter/color -I$S/.
$B/inter/imp.o: $S/inter/imp.cu; $N -I$S/inter -I$S/.
$B/io/bop/imp.o: $S/io/bop/imp.cpp; $X -I$S/io/bop -I$S/.
$B/io/com/imp.o: $S/io/com/imp.cpp; $X -I$S/io/com -I$S/.
$B/io/diag/mesh/imp.o: $S/io/diag/mesh/imp.cpp; $X -I$S/io/diag/mesh -I$S/.
$B/io/diag/part/imp.o: $S/io/diag/part/imp.cpp; $X -I$S/io/diag/part -I$S/.
$B/io/field/h5/imp.o: $S/io/field/h5/imp.cpp; $X -I$S/io/field/h5 -I$S/.
$B/io/field/imp.o: $S/io/field/imp.cpp; $X -I$S/io/field -I$S/.
$B/io/field/xmf/imp.o: $S/io/field/xmf/imp.cpp; $X -I$S/io/field/xmf -I$S/.
$B/io/mesh/imp.o: $S/io/mesh/imp.cpp; $X -I$S/io/mesh -I$S/.
$B/io/mesh/write/imp.o: $S/io/mesh/write/imp.cpp; $X -I$S/io/mesh/write -I$S/.
$B/io/off/imp.o: $S/io/off/imp.cpp; $X -I$S/io/off -I$S/.
$B/io/restart/imp.o: $S/io/restart/imp.cpp; $X -I$S/io/restart -I$S/.
$B/io/rig/imp.o: $S/io/rig/imp.cpp; $X -I$S/io/rig -I$S/.
$B/io/txt/imp.o: $S/io/txt/imp.cpp; $X -I$S/io/txt -I$S/.
$B/main.o: $S/main.cpp; $X -I$S/.
$B/math/linal/imp.o: $S/math/linal/imp.cpp; $X -I$S/math/linal -I$S/.
$B/math/rnd/imp.o: $S/math/rnd/imp.cpp; $X -I$S/math/rnd -I$S/.
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/math/tform -I$S/.
$B/meshbb/imp.o: $S/meshbb/imp.cu; $N -I$S/meshbb -I$S/.
$B/mesh/bbox/imp.o: $S/mesh/bbox/imp.cpp; $X -I$S/mesh/bbox -I$S/.
$B/mesh/collision/imp.o: $S/mesh/collision/imp.cu; $N -I$S/mesh/collision -I$S/.
$B/mesh/dist/imp.o: $S/mesh/dist/imp.cpp; $X -I$S/mesh/dist -I$S/.
$B/mesh/props/imp.o: $S/mesh/props/imp.cpp; $X -I$S/mesh/props -I$S/.
$B/mesh/triangles/imp.o: $S/mesh/triangles/imp.cpp; $X -I$S/mesh/triangles -I$S/.
$B/mesh/volume/imp.o: $S/mesh/volume/imp.cpp; $X -I$S/mesh/volume -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/pair/conf.o: $S/pair/conf.cpp; $X -I$S/pair -I$S/.
$B/pair/imp.o: $S/pair/imp.cpp; $X -I$S/pair -I$S/.
$B/parray/imp.o: $S/parray/imp.cpp; $X -I$S/parray -I$S/.
$B/parser/imp.o: $S/parser/imp.cpp; $X -I$S/parser -I$S/.
$B/rbc/adj/edg/imp.o: $S/rbc/adj/edg/imp.cpp; $X -I$S/rbc/adj/edg -I$S/.
$B/rbc/adj/imp.o: $S/rbc/adj/imp.cpp; $X -I$S/rbc/adj -I$S/.
$B/rbc/com/imp.o: $S/rbc/com/imp.cu; $N -I$S/rbc/com -I$S/.
$B/rbc/force/area_volume/imp.o: $S/rbc/force/area_volume/imp.cu; $N -I$S/rbc/force/area_volume -I$S/.
$B/rbc/force/conf.o: $S/rbc/force/conf.cpp; $X -I$S/rbc/force -I$S/.
$B/rbc/force/imp.o: $S/rbc/force/imp.cu; $N -I$S/rbc/force -I$S/.
$B/rbc/force/rnd/api/imp.o: $S/rbc/force/rnd/api/imp.cpp; $X -I$S/rbc/force/rnd/api -I$S/.
$B/rbc/force/rnd/imp.o: $S/rbc/force/rnd/imp.cpp; $X -I$S/rbc/force/rnd -I$S/.
$B/rbc/gen/imp.o: $S/rbc/gen/imp.cpp; $X -I$S/rbc/gen -I$S/.
$B/rbc/imp.o: $S/rbc/imp.cpp; $X -I$S/rbc -I$S/.
$B/rbc/params/conf.o: $S/rbc/params/conf.cpp; $X -I$S/rbc/params -I$S/.
$B/rbc/params/imp.o: $S/rbc/params/imp.cpp; $X -I$S/rbc/params -I$S/.
$B/rbc/shape/imp.o: $S/rbc/shape/imp.cpp; $X -I$S/rbc/shape -I$S/.
$B/rbc/stretch/imp.o: $S/rbc/stretch/imp.cu; $N -I$S/rbc/stretch -I$S/.
$B/rigid/conf.o: $S/rigid/conf.cpp; $X -I$S/rigid -I$S/.
$B/rigid/imp.o: $S/rigid/imp.cu; $N -I$S/rigid -I$S/.
$B/rig/imp.o: $S/rig/imp.cpp; $X -I$S/rig -I$S/.
$B/scheme/force/conf.o: $S/scheme/force/conf.cpp; $X -I$S/scheme/force -I$S/.
$B/scheme/force/imp.o: $S/scheme/force/imp.cu; $N -I$S/scheme/force -I$S/.
$B/scheme/move/imp.o: $S/scheme/move/imp.cu; $N -I$S/scheme/move -I$S/.
$B/scheme/restrain/conf.o: $S/scheme/restrain/conf.cpp; $X -I$S/scheme/restrain -I$S/.
$B/scheme/restrain/imp.o: $S/scheme/restrain/imp.cu; $N -I$S/scheme/restrain -I$S/.
$B/scheme/time/imp.o: $S/scheme/time/imp.cpp; $X -I$S/scheme/time -I$S/.
$B/scheme/time_step/imp.o: $S/scheme/time_step/imp.cpp; $X -I$S/scheme/time_step -I$S/.
$B/sim/imp.o: $S/sim/imp.cpp; $X -I$S/sim -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/utils -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
$B/wall/exch/imp.o: $S/wall/exch/imp.cpp; $X -I$S/wall/exch -I$S/.
$B/wall/force/imp.o: $S/wall/force/imp.cu; $N -I$S/wall/force -I$S/.
$B/wall/imp.o: $S/wall/imp.cu; $N -I$S/wall -I$S/.
$B/wall/sdf/array3d/imp.o: $S/wall/sdf/array3d/imp.cu; $N -I$S/wall/sdf/array3d -I$S/.
$B/wall/sdf/bounce/imp.o: $S/wall/sdf/bounce/imp.cu; $N -I$S/wall/sdf/bounce -I$S/.
$B/wall/sdf/field/imp.o: $S/wall/sdf/field/imp.cpp; $X -I$S/wall/sdf/field -I$S/.
$B/wall/sdf/imp.o: $S/wall/sdf/imp.cu; $N -I$S/wall/sdf -I$S/.
$B/wall/sdf/label/imp.o: $S/wall/sdf/label/imp.cu; $N -I$S/wall/sdf/label -I$S/.
$B/wall/sdf/tex3d/imp.o: $S/wall/sdf/tex3d/imp.cu; $N -I$S/wall/sdf/tex3d -I$S/.
$B/wall/sdf/tform/imp.o: $S/wall/sdf/tform/imp.cpp; $X -I$S/wall/sdf/tform -I$S/.
$B/wall/wvel/conf.o: $S/wall/wvel/conf.cpp; $X -I$S/wall/wvel -I$S/.
$B/wall/wvel/imp.o: $S/wall/wvel/imp.cpp; $X -I$S/wall/wvel -I$S/.
