$B/comm/imp.o: $S/comm/imp.cpp; $X -I$S/comm -I$S/.
$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/frag/imp.o: $S/frag/imp.cpp; $X -I$S/frag -I$S/.
$B/math/linal/imp.o: $S/math/linal/imp.cpp; $X -I$S/math/linal -I$S/.
$B/math/rnd/imp.o: $S/math/rnd/imp.cpp; $X -I$S/math/rnd -I$S/.
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/math/tform -I$S/.
$B/math/tri/imp.o: $S/math/tri/imp.cpp; $X -I$S/math/tri -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/u/math/linal/main.o: $S/u/math/linal/main.cpp; $X -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/utils -I$S/.
$B/utils/nvtx/imp.o: $S/utils/nvtx/imp.cpp; $X -I$S/utils/nvtx -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
$B/utils/string/imp.o: $S/utils/string/imp.cpp; $X -I$S/utils/string -I$S/.
