D = @d () { test -d "$$1" || mkdir -p -- "$$1"; } && \
    d $B/d                        && \
    d $B/glob                     && \
    d $B/io                       && \
    d $B/io/bop                   && \
    d $B/io/com                   && \
    d $B/io/diag                  && \
    d $B/io/field                 && \
    d $B/io/field/h5              && \
    d $B/io/field/xmf             && \
    d $B/io/mesh                  && \
    d $B/io/mesh/write            && \
    d $B/io/off                   && \
    d $B/io/ply                   && \
    d $B/math/linal               && \
    d $B/math/rnd                 && \
    d $B/math/tform               && \
    d $B/mpi                      && \
    d $B/rbc/adj                  && \
    d $B/rbc/com                  && \
    d $B/rbc/edg                  && \
    d $B/rbc/force                && \
    d $B/rbc/force/area_volume    && \
    d $B/rbc/gen                  && \
    d $B/rbc/main                 && \
    d $B/rbc/main/anti            && \
    d $B/rbc/rnd                  && \
    d $B/rbc/rnd/api              && \
    d $B/rbc/stretch              && \
    d $B/scheme/force             && \
    d $B/scheme/move              && \
    d $B/scheme/restrain          && \
    d $B/scheme/restrain/sub      && \
    d $B/scheme/restrain/sub/stat && \
    d $B/scheme/restrain/sub/sum  && \
    d $B/u/rbc/main               && \
    d $B/u/rbc/main/lib           && \
    d $B/utils                   
