$B/algo/edg/imp.o: $S/algo/edg/imp.cpp; $X -I$S/. -I$S/algo/edg
$B/conf/imp.o: $S/conf/imp.cpp; $X -I$S/. -I$S/conf
$B/coords/conf.o: $S/coords/conf.cpp; $X -I$S/. -I$S/coords
$B/coords/imp.o: $S/coords/imp.cpp; $X -I$S/. -I$S/coords
$B/d/api.o: $S/d/api.cu; $N -I$S/. -I$S/d
$B/io/bop/imp.o: $S/io/bop/imp.cpp; $X -I$S/. -I$S/io/bop
$B/io/com/imp.o: $S/io/com/imp.cpp; $X -I$S/. -I$S/io/com
$B/io/diag/mesh/imp.o: $S/io/diag/mesh/imp.cpp; $X -I$S/. -I$S/io/diag/mesh
$B/io/diag/part/imp.o: $S/io/diag/part/imp.cpp; $X -I$S/. -I$S/io/diag/part
$B/io/field/h5/imp.o: $S/io/field/h5/imp.cpp; $X -I$S/. -I$S/io/field/h5
$B/io/field/imp.o: $S/io/field/imp.cpp; $X -I$S/. -I$S/io/field
$B/io/field/xmf/imp.o: $S/io/field/xmf/imp.cpp; $X -I$S/. -I$S/io/field/xmf
$B/io/mesh/imp.o: $S/io/mesh/imp.cpp; $X -I$S/. -I$S/io/mesh
$B/io/mesh/write/imp.o: $S/io/mesh/write/imp.cpp; $X -I$S/. -I$S/io/mesh/write
$B/io/mesh_read/imp.o: $S/io/mesh_read/imp.cpp; $X -I$S/. -I$S/io/mesh_read
$B/io/point/imp.o: $S/io/point/imp.cpp; $X -I$S/. -I$S/io/point
$B/io/restart/imp.o: $S/io/restart/imp.cpp; $X -I$S/. -I$S/io/restart
$B/io/rig/imp.o: $S/io/rig/imp.cpp; $X -I$S/. -I$S/io/rig
$B/io/txt/imp.o: $S/io/txt/imp.cpp; $X -I$S/. -I$S/io/txt
$B/math/linal/imp.o: $S/math/linal/imp.cpp; $X -I$S/. -I$S/math/linal
$B/math/rnd/imp.o: $S/math/rnd/imp.cpp; $X -I$S/. -I$S/math/rnd
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/. -I$S/math/tform
$B/math/tri/imp.o: $S/math/tri/imp.cpp; $X -I$S/. -I$S/math/tri
$B/mesh/vectors/imp.o: $S/mesh/vectors/imp.cpp; $X -I$S/. -I$S/mesh/vectors
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/. -I$S/mpi
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/. -I$S/mpi
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/. -I$S/mpi
$B/rbc/adj/imp.o: $S/rbc/adj/imp.cpp; $X -I$S/. -I$S/rbc/adj
$B/rbc/com/imp.o: $S/rbc/com/imp.cu; $N -I$S/. -I$S/rbc/com
$B/rbc/force/area_volume/imp.o: $S/rbc/force/area_volume/imp.cu; $N -I$S/. -I$S/rbc/force/area_volume
$B/rbc/force/conf.o: $S/rbc/force/conf.cpp; $X -I$S/. -I$S/rbc/force
$B/rbc/force/imp.o: $S/rbc/force/imp.cu; $N -I$S/. -I$S/rbc/force
$B/rbc/force/rnd/api/imp.o: $S/rbc/force/rnd/api/imp.cpp; $X -I$S/. -I$S/rbc/force/rnd/api
$B/rbc/force/rnd/imp.o: $S/rbc/force/rnd/imp.cpp; $X -I$S/. -I$S/rbc/force/rnd
$B/rbc/gen/imp.o: $S/rbc/gen/imp.cpp; $X -I$S/. -I$S/rbc/gen
$B/rbc/imp.o: $S/rbc/imp.cpp; $X -I$S/. -I$S/rbc
$B/rbc/matrices/imp.o: $S/rbc/matrices/imp.cpp; $X -I$S/. -I$S/rbc/matrices
$B/rbc/params/conf.o: $S/rbc/params/conf.cpp; $X -I$S/. -I$S/rbc/params
$B/rbc/params/imp.o: $S/rbc/params/imp.cpp; $X -I$S/. -I$S/rbc/params
$B/rbc/shape/imp.o: $S/rbc/shape/imp.cpp; $X -I$S/. -I$S/rbc/shape
$B/rbc/stretch/imp.o: $S/rbc/stretch/imp.cu; $N -I$S/. -I$S/rbc/stretch
$B/scheme/force/conf.o: $S/scheme/force/conf.cpp; $X -I$S/. -I$S/scheme/force
$B/scheme/force/imp.o: $S/scheme/force/imp.cu; $N -I$S/. -I$S/scheme/force
$B/scheme/move/imp.o: $S/scheme/move/imp.cu; $N -I$S/. -I$S/scheme/move
$B/scheme/restrain/conf.o: $S/scheme/restrain/conf.cpp; $X -I$S/. -I$S/scheme/restrain
$B/scheme/restrain/imp.o: $S/scheme/restrain/imp.cu; $N -I$S/. -I$S/scheme/restrain
$B/scheme/time/imp.o: $S/scheme/time/imp.cpp; $X -I$S/. -I$S/scheme/time
$B/u/rbc/main/lib/imp.o: $S/u/rbc/main/lib/imp.cu; $N -I$S/. -I$S/u/rbc/main/lib
$B/u/rbc/main/main.o: $S/u/rbc/main/main.cpp; $X -I$S/. -I$S/u/rbc/main
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/. -I$S/utils
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/. -I$S/utils
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/. -I$S/utils
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/. -I$S/utils
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/. -I$S/utils
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/. -I$S/utils
