$B/d/api.o: $S/d/api.cu; $N -I$S/. -I$S/d
$B/glb/imp.o: $S/glb/imp.cu; $N -I$S/. -I$S/glb
$B/glb/wvel/imp.o: $S/glb/wvel/imp.cu; $N -I$S/. -I$S/glb/wvel
$B/io/bop/imp.o: $S/io/bop/imp.cpp; $X -I$S/. -I$S/io/bop
$B/io/com.o: $S/io/com.cpp; $X -I$S/. -I$S/io
$B/io/diag.o: $S/io/diag.cpp; $X -I$S/. -I$S/io
$B/io/field/h5/imp.o: $S/io/field/h5/imp.cpp; $X -I$S/. -I$S/io/field/h5
$B/io/field/imp.o: $S/io/field/imp.cpp; $X -I$S/. -I$S/io/field
$B/io/field/xmf/imp.o: $S/io/field/xmf/imp.cpp; $X -I$S/. -I$S/io/field/xmf
$B/io/fields_grid.o: $S/io/fields_grid.cpp; $X -I$S/. -I$S/io
$B/io/mesh/imp.o: $S/io/mesh/imp.cpp; $X -I$S/. -I$S/io/mesh
$B/io/mesh/write/imp.o: $S/io/mesh/write/imp.cpp; $X -I$S/. -I$S/io/mesh/write
$B/io/off.o: $S/io/off.cpp; $X -I$S/. -I$S/io
$B/io/ply.o: $S/io/ply.cpp; $X -I$S/. -I$S/io
$B/io/restart.o: $S/io/restart.cpp; $X -I$S/. -I$S/io
$B/io/rig.o: $S/io/rig.cpp; $X -I$S/. -I$S/io
$B/math/linal.o: $S/math/linal.cpp; $X -I$S/. -I$S/math
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/. -I$S/mpi
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/. -I$S/mpi
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/. -I$S/mpi
$B/msg.o: $S/msg.cpp; $X -I$S/.
$B/rbc/adj/imp.o: $S/rbc/adj/imp.cpp; $X -I$S/. -I$S/rbc/adj
$B/rbc/com/imp.o: $S/rbc/com/imp.cu; $N -I$S/. -I$S/rbc/com
$B/rbc/edg/imp.o: $S/rbc/edg/imp.cpp; $X -I$S/. -I$S/rbc/edg
$B/rbc/force/area_volume/imp.o: $S/rbc/force/area_volume/imp.cu; $N -I$S/. -I$S/rbc/force/area_volume
$B/rbc/force/imp.o: $S/rbc/force/imp.cu; $N -I$S/. -I$S/rbc/force
$B/rbc/gen/imp.o: $S/rbc/gen/imp.cpp; $X -I$S/. -I$S/rbc/gen
$B/rbc/main/anti/imp.o: $S/rbc/main/anti/imp.cpp; $X -I$S/. -I$S/rbc/main/anti
$B/rbc/main/imp.o: $S/rbc/main/imp.cpp; $X -I$S/. -I$S/rbc/main
$B/rbc/rnd/api/imp.o: $S/rbc/rnd/api/imp.cpp; $X -I$S/. -I$S/rbc/rnd/api
$B/rbc/rnd/imp.o: $S/rbc/rnd/imp.cpp; $X -I$S/. -I$S/rbc/rnd
$B/rbc/stretch/imp.o: $S/rbc/stretch/imp.cu; $N -I$S/. -I$S/rbc/stretch
$B/restrain/imp.o: $S/restrain/imp.cu; $N -I$S/. -I$S/restrain
$B/restrain/stat/imp.o: $S/restrain/stat/imp.cpp; $X -I$S/. -I$S/restrain/stat
$B/restrain/sum/imp.o: $S/restrain/sum/imp.cpp; $X -I$S/. -I$S/restrain/sum
$B/scheme/imp.o: $S/scheme/imp.cu; $N -I$S/. -I$S/scheme
$B/u/rbc/main/lib/imp.o: $S/u/rbc/main/lib/imp.cu; $N -I$S/. -I$S/u/rbc/main/lib
$B/u/rbc/main/main.o: $S/u/rbc/main/main.cpp; $X -I$S/. -I$S/u/rbc/main
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/. -I$S/utils
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/. -I$S/utils
$B/utils/halloc.o: $S/utils/halloc.cpp; $X -I$S/. -I$S/utils
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/. -I$S/utils
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/. -I$S/utils
