load("u.mac");
/*

i: paritcle id, ws: wrap start (0th lane), fs: fragment start
wsf: wrap start in fragment coordinates
wef: wrap end   in fragment coordinates

"global":
[fs  ws     i     ]

"wrap":
[0           ]

"fragment"
[0                      cnt]

*/

/* transformations */
[g2w, w2g]: genfi(ws, 0);
[g2f, f2g]: genfi(fs, 0);
f2w: chain(f2g, g2w);

wsf: g2f(ws);
f2w(cnt);

wef: g2f(ws + wrapSize);

