$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/pair/conf.o: $S/pair/conf.cpp; $X -I$S/pair -I$S/.
$B/pair/imp.o: $S/pair/imp.cpp; $X -I$S/pair -I$S/.
$B/parser/imp.o: $S/parser/imp.cpp; $X -I$S/parser -I$S/.
$B/u/pair/main.o: $S/u/pair/main.cu; $N -I$S/u/pair -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/utils -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
