= wall

Manages frozen wall particles data.

== data structure

The data is stored in a visible structure. The user can access
directly the fields.

[source,cpp]
----
include::{src}/wall/imp.h[tag=struct]
----

Only positions of the particles are stored, Their velocity can be
computed by using the <<wall_wvel, wvel submodule>>.

The `Ticket` hidden structure contains helpers (cell lists, texture objects,
random number generator) for force interactions with external
particles.

== interface

allocate and deallocate the data:

[source,cpp]
----
include::{src}/wall/imp.h[tag=mem]
----

generate the quantities:

[source,cpp]
----
include::{src}/wall/imp.h[tag=gen]
----
<1> freeze the particles from a given equilibrated array of solvent particles
    occupying the subdomain. The input array of particles is resized
    and only solvent particles remain. Creates additional "margin
    particles" copied from neighbouring ranks. See <<wall_exch>>.
<2> generate `Ticket` structure from quantities

<<io_restart, restart>> interface:

[source,cpp]
----
include::{src}/wall/imp.h[tag=start]
----
<1> read quantities from restart files
<2> dump quantities to restart files (set 0 velocity to particles)

compute interactions with other particles (see <<wall_force, force submodule>>):

[source,cpp]
----
include::{src}/wall/imp.h[tag=int]
----

== submodules

:leveloffset: +2

include::exch.inc.adoc[]

include::force.inc.adoc[]

include::sdf.inc.adoc[]

include::wvel.inc.adoc[]

:leveloffset: -2
