/* 10.1016/j.media.2007.10.005 */

/*
   0  <= L < +inf
   -L <= K <= L

   0 < t < pi
   0 < p < 2 * pi
*/

fac(n):=n!;
a1: fac(2*L)/fac(L) * (1/2*si)^L;
a2: (L + K)*(L - K + 1)*P(K-1, L) = 2*K*ct*P(K, L) - P(K+1, L);
s: linsolve(a2, 'P(K-1, L));
s: s[1];
s: subst(K = K + 1, s);
s: rhs(s);

define(Peq(L), a1);
define(P0(K, L),   s);

P(K, L):= if L = K then Peq(L) else if K > L then 0 else P0(K, L);
pp(t, K, L):= block([co: cos(t), si: sin(t), ct: cot(t)], P(K, L));
y0(t, p, K, L):=pp(t, K, L)*exp(%i*K*p);

sq(e):=e * conjugate(e);

i30(e):=integrate(integrate(sin('t)*e, 't, 0, %pi), 'p, 0, 2*%pi);
i3(e):= i30(sq(e));

/* reference normalization cooeficeent */
gold(m, l):= sqrt(   (2*l + 1)/(4*%pi) * fac(l - m)/fac(l + m));

(K: 3, L: 3);
r: i3(y0('t, 'p, K, L));
gold(K, L)^2 * r; /* should be one */

expr(K, L):= trigsimp(sq(y0('t, 'p, K, L)));

(K: 3, L: 3);
draw3d(spherical(expr(K, L),'p, 0, 2*%pi, 't, 0, %pi))$
