#!/usr/bin/python2

import sys
from scipy.special import sph_harm as YY0
def YY(K, L, p, t):
    return YY0(K, L, p, t).real if K >= 0 else YY0(-K, L, p, t).imag
from numpy import conj

def from_to(l, h):
    return [l] if l == h else range(l, h + 1)
def shift(): sys.argv.pop(0)
def fst()  : return sys.argv[1]
def msg(s) : sys.stderr.write("%s\n" % s )
def err(s) : msg(s); sys.exit(2)

def read_sph(f):
    P, T, R, A,  X, Y, Z = 0, 1, 2, 3, 4, 5, 6
    S = []
    f = f.read().splitlines()
    for l in f:
        l = l.split()
        tu = l[P], l[T], l[A], l[X], l[Y], l[Z]
        tu = map(float, tu)
        S.append(tu)
    return S

def null():
    for L in from_to(0, Lmax):
        for K in from_to(-L, L):
            C[K, L] = [0, 0, 0]
def proj(p, t, a, x, y, z):
    '''phi, theta, area, ...'''
    X, Y, Z = 0, 1, 2
    for L in from_to(0, Lmax):
        for K in from_to(-L, L):
            k = conj(YY(K, L, p, t))*a
            C[K, L][X] += x*k
            C[K, L][Y] += y*k
            C[K, L][Z] += z*k
def dump():
    X, Y, Z = 0, 1, 2
    for L in from_to(0, Lmax):
        for K in from_to(-L, L):
            c = C[K, L]
            print c[X].real, c[X].imag,   c[Y].real, c[Y].imag,    c[Z].real, c[Z].imag

Lmax = fst(); shift()
try: Lmax = int(Lmax)
except ValueError: err("expecting an integer: %s" % Lmax)
i = fst(); shift()
try:
    with open(i, 'r') as f: S = read_sph(f)
except IOError: err("not a file '%s'" % i)
except ValueError: err("error reading '%s'" % i)

C = {}
null()
for p, t, a, x, y, z in S: proj(p, t, a, x, y, z)
dump()
