#!/bin/sh

set -eu

# download/update and install udx related projects

# Run
# $ curl https://raw.githubusercontent.com/slitvinov/uDeviceX/solid/bootstrap -o bootstrap
# $ sh bootstrap

l="atest bop off udx comma"
#p=https://github.com/slitvinov
p=git@gitlab.ethz.ch:mavt-cse

pull0()    ( cd0 "$d" && cmd git pull )
install0() ( cd0 "$d" && cmd make install )
git0()     { cmd git clone "$p/$d" "$d"; }

installd() { if test -d "$d"; then install0; else err "no dir: $d"; fi; }
cloned()   { if test -d "$d"; then    pull0; else git0;             fi; }

msg()      { printf 'bstrap: %s\n' "$*" >&2 ; }
err()      { msg "$@"; exit 1; }
cmd()      { msg "> $*"; cmd0 "$@"; }
cmd0()     { "$@"; status; }
status()   { if test "$?" -eq 0; then msg "  OK"; else msg "  FAILED"; fi; }
cd0()      { msg ": cd $1"; cd "$1"; }

for d in $l; do cloned; done
for d in $l; do installd; done
