$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/u/hw/dev/main.o: $S/u/hw/dev/main.cu; $N -I$S/u/hw/dev -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/utils -I$S/.
$B/utils/nvtx/imp.o: $S/utils/nvtx/imp.cpp; $X -I$S/utils/nvtx -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
$B/utils/string/imp.o: $S/utils/string/imp.cpp; $X -I$S/utils/string -I$S/.
