== Inflow

Mass rate inflow.

Create particles given a surface stem:[S(u, v)], with a velocity profile
stem:[\mathbf{U}(u,v)] with stem:[(u,v) \in (0,1) \times (0,1)].

== Method

Define "cumulative inflow" stem:[\phi(u, v)] in a bin of area stem:[dA
\in S].

Updated as follow:

[stem]
++++
\phi^{n+1} = \phi^n + dt \rho dA \mathbf{u} \cdot \mathbf{n}
++++

where stem:[\rho] is the number density.

When stem:[\phi \geq 1], a particle is released at the bin position
with random velocity stem:[\mathcal{N} (\mathbf{u}, k_BT)].
We also set stem:[\phi \leftarrow \phi - 1].

=== interface

allocate, deallocate:

[source,cpp]
----
include::{src}/control/inflow/imp.h[tags=mem]
----

initialize the inflow structure (to be done only once):

[source,cpp]
----
include::{src}/control/inflow/imp.h[tags=ini]
----
depending on the type of inflow, call the appropriate
`ini_params_xxx`.
`ini_velocity` must be called after initializing the parameters.
it is used to setup the inlet velocity from parameters.

initialize from config parameters:

[source,cpp]
----
include::{src}/control/inflow/imp.h[tags=cnf]
----


create particles (at every time step):

[source,cpp]
----
include::{src}/control/inflow/imp.h[tags=int]
----
<1> add particles to the array `pp` and increase `n` accordingly
<2> same as above, with colors `cc` set to `color`


=== configuration

==== plate

syntax for a `8.0 x 16.0` plate perpendicular to the x axis passing by
the point `(1, 2, 3)`:

[source,cfg]
----
inflow = {
    active      = true
    type        = "plate"
    L1          = 1.0
    L2          = 16.0
    direction   = 0                # [0,1,2] = [X,Y,Z]
    origin      = [1.0, 2.0, 3.0]
    upoiseuille = false            # true for parabolic profile along L1
    vpoiseuille = false            # true for parabolic profile along L2
    u           = [10.0, 0.0, 0.0]
}
----


==== circle

syntax for cylindrical surface:

[source,cfg]
----
inflow = {
    active = true
    type   = "circle"
    R      = 1.0              # radius
    H      = 16.0             # hight of the cylinder
    U      = 1.0              # maximum velocity
    center = [8.0, 8.0, 8.0]
    poiseuille = false        # parabolic profile along H if true
}
----
