== Velocity controller

:stem: latexmath

control velocity by modifying the imposed hydrostatic force
the force is modified using a PID controller https://en.wikipedia.org/wiki/PID_controller.

=== Controlled variables

The controlled variable is the (global) body force value.
The state of the system is represented by

[stem]
++++
\mathbf{U} = \frac 1 n \sum\limits_{i=1}^n \mathbf{f} \left( \mathbf{r_i}, \mathbf{v_i} \right)
++++
where stem:[( \mathbf{r_i}, \mathbf{v_i})] are the stem:[i^{th}]
particle position and velocity, stem:[n] is the number of particles
and stem:[\mathbf{f}] is a given transformation.

There is therefore 3 (independant) controlled variables.

the transformation is the way of averaging the velocity:

* cartesian transformation keeps the velocity and does not depends on position.
* radial transformation returns the velocity in polar coordinates
  scaled by the radial position. the `z` component corresponds to
  cartesian transformation


=== interface

allocate, deallocate:

[source,cpp]
----
include::{src}/control/vel/imp.h[tags=mem]
----

set the parameters (to be done only once, before any other calls):

[source,cpp]
----
include::{src}/control/vel/imp.h[tags=set]
----
<1> set the PID control variables. `factor` scales variables `Kp`, Ki`
    and `Kd`
<2> set the target velocity (in transformed space)
<3> set the transformation mode to cartesian
<4> set the transformation mode to radial

The parameters can also be set through the configuration file:

[source,cpp]
----
include::{src}/control/vel/imp.h[tags=cnf]
----


Control operations:

[source,cpp]
----
include::{src}/control/vel/imp.h[tags=int]
----
<1> get average velocity according to transformation and store it
<2> reduce sampled quantities and update the controller. return the force
<3> logging informations; dumped into the file `vcon.txt`

=== configuration

syntax:

[source,cfg]
----
vcon = {
     active = true;
     type   = "cart";          # can be also "rad"
     U      = [1.0, 1.0, 0.0]; # target velocity in transformed space
     factor = 0.08
     Kp = 2.0
     Ki = 1.0
     Kd = 8.0
     log_freq    = 500;
     adjust_freq = 500;
     sample_freq = 1;
};
----
