= Red blood cell

Red blood cell membranes are represented via particles with
connectivity.

This module stores the required quantities and functions for:

* initializing red blood cells positions and orientations
* managing particles and connectivity
* membrane force computations

:leveloffset: +1

include::energy.inc.adoc[]

:leveloffset: -1

== Quantities

`RbcQuants` structure contains particles of membrane and connectivity.

[source, c++]
----
include::{src}/rbc/type.h[tag=quants]
----

The above data structure is allocated and freed using:

[source, c++]
----
include::{src}/rbc/imp.h[tag=mem]
----

The generation is made in two stages: mesh generations and other
quantities (global ids).
This allows to remove red blood cells colliding with other entities
before creating global ids.


[source, c++]
----
include::{src}/rbc/imp.h[tag=ini]
----
<1> Generate mesh from file "ic" (see <<mesh_gen>>)
<2> Generate global ids of rbc
<3> Generate quantities from <<io_restart, restart>>
<4> Dump a <<io_restart, restart>> state of the quantities

Available mesh are stored in `src/data/cells`

== Submodules

:leveloffset: +2

include::adj.inc.adoc[]

include::com.inc.adoc[]

include::forces.inc.adoc[]

include::area_volume.inc.adoc[]

include::rnd.inc.adoc[]

include::params.inc.adoc[]

include::shape.inc.adoc[]

include::stretch.inc.adoc[]

:leveloffset: -2

