= mesh adjacency structure
:lext: .adoc
:src: ../../../src

Consider closed triangulated mesh with `nv` vertices. Degree of a
vertex is the number of edges incident to the vertex. Let `md` is a
maximum degree of the vertices. To compute forces in one membrane
_uDeviceX_ launches `nv * md` threads each thread adds forces to only
one vertices.  There are three types of forces: edge forces which
depend on two vertices, triangle forces which depend on three
vertices, and dihedral forces which depend of four vertices (edge and
two adjusting triangles). `Adj_v` has an API call which allow for a
given thread ID to find which vertices should be used in forces
computation.

[source,cpp]
----
include::{src}/rbc/adj/dev.h[tag=interface]
----

It return 0 if thread is not `valid`. If `md * nv` is bigger than
number of edges in the membrane some threads are not needed. `AdjMap`
is a structure which contains five indices and ID of a mesh:

[source,cpp]
----
include::{src}/rbc/adj/type/dev.h[tag=interface]
----
