= Elastic energies
:lext: .adoc
:stem: latexmath

== spring

Spring energy is a function of distance between connected beads stem:[r]
[stem]
++++
U_{spring}(r) = U_{wlc}(r) + U_{pow}(r)
++++

where worm-like chain energy:
[stem]
++++
U_{wlc}(r) =
\frac{k_s}{4 l_{max}}
\frac{3 x^2 - 2 x^3}{1 - x}, \quad x = \frac{r}{l_{max}}
++++
and power-law energy:
[stem]
++++
U_{wlc}(r) =
\frac{k_p}{r^{m - 1}}
++++

stem:[l_0] is an equilibrium lenght, stem:[l_{max}] is a maximum
lenght stem:[l_{max} = l_{0} / x_{0}], and stem:[k_p] is defined from
condition that stem:[U_{spring}] has a maximum at stem:[r = l_0].

== local area constrain

For every triangle with area stem:[A^{loc}] and an equilibrium area
stem:[A_0^{loc}]

[stem]
++++
E^{loc}_{area} =
k_d
\frac
{
  \left(
    A^{loc} - A_0^{loc}
  \right)^2
}
{2 A_0^{loc}}
++++

== total area constrain

For whole mesh with area stem:[A^{tot}] and an equilibrium area
stem:[A_0^{tot}]

[stem]
++++
E^{tot}_{area} =
k_a
\frac
{\left( A^{tot} - A_0^{tot} \right)^2}
{2 A_0^{tot} }
++++

== total volume constrain

For whole mesh with volume stem:[V] and an equilibrium volume
stem:[V_0]


[stem]
++++
E_{vol} =
k_v
\frac
{\left( V - V_0 \right)^2}
{2 V_0}
++++

== bending

[stem]
++++
E_{bnd} = k_b
\left[
  1 - \cos
  \left(
    \theta - \theta_0
  \right)
\right]
++++
