= Red blood cell

Red blood cell membranes are represented via particles with
connectivity.

This module stores the required quantities and functions for:

* initializing red blood cells positions and orientations
* managing particles and connectivity
* membrane force computations

== Quantities

`RbcQuants` structure contains particles of membrane and connectivity.

[source, c++]
----
include::{src}/rbc/type.h[tag=quants]
----

The above data structure is allocated and freed using:

[source, c++]
----
include::{src}/rbc/imp.h[tag=mem]
----


[source, c++]
----
include::{src}/rbc/imp.h[tag=ini]
----
<1> Generate quantities from file "ic" (see matrices submodule)
<2> Generate quantities from restart
<3> Dump a restart state of the quantities

Available mesh are stored in `src/data/cells`

== Submodules

:leveloffset: +2

include::adj.inc.adoc[]

include::com.inc.adoc[]

include::forces.inc.adoc[]

include::area_volume.inc.adoc[]

include::rnd.inc.adoc[]

include::shape.inc.adoc[]

:leveloffset: -2

== TODO

* gen generate `pp` from cell template (`rbc.off`) and initial condition
files (`rbcs-ic.txt`)
* stretch apply a force to every vertex of every cell, force is set from
a file `rbc.stretch`

