= Red blood cell

Red blood cell membranes are represented via particles with
connectivity.

This module stores the required quantities and functions for:

* initializing red blood cells positions and orientations
* managing particles and connectivity
* membrane force computations

== Quantities

`RbcQuants` structure contains particles of membrane and connectivity.

[source, c++]
----
include::{src}/rbc/type.h[tag=quants]
----

The above data structure is allocated and freed using:

[source, c++]
----
include::{src}/rbc/imp.h[tag=mem]
----


[source, c++]
----
include::{src}/rbc/imp.h[tag=ini]
----
<1> Generate quantities from file "ic" (see matrices submodule)
<2> Generate quantities from restart
<3> Dump a restart state of the quantities

Available mesh are stored in `src/data/cells`

== Submodules



* adj adjacency list: a structure to pack mesh to read on device
* com compute center of mass
* edg store information for every edge (host)
* internal forces: link:forces{lext}[forces]
* gen generate `pp` from cell template (`rbc.off`) and initial condition
files (`rbcs-ic.txt`)
* link:com[main] initialization, restart
* rnd random numbers for internal forces
* rnd/api low level api for random number generator
* force/area_volume compute area and volume
* stretch apply a force to every vertex of every cell, force is set from
a file `rbc.stretch`

See also `src/u/rbc`, `src/test/rbccom`, `src/test/rbc`

