#!/bin/bash

# u.deps and u.obj are from
# see git@gitlab.ethz.ch:mavt-cse/clarity

special () { # TODO: exclude glb.cu
    printf '%s\n' $* | awk '!/glb\.cu$/' | awk '!/bund\.cu$/'
}

D=../u/hw

# run from src
l="../u/hw/main.cu msg.cpp m.cpp l/m.cpp"
l0=`special $l`

d=$D/make/dep.mk
o=$D/make/obj.mk
m=$D/make/dir.mk
r=$D/make/rule.mk

u.deps $l > $d
u.obj  $l > $o
u.mdir $l > $m
u.rule $l0 > $r

echo upd: $d $o $m $r >&2
