#!/bin/sh

usg() {
    echo "usage: $name <LX> <LY> <LZ>  <output dir> <0.bop> <1.bop> ... -- <i0.bop> <i1.bop> ..." >&2
    exit
}

bn ()  { basename "$1" .bop; }
bov () { echo `bn "$1"`; }

exec0 () {
    if test -z ${DRYRUN+x}
    then "$@"
    else printf '%s\n' "$*"
    fi
}

# shift global variable $a
shift0 ()  { shift; echo "$@"; }
one0  ()  { echo "$1"; }
shift_a () { a=`shift0 $a`; }
one_a  () { one0 $a; }
###

main () {
    a="$@"
    while test $# -ne 0
    do f="$1"; shift
       if test "$f" = --; then break; fi
    done

    while test $# -ne 0
    do f=`one_a`; shift_a
       i="$1";    shift
       o=`out "$f"`
       Exec $LX $LY $LZ "$f" "$i" "$d/$o"
    done
}

mkdir0 () {
    exec0 mkdir -p -- "$d"
    mkdir -p -- "$d"
    if test ! -z ${DRYRUN+x}; then return; fi
    if ! test -d "$d"
    then printf '%s: cannot create dir %s\n' "$name" "$d"
	 exit 1
    fi
}

Exec () { exec0 u.color.density "$@"; }
out () { bov "$@"; }

if test $# -ne 0 -a "$1" = -h; then usg; fi

LX="$1"; shift
LY="$1"; shift
LZ="$1"; shift

# output directory
d="$1"; shift
mkdir0

main "$@"
