#!/bin/sh

usg() {
    echo "usage: u.colors2minmax <XT> <T0> <T1> <0.bov> <1.bov> ..." >&2
    exit
}

exec0 () {
    if test -z ${DRYRUN+x}
    then "$@"
    else printf '%s\n' "$*"
    fi
}

main () {
    while test $# -ne 0
    do i="$1";    shift
       Exec $XT $T0 $T1 "$i"
    done
}

Exec () { exec0 u.color.minmax "$@"; }

if test $# -ne 0 -a "$1" = -h; then usg; fi

XT="$1"; shift
T0="$1"; shift
T1="$1"; shift

main "$@"
