= clist
:lext: .adoc
:src: ../../../src

Helpers to find which particles are in a given cell.

* reorder data according to particle positions into cells
* access particles within a given cell

== example

consider a 1D example of particles with positions in domain `[0, 4)`

----
pp: 2.5 0.1 1.1 0.5 1.6
----

After cell list building (we take 1 as cell size), the above data becomes

----
pp: 0.1 0.5 1.1 1.6 2.5  -
cc: 2       2       1    0
ss: 0       2       4    5
----
where `pp` is the particle array, `cc` (counts) is the number of particles per
cell and `ss` (starts) is the prefix sum of `cc`.

Accessing all particles in cell `i=1` (`[1,2)`) can be done as follows:

```
loop: j = 0, ..., cc[i]
      id = ss[i] + j
      p = pp[id]
      work(p)
```

The above can be easily extended in 3D, only ordering changes.

== data structures

=== Clist

[source,cpp]
----
include::{src}/clist/imp.h[tag=clist]
----

* `dims` dimesnsions of the grid
* `ncells` number of cells
* `counts` number of particles per cell
* `starts` exclusive prefic scan of the above

=== Map

Helper to build the cell lists (hidden from client)

[source,cpp]
----
include::{src}/clist/imp/type.h[tag=map]
----

* `nA` number of source arrays
* `ee` cell entries: one array per source array, containing a list of
  `uchar4` with entries (`xcid`, `ycid`, `zcid`, `sid`)
  ** `xcid`: x cordinate of the cell, in 0, ..., `dims.x`
  ** `ycid`: y cordinate of the cell, in 0, ..., `dims.y`
  ** `zcid`: z cordinate of the cell, in 0, ..., `dims.z`
  ** `sid`: source array id, in 0, ..., `nA`
* `ii` indices of particles to fetch. can be decoded into the source
  array id and the particle id inside this array
* `scan` scan workspace, see link:algo/scan{lext}[scan]

The ids can be accessed from

[source,cpp]
----
include::{src}/clist/imp.h[tag=access]
----


== interface

allocate/deallocate

[source,cpp]
----
include::{src}/clist/imp.h[tag=mem]
----

build interface:

[source,cpp]
----
include::{src}/clist/imp.h[tag=int]
----

Device interface: code/decode map ids

[source,cpp]
----
include::{src}/clist/code.h[tag=int]
----


== algorithm

The cell build process is linear in number of particles `np` and `n log(n)`
in number of cells `n`.
The process to build cell lists is as follows:

----
- build ee and counts: O(np)
  - set counts[i] = 0 for all i
  - for each particle, compute its cell id cid
  - get unique subindex k within the cell by updating cc[cid]
- scan counts to get starts O(nlog n)
- construct ii: O(np)
  - for each particle with id i, compute new index j = ss[cid] + k[i]
  - set ii[j] = i
- Gather data: O(np)
  - new particle vector pp1 from pp: pp1[i] = pp[ii[i]]
----
