= clists

Cell lists
Purpose: reorder data according to particle positions into cells

== data structures

=== Clist

Helpers to find which particles are in which cells.

[source,c++]
----
struct Clist {
    int3 dims;
    int ncells;
    int *starts, *counts;
};
----

* `dims` dimesnsions of the grid
* `ncells` number of cells
* `counts` number of particles per cell
* `starts` exclusive prefic scan of the above

=== Map

Helper to reorder the arrays

[source,c++]
----
struct Map {
    int nA;              /* number of source arrays to build the cell lists, e.g remote+bulk -> 2 */
    uchar4 *ee[MAXA];    /* cell entries */
    uint *ii;            /* codes containing: indices of data to fetch and array id from which to fetch */
    scan::Work scan;     /* scan workspace */
};
----

* `nA` number of source arrays
* `ee` cell entries: one array per source array, containing a list of
  `uchar4` with entries (xcid, ycid, zcid, sid)
  ** xcid: x cordinate of the cell, in 0, ..., dims.x
  ** ycid: y cordinate of the cell, in 0, ..., dims.y
  ** zcid: z cordinate of the cell, in 0, ..., dims.z
  ** sid: source array id, in 0, ..., nA
* `ii` indices of particles to fetch. can be decoded into the source
  array id and the particle id inside this array
* `scan` scan workspace, see link:/doc/DEV/modules/scan.adoc[scan]
