= parser

:src: ../../../src

== purpose

* wrapper for the `libconfig` library
* holds configurations from 4 sources:
** set by program (priority 4)
** arguments (priority 3)
** configuration file (priority 2)
** default parameters (priority 1)

When retrieving a value, the source with higher priority is used.
If not found in a source, the value is retrieved from the next highest
priority.
If no source contains the parmeter, an error is raised.

== data structure

[source, c++]
----
include::{src}/conf/imp.cpp[tag=struct]
----

Consists of an array of `config_t` descriptors, ordered by priority.
Indices correspond to the `enum` keys.
The first key has the highest priority, second key has second highest
priority etc.

== interface

Allocate and free the structure:

[source, c++]
----
include::{src}/conf/imp.h[tags=mem]
----


Read data from the default, optional and command line config:

[source, c++]
----
include::{src}/conf/imp.h[tags=ini]
----


Lookup variables from the configuration:

[source, c++]
----
include::{src}/conf/imp.h[tags=lookup]
----
Note that the program raises an error if the argument is not found or
if an error occured (e.g. wrong type).


Lookup variables from the configuration:

[source, c++]
----
include::{src}/conf/imp.h[tags=opt]
----
The program does not raise error if the variable is not found.
The return value is `true` if the variable has been found and `false`
otherwise.


The client may overwrite variables in the config object:

[source, c++]
----
include::{src}/conf/imp.h[tags=set]
----
`desc` is an array containing the names of the nested groups.
`n` is the nesting level of the description (minimum is 1). It is the
same as the size of `desc`.

Example:

[source, c++]
----
const char *desc[] = {"main", "sub", "a"};
int n = 3;
----

will correspond to

[source, c++]
----
main = {
    sub = {
        a = ...
    }
}
----

The written fields may be dumped in a stream using
[source, c++]
----
include::{src}/conf/imp.h[tags=dump]
----
