[[conf]]
= conf: runtime configuration

== purpose

* wrapper for the `libconfig` library
* holds configurations from 4 sources:
** set by program (priority 4)
** arguments (priority 3)
** configuration file (priority 2)
** default parameters (priority 1)

When retrieving a value, the source with higher priority is used.
If not found in a source, the value is retrieved from the next highest
priority.
If no source contains the parmeter, an error is raised.

== data structure

[source, c++]
----
include::{src}/conf/imp/type.h[tag=struct]
----

Consists of an array of `config_t` descriptors, ordered by priority.
Indices correspond to the `enum` keys.
The first key has the highest priority, second key has second highest
priority etc.

The `r` field is the configuration history, i.e what is read by the program.

== interface

Allocate and free the structure:

[source, c++]
----
include::{src}/conf/imp.h[tags=mem]
----


Read data from the default, optional and command line config:

[source, c++]
----
include::{src}/conf/imp.h[tags=ini]
----


Lookup variables from the configuration:

[source, c++]
----
include::{src}/conf/imp.h[tags=lookup]
----
Note that the program raises an error if the argument is not found or
if an error occured (e.g. wrong type).


Lookup variables from the configuration:

[source, c++]
----
include::{src}/conf/imp.h[tags=opt]
----
The program does not raise error if the variable is not found.
The return value is `true` if the variable has been found and `false`
otherwise.


The client may overwrite variables in the config object:

[source, c++]
----
include::{src}/conf/imp.h[tags=set]
----
`desc` contains the names of the nested groups. separated by a `.` or
a `/`.

Example:

[source, c++]
----
const char *desc = "main.sub.a";
----

will correspond to

[source, c++]
----
main = {
    sub = {
        a = ...
    }
}
----

The configuration can be dumped by using

[source, c++]
----
include::{src}/conf/imp.h[tags=dump]
----
<1> dump the fields set by the program to a stream
<2> dump the fields read by the program to a stream

