= coords
:lext: .adoc
:src: ../../../src
:stem: latexmath

Coordinate transforms utility.

In _uDeviceX_, the simulation domain is decomposed into a grid of
subdomains of equal sizes.
Computations are performed in _local_ coordinates and all objects are
relative to these coordinates.
Operations, such as initialisation of the data, io, etc., need
_global_ coordinates informations.

For convenience, we consider the three coordinate systems:

* _Global_: Relative to the lower corner of the full domain of size
   stem:[(G_x, G_y, G_z)]
* _Local_: Relative to the center of the subdomain of size
  stem:[(L_x, L_y, L_z)]
* _Center_: Relative to the center of the full domain: stem:[(C_x,
   C_y, C_z) = (G_x/2, G_y/2, G_z/2)]

== data structures

All the needed information is stored in the hidden structure `Coords`.
A _view_ structure `Coords_v` is public to device code:

[source,cpp]
----
include::{src}/coords/type.h[tag=view]
----

== Host interface

=== Memory management

[source,cpp]
----
include::{src}/coords/ini.h[tag=mem]
----
<1> allocate and set the data according to the cartesian communicator
<2> deallocate the structure 


=== Getters

Obtain a view structure from `Coords`:

[source,cpp]
----
include::{src}/coords/imp.h[tag=view]
----

Get stem:[(G_x, G_y, G_z)]:

[source,cpp]
----
include::{src}/coords/imp.h[tag=domainsz]
----

Get stem:[(L_x, L_y, L_z)]:

[source,cpp]
----
include::{src}/coords/imp.h[tag=subdomainsz]
----

Get (from _local_ coordinates) stem:[(-L_x/2, -L_y/2, -L_z/2)] and
stem:[(L_x/2, L_y/2, L_z/2)] in _global_ coordinates:

[source,cpp]
----
include::{src}/coords/imp.h[tag=bblocal]
----


=== Coordinate transforms

From _local_ coordinates to _center_ coordinates:

[source,cpp]
----
include::{src}/coords/imp.h[tag=local2center]
----

From _center_ coordinates to _local_ coordinates:

[source,cpp]
----
include::{src}/coords/imp.h[tag=center2local]
----

From _local_ coordinates to _global_ coordinates:

[source,cpp]
----
include::{src}/coords/imp.h[tag=local2global]
----

From _global_ coordinates to _local_ coordinates:

[source,cpp]
----
include::{src}/coords/imp.h[tag=global2local]
----

=== helpers

[source,cpp]
----
include::{src}/coords/imp.h[tag=int]
----
