= distr
:lext: .adoc
:src: ../../../src

Redistribution of quantities across nodes.
Each node has a local coordinate system. The origin is the center of a
"subdomain" of size `Sx`, `Sy`, `Sz`.

A quantity is sent to a neighboring rank if its position is outside of
the subdomain.

The workflow is very similar for every quantity to redistribute:
* build a map from the positions of the quatities and store it in a
  `Map` structure.
* pack the data using `Map` in a `Pack` structure
* communicaion: exchange packed data with neighbors, receive data into
  `Unpack` structure. This is done using the
  link:comm{lext}[generic communicator].
* Unpack the data from `Unpack` to quantities.

== map

Helper for packing data to send buffers. This is common to all quantities.

=== data structure

The structure to map local data from an array to packed data in 27
arrays is implemented as:

[source,cpp]
----
include::{src}/distr/map/type.h[tag=struct]
----

This can be allocated on device or on host memory (see interface).

=== interface

TODO

== flu

Redistribute solvent particles accross nodes.

=== data structures

Solvent distribution follow the common workflow described above and
contains the three generic data structures:

[source,cpp]
----
include::{src}/distr/flu/type.h[tag=struct]
----

where `[d,h]xx` means quantities on `[device,host]` and `pp`
corresponds to particles, `cc` to colors and `ii` to global ids.
The `xxre` variables in `Unpack` are buffer for remote quantities.

=== interface

[source,cpp]
----
include::{src}/distr/flu/imp.h[tag=interface]
----

The map is build from link:partlist{lext}[partlist], allowing the
process to delete particles.

The solvent distribution also include cell list generation (see
link:clist{lext}[cell lists]).
It is done in two phases:
* subindices, independant for bulk and remote particles
* gather, which needs the subindices to be computed
Bulk subindices can be computed while comunicating remote particles.

[source,cpp]
----
include::{src}/distr/flu/imp.h[tag=clist]
----



== rbc

Redistribute red blood cells accross nodes according to the center of
mass of their bounding box (see link:algo/minmax{lext}[minmax]).

=== data structures

RBC distribution follows the common workflow described above and
contains the three generic data structures:

[source,cpp]
----
include::{src}/distr/rbc/type.h[tag=struct]
----

where `minext` and `maxext` contain the bounding box informations of
each RBC. Other variables have the same naming conventions than `distr::flu`.

=== interface

[source,cpp]
----
include::{src}/distr/rbc/imp.h[tag=interface]
----

Note that `unpack_bulk` can be done before unpacking halo quantities.




== rig

Redistribute rigid objects accross nodes according to their center of
mass.

=== data structures

Rigid bodies distribution is very similar to the above. The data
structures fits again in the general workflow:

[source,cpp]
----
include::{src}/distr/rig/type.h[tag=struct]
----

=== interface

[source,cpp]
----
include::{src}/distr/rig/imp.h[tag=interface]
----

Note that `unpack_bulk` can be done before unpacking halo quantities.
