= distr
:lext: .adoc
:src: ../../../src

Redistribution of quantities across nodes.
Each node has a local coordinate system. The origin is the center of a
"subdomain" of size `Sx`, `Sy`, `Sz`.

A quantity is sent to a neighboring rank if its position is outside of
the subdomain.

The workflow is very similar for every quantity to redistribute:
* build a map from the positions of the quatities and store it in a
  `Map` structure.
* pack the data using `Map` in a `Pack` structure
* communicaion: exchange packed data with neighbors, receive data into
  `Unpack` structure. This is done using the
  link:comm{lext}[generic communicator].
* Unpack the data from `Unpack` to quantities.

== map

Helper for packing data to send buffers. This is common to all quantities.

=== data structure

The structure to map local data from an array to packed data in 27
arrays is implemented as:

[source,cpp]
----
include::{src}/distr/map/type.h[tag=struct]
----

This can be allocated on device or on host memory (see interface).

=== interface

TODO

== flu

Redistribute solvent particles accross nodes.

=== data structures

Solvent distribution follow the common workflow described above and
contains the three generic data structures:

[source,cpp]
----
include::{src}/distr/flu/type.h[tag=struct]
----

=== interface

[source,cpp]
----
include::{src}/distr/flu/imp.h[tag=interface]
----

== rbc
TODO

== rig
TODO
