[[grid_sampler]]
= grid_sampler: particle to grid average

:stem: latexmath

gather particle data on a grid and average in time.
The particle to grid process is simple binning.

== quantities

The number density and velocity (3 components) are computed by
default.
Optionally, the stress tensor (6 components) and the color proportions
can be sampled as well.

All cell quantities computed at a given time stem:[t] are averaged on time:

[stem]
++++
Q^i = \frac 1 T \sum\limits_{t = 1}^T Q^i_t
++++

The cell quantities stem:[Q^i_t] are averaged on space, depending on
the quantity. Let stem:[j \in [1, n_i]] denote the particle ids inside
cell stem:[i], where stem:[n_i] is the number of particles inside this
cell. stem:[V_i] denotes the volume of the cell.

Velocity:

[stem]
++++
\mathbf{u}^i_t = \frac{1}{n_i} \sum\limits_{j = 1}^{n_i} \mathbf{u}_j
++++

number density:

[stem]
++++
\rho^i_t = \frac{n_i}{V_i}
++++

stress:

[stem]
++++
S^i_{\alpha, \beta} = \frac{1}{V_i} \sum\limits_{j = 1}^{n_i} S_j^{\alpha, \beta}
++++

color proportion:

[stem]
++++
c^i_{\alpha} = \frac{1}{n_i} \sum\limits_{j = 1}^{n_i} \delta_{c_j, \alpha}
++++


== interface

Allocate and free the structure:

[source, c++]
----
include::{src}/grid_sampler/imp.h[tags=mem]
----
<1> create a sampler for binning a subdomain of size `L`. `N` is the
    number of bins. Allocate space for stress when `stress` is set to
    true. Allocate space for the color proportions when `colors` is
    set to true.
<2> deallocate the structure

The sampler object stores the grid data. All operations are performed
on device:

[source, c++]
----
include::{src}/grid_sampler/imp.h[tags=int]
----
<1> set all fields of the grids to 0
<2> add contribution of the data (see <<grid_sampler_data>>) to the
    time averaged grid
<3> perform time average of all gathered data, download grid on host
    and dump to file (see <<io_grid>>).


[[grid_sampler_data]]
== grid sampler data

helper to pass data to the grid sampler.

allocate and deallocate the data structure:

[source, c++]
----
include::{src}/grid_sampler/imp.h[tags=data_mem]
----

pass data to the structure:

[source, c++]
----
include::{src}/grid_sampler/imp.h[tags=data_int]
----
<1> remove all previously pushed data
<2> add data (pointers only, *not* a deep copy) to the structure. The
    `pp` pointer is mandatory. The stress `ss` pointer is used only when
    `stress` is activated in grid sampler. The colors `cc` pointer is
    only used when `colors` is activated in the grid sampler.
