= pair
:lext: .adoc
:src: ../../../src
:stem: latexmath

pairwise forces.
manages the parameters for dpd and repulsive Lennard-Jones parameters.

== dpd interactions

DPD particles interact via the following force:

[stem]
++++
\mathbf{F}_{ij} = \left( F_{ij}^C + F_{ij}^R + F_{ij}^D \right) \mathbf{e}_{ij}
++++

where

[stem]
++++
F_{ij}^C = \alpha \max \left( 1 - \frac{r_{ij}} {r_c}, 0 \right)
++++

[stem]
++++
F_{ij}^R = \sigma w(r_{ij}) W_{ij}
++++

[stem]
++++
F_{ij}^D = -\gamma w(r_{ij})^2 \mathbf{v}_{ij} \cdot \mathbf{r}_{ij}
++++

with
[stem]
++++
\mathbf{r}_{ij} = \mathbf{r}_i - \mathbf{r}_j, \\
r_{ij} = | \mathbf{r}_{ij} |, \\
\mathbf{v}_{ij} = \mathbf{v}_i - \mathbf{v}_j.
++++

The viscous kernel is given by

[stem]
++++
w(r) = r^{\frac{1}{2^s}},
++++
where stem:[s] is the `S_LEVEL` compile time option set to `2` by default.

== repulsive LJ

Repulsive forces for contact are implemented using the repulsive LJ
potential. It is given by

[stem]
++++
\mathbf{F}_{ij} = F_{ij}^{rLJ} \mathbf{e}_{ij}
++++

where

[stem]
++++
F_{ij}^{rLJ} = \max \left( 0, F^{LJ}(r_{ij})\right)
++++

[stem]
++++
F^{LJ}(r) = 24 \epsilon \frac{1}{r} \left( 2 \left[\frac \sigma r
\right]^12 - \left[\frac \sigma r \right]^6 \right)
++++

for numerical reasons, the magnitude is limited to stem:[10^4].

== Host interface

allocate, deallocate the structure:

[source,cpp]
----
include::{src}/pair/imp.h[tag=mem]
----

set parameters:

[source,cpp]
----
include::{src}/pair/imp.h[tag=set]
----

set parameters from configuration file:

[source,cpp]
----
include::{src}/pair/imp.h[tag=cnf]
----

the argument `name_space` denotes the namespace where to look for the
parameters (see below).


Compute the stem:[\sigma] parameter for a given temperature and timestep:

[source,cpp]
----
include::{src}/pair/imp.h[tag=mem]
----

Get the different views:

[source,cpp]
----
include::{src}/pair/imp.h[tag=view]
----

== device interface

Inside a CUDA kernel, the pairwise force can be called by the generic function

[source,cpp]
----
include::{src}/pair/dev.h[tag=int]
----

The `PairPa` structure is a generic particle with color.
The `PairFo` structure is a generic force.
The input parameter `Param p` is a view for pair parameters.

The above function behaves differently given different types:

* `PairDPD`: standard DPD interaction
* `PairDPDLJ`: standard DPD and repulsive LJ interaction
* `PairDPDC`: _colored_ DPD interaction: pick up parameters as a function
  of the particle colors
* `PairDPDCM`: _mirrored_ DPD: same as _colored_ DPD considering that
  particle `b` has the same color than particle `a`.



== Configuration

TODO

[source,cfg]
----
TODO
----
