= parser

:src: ../../../src

== purpose

* wrapper for the `libconfig` library
* holds configurations from 4 sources:
** set by program (priority 4)
** arguments (priority 3)
** configuration file (priority 2)
** default parameters (priority 1)

When retrieving a value, the source with higher priority is used.
If not found in a source, the value is retrieved from the next highest
priority.
If no source contains the parmeter, an error is raised.

== data structure

[source, c++]
----
include::{src}/parser/imp.cpp[tag=struct]
----

Consists of an array of `config_t` descriptors, ordered by priority.
Indices correspond to the `enum` keys.
The first key has the highest priority, second key has second highest
priority etc.

== interface

Allocate and free the structure:

[source, c++]
----
include::{src}/parser/imp.h[tags=mem]
----


Read data from the default, optional and command line config:

[source, c++]
----
include::{src}/parser/imp.h[tags=ini]
----


Lookup variables from the configuration:

[source, c++]
----
include::{src}/parser/imp.h[tags=lookup]
----
Note that the program raises an error if the argument is not found.


Lookup variables from the configuration:

[source, c++]
----
include::{src}/parser/imp.h[tags=opt]
----
The program does not raise error if the variable is not found.
The return value is `true` if the variable has been found and `false` otherwise.
