= wvel

:src: ../../../src
:stem: latexmath

wall velocity field

== purpose

* set velocity to wall particles for wall interactions
* get wall velocity for bounce back on walls

== data structures

data structures are separated into 3 kinds of data structures:

* `Wvel` (hidden), which contains all informations needed for the velocity
  field. It is hold and maintained on host.
* `WvelStep` (hidden), containing only the information needed for one
   specific time step. It is generated from `Wvel` structure.
* Views, passed to kernels. They are generated from the `WvelStep` structure.

== interface 

Interface is splitted between host and device

=== Host
Host code is responsible for initialisation of `Wvel` and convert
`Wvel` to a view at a given timestep.

alloc, free structures:

[source, c++]
----
include::{src}/wall/wvel/imp.h[tag=mem]
----

Set velocity type from parameters:

[source, c++]
----
include::{src}/wall/wvel/imp.h[tag=ini]
----

Set velocity type from configuration:

[source, c++]
----
include::{src}/wall/wvel/imp.h[tag=cnf]
----

Get _step_ structure:

[source, c++]
----
include::{src}/wall/wvel/imp.h[tag=step]
----

Get _view_ structures:

[source, c++]
----
include::{src}/wall/wvel/imp.h[tag=view]
----

The convertion to _view_ structures can be dispatch using the type of
the parameters:

[source, c++]
----
include::{src}/wall/wvel/imp.h[tag=enum]
----
which can be retrieved from the _Step_ structure using

[source, c++]
----
include::{src}/wall/wvel/imp.h[tag=get]
----


=== Device

Velocity field can be retrieved, depending on the view structure, using

[source, c++]
----
include::{src}/wall/wvel/dev.h[tag=vel]
----


Bounce function: gives bounced-back velocity from
position and velocity of particle.

[source, c++]
----
include::{src}/wall/wvel/dev.h[tag=bb]
----

== Configuration

=== constant

constant velocity stem:[u = (1, 0, 0)]:

[source, cfg]
----
wvel {
    type = "constant"
    u    = [1.0, 0.0, 0.0]
}
----

=== shear

shear velocity stem:[u = (3 y, 0, 0)]:

[source, cfg]
----
wvel {
    type = "shear"
    gdot = 3.0
    vdir = 0
    gdir = 1
    half = 0
}
----

=== sinusoidal shear

shear velocity stem:[u(t) = (3 y \sin(5 t), 0, 0)]:

[source, cfg]
----
wvel {
    type = "shear sin"
    gdot = 3.0
    vdir = 0
    gdir = 1
    w = 5.0
}
----

=== Hele Shaw 

velocity stem:[u_r = \frac u r \left(1 - \frac {4 z^2}{h^2}\right)]:

[source, cfg]
----
wvel {
    type = "hele shaw"
    u = 1.0
    h = 8.0
}
----
