= wvel

:src: ../../../src
:stem: latexmath

wall velocity field

== purpose

* set velocity to wall particles for wall interactions
* get wall velocity for bounce back on walls

== data structures

data structures are separated into 2 kinds of data structures:

* `Wvel`, which contains all informations needed for the velocity
  field. It is hold and maintained on host.
* `Wvel_v` (`Wvel view`), containing only the information needed for one
   specific time. It is passed to device kernels.

== interface 

Interface is splitted between host and device

=== Host
Host code is responsible for initialisation of `Wvel` and convert
`Wvel` to a view at a given timestep.

alloc, free structure:

[source, c++]
----
include::{src}/wvel/imp.h[tag=mem]
----

Set velocity type from parameters:

[source, c++]
----
include::{src}/wvel/imp.h[tag=ini]
----

Set velocity type from configuration:

[source, c++]
----
include::{src}/wvel/imp.h[tag=cnf]
----

Get _view_ structure:

[source, c++]
----
include::{src}/wvel/imp.h[tag=int]
----


=== Device

Device code contains the functions describing the field.
Also contains bouncer function: gives bounced-back velocity from
position and velocity of particle.

[source, c++]
----
include::{src}/wvel/dev.h[tag=dev]
----

== Configuration

=== constant

constant velocity stem:[u = (1, 0, 0)]:

[source, cfg]
----
wvel {
    type = "constant";
    u    = [1.0, 0.0, 0.0];
};
----

=== shear

shear velocity stem:[u = (3 y, 0, 0)]:

[source, cfg]
----
wvel {
    type = "shear";
    gdot = 3.0;
    vdir = 0;
    gdir = 1;
    half = 0;
};
----

=== sinusoidal shear

shear velocity stem:[u(t) = (3 y \sin(5 t), 0, 0)]:

[source, cfg]
----
wvel {
    type = "shear sin";
    gdot = 3.0;
    vdir = 0;
    gdir = 1;
    half = 0;
    w = 5.0;
    log_freq = 1000;
};
----

in this case, the value stem:[3 * \sin(5 t)] is printed every 1000 iterations.

=== Hele Shaw 

velocity stem:[u_r = \frac u r \left(1 - \frac {4 z^2}{h^2}\right)]:

[source, cfg]
----
wvel {
    type = "hele shaw";
    u = 1.0;
    h = 8.0;
};
----
