= configuration files
:lext: .adoc

== glb
Global parameters.

`L = [int, int, int]`::
  a size of each of the subdomains
`restart = bool`::
  continue from a restart?
`kBT = float`::
  solvent temerature
`numdensity = int`::
  solvent number density in initilization

== time
Control simulation time.

`type = "const"|"disp"`::
  a strategy for time step.
`end = float`::
  when to end the simulation?
`wall = float`::
  when to create wall?
`screenlog = bool`::
  log time step to `stderr`?

=== `type = const`

Timestep is constant

`dt = float`::
  timestep

=== `type = disp`

The time step is adjusted base on the forces (TODO)

`dt = float`::
  initial timestep
`dx = float`::
  maximum displacement

== flu
Solvent parameters.

== rbc
RBC membrane.

== rig
Rigid body.

== wall
Wall boundary condition parameters

== fsi
Fluid-structure interaction.

== cnt
Contact between rigid objects and membranes.

== bforce
Body force: constant in time force applied to solvent, membranes, and rigid objects.

== wvel
Wall velocity.

== dump
Controls what and when to dump.

== inflow
Inflow boundary conditions for velocity.

== outflow
Outflow boundary condition for velocity.

== denoutflow
Density outflow boundary condition.

== iccolor
How to color particle of the solvent?

== restrain
Restrain some solvent particles or particles of the membranes.

== vcon
Velocity controller: apply body condition to maintain prescribed average velocity.

== recolor
Change color of some solvent particles durining the simulation.

== dflu
Parameters for solvent distribtuion between MPI processes.

== dbg
Debug options.
