= configuration parameters

// TODO
:default: {src}/../conf/default.cfg
:examples: {src}/../examples
// TODO: make it look better
// :CFG: source,cfg
:CFG: source

_uDeviceX_ is configured via runtime parameters.
These parameters are passed by the program via three mechanisms:

* <<defaults, default parameters>> (priority 0)
* file parameters `conf.cfg`(optional) (priority 1)
* arguments `args` (optional) (priority 2)

The program can be run as follows (for one node):

[source, sh]
----
udx [conf.cfg] [args]
----

When reading parameters, the program will select the one with highest
priority.
This makes it easy to overwrite the default parameters.

A file named `conf.history.cfg` is dumped once the program has read
all parameters. The file contains all parameters which have beed read
by `udx`.

[[defaults]]
== Default parameters

We describe here the default parameters, contained in the file `${HOME}/.udx/default.cfg`.

=== glb: global parameters

Global parameters

[{CFG}]
----
include::{default}[tag=glb]
----
<1> create initial conditions from restart files
<2> temperature of the system (supposed uniform)
<3> number density of solvent particles


=== time

Time related parameters.

[{CFG}]
----
include::{default}[tag=time]
----
<1> time of freezing step
<2> dump the timestep informations to the console


=== flu

Describe the solvent parameters
// TODO
A description of the DPD parameters can be found in <<>>.

[{CFG}]
----
include::{default}[tag=flu]
----
<1> mass of one particle
<2> each particle has a different color if set to `true`
<3> each particle has unique global index if set to `true`
<4> compute solvent stresses if set to `true`
<5> recolor the solvent according to membranes every `x` iterations;
    `0`: deactivated; membranes must be active if set to non `0`.
<6> apply body forces on solvent if set to `true`

