[[defaults]]
= Default parameters

We describe here the default parameters, contained in the file `${HOME}/.udx/default.cfg`.

== glb: global parameters

Global parameters

[{CFG}]
----
include::{default}[tag=glb]
----
<1> create initial conditions from restart files
<2> temperature of the system (supposed uniform)
<3> number density of solvent particles

== time

Time related parameters.

[{CFG}]
----
include::{default}[tag=time]
----
<1> time of freezing step
<2> dump the timestep informations to the console

== flu

Describe the solvent parameters
// TODO
A description of the DPD parameters can be found in <<>>.

[{CFG}]
----
include::{default}[tag=flu]
----
<1> mass of one particle
<2> each particle has a different color if set to `true`
<3> each particle has unique global index if set to `true`
<4> compute solvent stresses if set to `true`
<5> recolor the solvent according to membranes every `x` iterations;
    `0`: deactivated; membranes must be active if set to non `0`.
<6> apply body forces on solvent if set to `true`

== debug parameters

We list here default debug parameters

[{CFG}]
----
include::{default}[tag=dbg]
----
<1> activate debug mode for solvent distribution
<2> activate verbose for debug informations
<3> activate dump informations for debug modes
<4> check positions of solvent
<5> check positions of solvent and objects
<6> check velocities
<7> check forces
<8> check colors of solvent
<9> check cell lists
