#!/bin/sh

set -u
. u.adoc2html.util

if test $# -eq 0; then exec "$ADOC"; fi

i="$1"; shift
for c; do shift; set -- "$@" "$i"; i="$c"; done
# i =  the last arguments
# "$@" the rest of the arguments

a="-a lext=.html
   -a source-highlighter=pygments
   -a nofooter
   -a disable-javascript
   -a linkcss"

e "$ADOC" $a -b html5 "$@" "$i"
