#!/bin/sh

: ${DBG=0}
: ${ADOC=asciidoctor}

msg () { echo >&2 "$@"; }
e0 () {
   if test "$DBG" != 0; then msg "cmd: $@"; fi
   eval "$@"
}
e () {
   e0 "$@"
   if test $? -ne 0; then msg "fail: $@"; exit 2; fi
}
