/* G: domain size
   N: number of cells in sdf files
   lo: low edge of a subdomain
   L:  subdomain size
   T: number of cells in texture
   M: texture margin
*/

load("scifac") $
load("format") $
load("u.mac") $
fmt0(e, r):=format(fullratsimp(e), %poly(r), %factor) $
fmt(f):=fmt0(f('r), 'r)                               $

[sdf2g, g2sdf]: genfi(-1/2,      0,   N-1/2,          G) $
[tex2g, g2tex]: genfi(-1/2, lo - M,   T-1/2, lo + L + M) $
[sub2g, g2sub]: genfi(-L/2, lo,       0, lo + L/2)       $

tex2sdf: chain(tex2g, g2sdf) $
sdf2tex: chain(sdf2g, g2tex) $
sub2tex: chain(sub2g, g2tex) $

gcfac(fmt(sub2tex));

/* from `sdf/dev.h` */
e: T * (r + L / 2 + M) / (L + 2 * M) - 1/2;
fmt0(e, 'r);

[f2g, g2f]: genfi(-L/2,        lo,    0,           lo + L/2) $
[t2g, g2t]: genfi(-1/2,      t_lo,   t_n-1/2,          t_hi) $
f2t       : chain(f2g, g2t);

(t_lo: lo - M, t_hi: lo + L + M, t_n: T);
map('gcfac, fmt(f2t));