/* g: global */

load("format") $
load("u.mac") $
fmt0(e, r):=format(fullratsimp(e), %poly(r), %factor) $
fmt(f):=fmt0(f('r), 'r)                               $

[sdf2g, g2sdf]: genfi(0,    0,        N, G )          $
[tex2g, g2tex]: genfi(0,    lo - M,   T, lo + L + M)  $
[sub2g, g2sub]: genfi(-L/2, lo,       0, lo + L/2)    $

tex2sdf: chain(tex2g, g2sdf) $
sdf2tex: chain(sdf2g, g2tex) $
sub2tex: chain(sub2g, g2tex) $

fmt(tex2sdf);
fmt(sub2tex);

/* from `sdf/dev.h` */
e: T * ('r + L / 2 + M) / (L + 2 * M) $
fmt0(e, 'r);
