#!/bin/sh

. plcmt.util
prog=plcmt.ro

usg () {
    msg "$prog Lx Ly Lz r     f    sc ang     solid.out rbc.out"
    msg '   ro(`rbc and solid`) : create initial conditons for rbc and solid'
    msg '   L[xyz]: domain sizes'
    msg '   r: radious of a sphere for packing'
    msg '   f: fraction of solids'
    msg '   sc: scale for RBCs'
    msg '   ang: angle of rotation around OX ("rnd" for random)'
    exit
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

if test $# -le 2; then err "expecting domain size"; fi
x="$1"; shift; y="$1"; shift; z="$1"; shift

if test $# -le 0; then err "expecting packing radious"; fi
r="$1"; shift

if test $# -le 0; then err "expecting fraction"; fi
f="$1"; shift

if test $# -le 0; then err "expecting rbc scale"; fi
s="$1"; shift

if test $# -le 0; then err "expecting RBC angle"; fi
a="$1"; shift

if test $# -le 0; then err "expecting solid.out"; fi
O="$1"; shift

if test $# -le 0; then err "expecting rbc.out"; fi
R="$1"; shift

pr=/tmp/rbc.$$; >$pr
trap 'rm -f $pr' 1 2 3 15

plcmt.hex $x $y $z $r | plcmt.select $f "$O" "$pr"
plcmt.p2mat $s $a     $pr > "$R"

rm -f $pr

# TEST: plcmt.ro.t0
# x=10 y=20 y=30 radius=1
# fraction=0.1
# sc=1 ang=0
# SEED=1234 plcmt.ro 10 20 30 $radius     $fraction    $sc $ang     solid.ic rbc.ic
# :
# (sort solid.ic; sort rbc.ic) > test.out.txt
#
