#!/bin/sh

usg0 () {
    echo 'usage: plcmt.ro Lx Ly Lz r     f    sc ang     solid.out rbc.out'
    echo '   ro(`rbc and solid`) : create initial conditons for rbc and solid'
    echo '   L[xyz]: domain sizes'
    echo '   r: radious of a sphere for packing'
    echo '   f: fraction of solids'
    echo '   sc: scale for RBCs'
    echo '   ang: angle of rotation around OX ("rnd" for random)'
}

usg() { usg0 >&2; exit; }
if test $# -ne 0 && test "$1" = -h; then usg; fi

# sphere packing
x=$1; shift; y=$1; shift; z=$1; shift; r=$1; shift
f=$1; shift # fraction
s=$1; shift; a=$1; shift # rbc parameters
O=$1; shift; R=$1; shift  # s[o]lid and [r]bc output files

pr=/tmp/rbc.$$ # tmp file with points for RBCs
trap 'rm -rf $pr' 0 1 2 3 15

plcmt.hex $x $y $z $r | plcmt.select $f $O $pr
plcmt.p2mat $s $a     $pr > $R

# TEST: plcmt.ro.t0
# x=10 y=20 y=30 radius=1
# fraction=0.1
# sc=1 ang=0
# SEED=1234 plcmt.ro 10 20 30 $radius     $fraction    $sc $ang     solid.ic rbc.ic
# :
# (sort solid.ic; sort rbc.ic) > test.out.txt
#
