#! /bin/sh

make_image() {
    IN=$1; shift
    OUT=$1; shift
    gnuplot <<EOF
set term png
set output "$OUT"
set grid
set xrange [-0.4:0.4]
set yrange [0:15]
set xlabel "x (dpd units)"
set ylabel "U (dpd units)"
plot "$IN" u 2:(\$1+7.0) w lp t ""
EOF
}

format_name() {
    f=$1  ; shift
    ext=$1; shift
    echo $f | sed "s/h5\/\([0-9]\{4\}\)/\1/" \
	| sed "s/h5/${ext}/"
}

for f in `ls h5/*[0-9].h5`; do
    P=`format_name $f "txt"`
    U=`format_name $f "png"`
    u.avgh5 1 u 2 $f > $P
    make_image $P $U
done

#make_image "profile.txt" "U.png"
