#!/usr/bin/awk -f
#
# Converts a list of coordinates "xc, yc, zc" to a list of 4x4
# transformation matrixes

function cell(x, y, z, p) {
    f0 = "%+9.3e"
    f = f0 " " f0 " " f0 " " f0 "\n"
    printf f,  s,        0,         0, x
    printf f,  0, s*cos(p), -s*sin(p), y
    printf f,  0, s*sin(p),  s*cos(p), z
    printf f,  0,        0,         0, 1
}

BEGIN {
    p = length(p) ? p : 0
    s = length(s) ? s : 1
}

{
    x = $1; y = $2; z = $3
    cell(x, y, z, p)
}
