#!/usr/bin/awk -f
#
# Converts a list of coordinates "xc, yc, zc" to a list of 4x4
# transformation matrixes

function cell0(x, y, z, px) {
    f0 = "%+9.3e"
    f = f0 " " f0 " " f0 "\n"
    printf f,  0,       0,        0, x
    printf f,  0, cos(px), -sin(px), y
    printf f,  0, sin(px),  cos(px), z
    printf f,  0,       0,        0, 1
}

BEGIN {
    px = length(px) ? px : 0.0
}

{
    x = $1; y = $2; z = $3
    cell0(x, y, z, px)
}
