/* Intersection with a plain centered at (0, 0, 0) and normal `nz' */

load("format")$
load("cgrind")$
alias(cg, cgrind);

/* make a vector */
mv(P)::=buildq([l: P,
  r: create_list(concat(P, d), d,  ['x, 'y, 'z])],
  l: r) $

mv(R0)$ mv(R1)$ /* Initial and final positions of a point */
R : R0*(1-t) + R1*t; /* Point at time t */

mv(n)$ /* normal */
nx: ny: 0; /* only nz */

eq: R . [nx, ny, nz] $
eq: format(eq, %poly(t)) $

so: linsolve(eq, t)$
t_ex: rhs(so[1])   $

nu: num(t_ex)  $
de: denom(t_ex)$

ratexpand(nu/de - t_ex) $

cg(' t = t_ex)$
