/* Intersection with a plain centered at (0, 0, 0) */

load("format")$
load("cgrind")$
alias(cg, cgrind);

/* make a vector */
mv(P)::=buildq([l: P,
  r: create_list(concat(P, d), d,  ['x, 'y, 'z])],
  l: r) $

mv(R0)$ mv(R1)$ /* Initial and final positions of a point */
R : R0*(1-t) + R1*t; /* Point at time t */

mv(P)$ /* any point on the wall */
mv(n)$ /* normal */

eq: (R - P). [nx, ny, nz] $
eq: format(eq, %poly(t)) $

so: linsolve(eq, t)$
t_ex: rhs(so[1])   $

nu: num(t_ex)  $
de: denom(t_ex)$

ratexpand(nu/de - t_ex) $

(cg('nu = nu), cg('de = de), cg(' t = 'nu/'de))$
