#!/usr/bin/awk -f

BEGIN {
    if (!emptyp(File)) cat(File)
    for (i in ARGV)
	print ARGV[i]
}
function cat(f) {
    c = sprintf("cat '%s'", f)
    system(c)
}
function emptyp(s) { return !length(s) }

# TODO: parse File, respect Over
