$B/algo/edg/imp.o: $S/algo/edg/imp.cpp; $X -I$S/algo/edg -I$S/.
$B/algo/vectors/imp.o: $S/algo/vectors/imp.cpp; $X -I$S/algo/vectors -I$S/.
$B/conf/imp.o: $S/conf/imp.cpp; $X -I$S/conf -I$S/.
$B/coords/conf.o: $S/coords/conf.cpp; $X -I$S/coords -I$S/.
$B/coords/imp.o: $S/coords/imp.cpp; $X -I$S/coords -I$S/.
$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/io/mesh/imp.o: $S/io/mesh/imp.cpp; $X -I$S/io/mesh -I$S/.
$B/io/mesh_read/edg/imp.o: $S/io/mesh_read/edg/imp.cpp; $X -I$S/io/mesh_read/edg -I$S/.
$B/io/mesh_read/imp.o: $S/io/mesh_read/imp.cpp; $X -I$S/io/mesh_read -I$S/.
$B/io/write/imp.o: $S/io/write/imp.cpp; $X -I$S/io/write -I$S/.
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/math/tform -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/u/io/mesh/main.o: $S/u/io/mesh/main.cpp; $X -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/utils -I$S/.
$B/utils/nvtx/imp.o: $S/utils/nvtx/imp.cpp; $X -I$S/utils/nvtx -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
$B/utils/string/imp.o: $S/utils/string/imp.cpp; $X -I$S/utils/string -I$S/.
