#!/bin/sh

. u.case.util

usg () {
    msg 'S=[SRC] u.case -d [case dir] -f [from] [to] -b [exec before] -a [exec after] [UNIT] [CONFIG.h] [udx conf file]'
    msg 'if DBG    is set log the commands'
    msg 'if DRYRUN is set do not run u.conf and u.make'
    exit
}

if test "$1" = -h; then usg; fi

exec u.case0 "$@"
