kill(all)$

x : r*cos(t)$
y : r*sin(t)$

xx : y^2 + z^2$
xy : -x*y$
xz : -x*z$
yy : x^2 + z^2$
yz : -y*z$
zz : x^2 + y^2$

I(e) := rho*integrate(integrate(integrate(r*e, t, 0, 2*%pi), r, 0, R), z, -L/2, L/2)$

Ixx : I(xx);
Ixy : I(xy);
Ixz : I(xz);
Iyy : I(yy);
Iyz : I(yz);
Izz : I(zz);

rhoev : 10;
Lev : 8;
Rev : 5;

evinv(e) := float(ev(1/e, L=Lev, R=Rev, rho=rhoev));

Iinvxx : evinv(Ixx);
Iinvyy : evinv(Iyy);
Iinvzz : evinv(Izz);
