#!/bin/sh

nv=1986
u.cp.rbc rbc/sc/$nv rbc.off
u.cp.rbc sph/sc/$nv rbc.stress.free

u.strtdir
u.run udx conf.cfg "
glb = { restart = false }
rbc = {
    totArea   = `off.area   rbc.off`
    totVolume = `off.volume rbc.off`
}
"
