#!/bin/sh

nv=1986
u.cp.rbc sph/sc/$nv rbc.off
u.cp.rbc sph/sc/$nv rbc.stress.free

echo run | S=`u.cp.s` u.build u/x conf.base.h
u.strtdir
u.run ./udx conf.cfg "
glb = { restart = false }
rbc = {
    totArea   = `off.area   rbc.stress.free`
    totVolume = `off.volume rbc.stress.free`
}
"
