#!/bin/sh

nv=2562
u.cp.rbc rbc/sc/$nv rbc.off
u.cp.rbc rbc/sc/$nv rbc.stress.free

u.strtdir
a=`off.area   rbc.off`
v=`off.volume rbc.off`
#p=`off.phi    $nv`
p=0.0

u.run udx conf.cfg "
glb = { 
    restart = true
    numdensity = 1
}
time = { end =  5.0 }
wvel = { gdot = 0.0 }
rbc = {
    ks  = 0.0
    kb  = 0.1
    kd   = 0.0
    x0  = 0.2
    gammaC = 100.0
    totArea   = $a
    totVolume = $v
    phi =       $p
}
"
