lmax: 'l0 / 'x0;
sq(x):=x*x;
pow(a, b):=a^b;
wlc0(r):=(4*sq(r)-9*r+6)/(4*sq(r-1));
wlc(r):=ks/lmax*wlc0(r/lmax);

fwlc: 'wlc(r);
fpow: -'wlc(l0) * pow(l0, m+1) / pow(r, m + 1);

f: (fwlc + fpow)*r;

Epow: l0^(m + 1) * 'wlc(l0) / r^(m - 1) / (m - 1);
Ewlc: block([x: 'r/lmax], ('ks / 4 * lmax) * (3 * x^2 - 2 * x^3) / (1 - x));

E: Epow + Ewlc;
fullratsimp(diff(E, r) - f), wlc;

df0: ev(diff(E, r, 2), wlc);
df0: subst(r = l0, df0);
df0: factor(df0);
