#!/usr/bin/awk -f


function rnd(l, h) { return (h - l) * rand() + l }
function rnd3() {
    x = rnd(xl, xh); y = rnd(yl, yh); z = rnd(zl, zh)
}

BEGIN {
    N = ARGV[1]
    if (!length(N)) N = 100

    ext = ARGV[2]
    if (!length(ext)) ext = 5

    xl = yl = zl = -5
    xh = yh = zh =  5

    while (N--) {
	rnd3()
	print x, y, z
    }
}
