= objects
:base: {src}/sim/objects

Manages all solutes objects.
This includes rigid objects and membranes.

== Interface

Allocate, deallocate the structure:

[source, cpp]
----
include::{base}/imp.h[tag=mem]
----

Generate the quantities:

[source, cpp]
----
include::{base}/imp.h[tag=gen]
----
<1> Generate the meshes of all objects from the template mesh and an
    initial condition files (see <<mesh_gen>>)
<2> Remove all meshes colliding with walls
<3> Build all remaining quantities after removal from walls. The rigid
    objects need solvent particles

The quantities can be instead generated from restart files:

[source, cpp]
----
include::{base}/imp.h[tag=strt]
----

The state of the objects can be dumped using

[source, cpp]
----
include::{base}/imp.h[tag=dump]
----
<1> Dump all meshes of objects
<2> Dump diagnosis. This include the solid objects dumps and the
    membrane centers of mass.
<3> Dump rigid particles in bop format
<4> Dump rigid templates to restart files
<5> Dump current state to restart files


The objects are updated using

[source, cpp]
----
include::{base}/imp.h[tag=upd]
----
<1> set all velocities to 0
<2> advance objects for one timestep;
    internal fast forces are computed there for time separation scheme
    of membranes
<3> redistribute objects accross nodes
<4> update dpd parameters given a new time step

The objects forces can be managed by calling

[source, cpp]
----
include::{base}/imp.h[tag=force]
----
<1> set all forces to 0
<2> apply body forces to the objects

The internal membrane forces are computed inside advance (see above).

Other forces can be set via the getter functions (see link with
<<sim_objinter>>):

[source, cpp]
----
include::{base}/imp.h[tag=get]
----
<1> get particle infos of all objects
<2> get particle infos of membranes
<3> retrieve acceleration infos (see <<scheme_time_step>>)
<4> get the pair parameters for fsi interactions (one per object, NULL
    for no interactions)
<5> get the parameters for adhesion interactions with walls (one per object, NULL
    for no interactions)
<6> get the parameters for repulsion with walls (one per object, NULL
    for no interactions)
<7> get the pair parameters for cnt interactions (one per object pair, NULL
    for no interactions)

[source, cpp]
----
include::{base}/imp.h[tag=tools]
----
<1> bounce solvent particles against objects
<2> recolor solvent particles located inside membranes
<3> compute the total volume occupied by all membranes

