#! /usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
plt.switch_backend('agg')

L = 16.0

D = np.loadtxt("profile.txt")

(nx, ny) = np.shape(D)

x = np.linspace(0.0, L, nx)
iy=5
u = D[:,iy]

print x
print u


plt.rc('text', usetex=True)
plt.rc('font', family='serif', size=18)

plt.figure()
plt.plot(x, u, 'k+', label="DPD")

plt.xlabel(r'$z/L$')
plt.ylabel(r'$u/u_{max}$')

#plt.xticks([-0.5, 0, 0.5])
#plt.yticks([0, 1.0])

#plt.legend(numpoints=1, frameon=False, fontsize=12)

plt.savefig("U")
