= coding conventions
:lext: .adoc

== modules

_uDeviceX_ consists of modules.
Modules are as independant as possible.
They consist of a folder with one or more compilation units, and an
interface.
Whenever it is possible, the structures are hidden from the client of
the module.

== naming

=== variables

* names of local variables are short and understandable from the context
* names of global variables are as descriptive as possible
* arrays of simple structures `x` have names `xx`, eg. `pp` is an
  array of particles, `cc` is an array of colors, `ii` is an array of
  indices * array of small dimentionality may use an enum type for
  readability, e.g.
[source,cpp]
----
enum {X, Y, Z};
int r[3];
r[X] = rx;
r[Y] = ry;
r[Z] = rz;
----

=== functions

* a function name is descriptive on its own or inside a module.
* arguments are ordered as follow:
** input is at the beginning
** input/output come after input and start with a commented `io`
** output comes after input/output and start with a comment or `o` depending on the context
** sizes have higher priority than arrays
** workspace comes at the end ans starts with a commented `w`
* do **not** use references, use pointers instead

Example of valid function declarations:

[source, cpp]
----
void read_int_from_file(const char *fname, /**/ int *n, int *ii);
void forward_euler(int n, const Force *ff, /* io */ Particle *pp);
----

Function names part of a module interface start with the module name.
Functions private to a module do not need to contain the module name
if the context make it clear. Use the `static` qualifier for functions
with compilation-unit scope.

== file structure

* no include guards; no "headers in headers" if easily avoidable.
* all cuda kernels are in a separate header `.h` file.
* a module is implemented inside its own directory `A`
** it has its own object `A/imp.cu` or `A/imp.cpp`(`.cpp` prefered if possible)
** interface `A/imp.h`
** implementation can be done in separate files inside `A/imp/` directory
** internal cuda (private to module) code are inside `A/dev/` directory
** cuda interface inside `A/dev.h` (for client use)
* modules can have submodules, which follow the same structure as above, e.g. submodule `B` inside module `A` belongs to `A/B/` directory

== style

for emacs: the following c++ mode is used

[source,lisp]
----
include::cstyle/cc.el[]
----

