$B/algo/minmax.o: $S/algo/minmax.cu; $N -I$S/algo -I$S/.
$B/algo/scan/imp.o: $S/algo/scan/imp.cu; $N -I$S/algo/scan -I$S/.
$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/glb/gdot/imp.o: $S/glb/gdot/imp.cu; $N -I$S/glb/gdot -I$S/.
$B/glb/imp.o: $S/glb/imp.cu; $N -I$S/glb -I$S/.
$B/io/off.o: $S/io/off.cpp; $X -I$S/io -I$S/.
$B/mesh/bbox.o: $S/mesh/bbox.cu; $N -I$S/mesh -I$S/.
$B/mesh/collision.o: $S/mesh/collision.cu; $N -I$S/mesh -I$S/.
$B/mesh/dist.o: $S/mesh/dist.cpp; $X -I$S/mesh -I$S/.
$B/mesh/props.o: $S/mesh/props.cpp; $X -I$S/mesh -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/msg.o: $S/msg.cpp; $X -I$S/.
$B/u/mesh/main.o: $S/u/mesh/main.cu; $N -I$S/u/mesh -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
