/*
explicit formula for B-spline
https://en.wikipedia.org/wiki/B-spline#Definition */

load("format") $
load("cgrind") $

n: 4;

evl1(   i):= I[i, i+1];
evlk(k, i):= (x - i)     / (k - 1) * evl(k - 1, i    ) +
             (i + k - x) / (k - 1) * evl(k - 1, i + 1);
evl(k, i):= if k = 1 then evl1(i) else evlk(k, i);

e: evl(n, 0);
v: create_list(I[i - 1, i], i, 1, n);
v: funmake(%poly, v);
e: format(e, v);

foo0(i):=horner(coeff(e, i));
foo(i):=subst(x^3 = xcu, foo0(i));

grd():=for i thru n do grind([i-1, i, foo(I[i-1, i])])$
plot():=block(
  local(f, indic, i, j, r),
  indic(a, b)::= if x >= a and x < b then 1 else 0,
  matchdeclare([i, j], true),
  defrule(r, I[i, j], indic(i, j)),
  define(f(x), apply1(e, r)),
  draw2d(explicit(f(x + n/2), x, -n/2, n/2)));

plot();
grd(); /* grind */
