#!/bin/sh
set -eu

prog=u.punto.2vtk0

. u.punto.util

o="$1"; shift
i="$1"; shift

"$AWK" -v o="$o" -v i="$i" -v prog="$prog" '
BEGIN {
    ini()
    arg()
    while (1) {
	r = read()
	write()
	if (r == EOF) break
    }
}

function ini() {
    id = 0
    # end of file/snapshot
    OK = 0; EOF = 1; EOS = 2
}

function nxt(   r) {
    r = getline < i
    if (r <= 0)  return EOF
    if (NF == 0) return EOS
    return OK
}

function read(   r) {
    while (1) {
	r = nxt()
	if (r == EOF) return EOF
	if (r == EOS) return OK
    }
}
function write() {
    msg("preved")
}

function arg(   i, k) {
    for (i = 1; i in ARGV; i++) {
	k = ARGV[i]; idx[k] = i; key[i] = k
    }
}
function msg(s) { printf "%s: %s\n", prog, s | "cat >&2" }
function err(s) { msg(s); exit(2) }
' "$@"
