#!/bin/sh

set -eu

prog=u.punto.disp
prog0=u.punto.disp0

. u.punto.util

usg () {
    msg "$prog"' [PUNTO FILE]'
    msg '[disp]acement from initial position'
    exit
}

if test $# -ne 0 && test "$1" = -h; then usg; fi
if test $# -eq 0; then err 'not enough args'; fi

i="$1"; shift
for c; do shift; set -- "$@" "$i"; f="$c"; done

exec "$prog0" "$@"
