#!/bin/sh

. u.punto.util

prog=u.punto.merge

usg () {
    msg "$prog"' A.punto B.punto > out.punto'
    msg 'merge A and B'
    exit
}
if test $# -ne 0 -a "$1" = -h; then usg; fi

filep () {
    if test ! -f "$1"
    then err 'not a file '"$1"
    fi
}

if test $# -le 0; then err "need A.punto"; fi
a="$1"; shift
filep "$a"

if test $# -le 0; then err "need B.punto"; fi
b="$1"; shift
filep "$b"

"$AWK" -v a="$a" -v b="$b" '
function read(a, A,   rc) {
    split("", A)
    for (;;) {
	rc = getline < a
	if (rc <= 0) {EOF = 1; break}
	if (NF == 0) break
	A[++i] = $0
    }
}
function write(A,   i) {
    for (i = 1; i in A; i++) print A[i]
}

BEGIN {
    for (;;) {
        read(a, A); read(b, B)
        write(A); write(B)
	if (EOF == 1) break
	printf "\n"
    }
}
'
