#!/bin/sh

. u.punto.util

usg () {
    msg "$prog"' xl xh   yl yh   zl zh [PUNTO FILE]'
    msg '[r]egion [o]f [i]nterest'
    exit
}

prog=u.punto.roi
if test $# -ne 0 -a "$1" = -h; then usg; fi

case $# in
    0|1|2|3|4|5) err 'not enough arguments' ;;
esac

exec u.punto.roi0 "$@"
