#!/bin/sh

set -eu

. u.punto.util

xl="$1"; shift; xh="$1"; shift
yl="$1"; shift; yh="$1"; shift
zl="$1"; shift; zh="$1"; shift

"$AWK" -v xl=$xl -v xh=$xh \
       -v yl=$yl -v yh=$yh \
       -v zl=$zl -v zh=$zh \
'
    BEGIN { Empty = 1 }
    function roi0(r, l, h) { return l < r && r < h }
    function roi() {
        x = $1; y = $2; z = $3
        return roi0(x, xl, xh) && roi0(y, yl, yh) && roi0(z, zl, zh)
    }
    function nxt_snap() { return NF == 0    }
    nxt_snap()          { 
                          if (!Empty) {printf "\n"; Empty=1}
                          next 
                        }
    roi()               { Empty = 1; print }
' "$@"
