#!/bin/sh
set -u

prog=u.punto.unwrap
prog0=u.punto.unwrap0

. u.punto.util

usg () {
    msg "$prog"' DIR PUNTO.FILE [fields]...'
    msg 'convert PUNTO.FILE to several vtk files in DIR'
    msg '[fields].. names in vtk files'
    msg "skip field if it is '-'"
    msg "$prog"' out punto.txt    id x y z'
    msg "$prog"' out punto.txt     - x y z'
    exit
}
if test $# -ne 0 && test "$1" = -h; then usg; fi

exec "$prog0" "$@"
