#!/usr/bin/awk -f

function ini(Din,   Dr) {
    D = Din   # cell diameter
    Dr = 7.82 # reference value
    a0 = 0.0518/Dr*D; a1 = 2.0026; a2 = -4.491/Dr^2*D^2
    IN = 1; OUT = 0
    BIG = 1000; NITER = 30
}
function rbc(x, y, z,   z0, d, rr) {
    rr  = x^2 + y^2; rr /= D^2
    d = 1 - 4*rr
    if (d < 0) return OUT
    z0  = sqrt(d) * (a0 + a1*rr + a2*rr^2)
    z0 *= D
    return abs(z) < z0 ? IN : OUT
}
function read(f,   rc) {
    n = 0
    for (;;) {
	rc = getline < f
	if (rc <= 0) return "(EOF)"
	if (!NF)     break
	n++; x[n] += $1; y[n] += $2; z[n] += $3
    }
}

function mid(l, h) { return (l + h)/2 }
function f(s) { return rbc(s*x0, s*y0, s*z0) }
function gscale0(   l, h, m, fl, fh, fm, i) {
    l = 0.25; h = 3.0 # low, high, middle
    fl = f(l); fh = f(h)
    for (i = 1; i <= NITER; i++) {
	m = mid(l, h)
	fm = f(m)
	if (fm == fl) {
	    fl = fm; l = m
	} else {
	    fh = fm; h = m
	}
    }
    return m
}
function gscale(x, y, z) {
    x0 = x; y0 = y; z0 = z # global
    return gscale0()
}
function dist(x, y, z, s,   r) {
    r = rad(x, y, z)
    return r - r*s
}
function main0(x, y, z,  s, d) {
    s = gscale(x, y, z)
    d = dist(x, y, z, s)
    print s*x, s*y, s*z, s
}
function main(   i) {
    for (i = 1; i <= n; i++) main0(x[i], y[i], z[i])
}
BEGIN {
    ini(5.2)
    for (;;) {
	if (rc == "(EOF)") break
	rc = read(ARGV[1])
	main()
    }
}

function rad(x, y, z) { return sqrt(x^2 + y^2 + z^2) }
function abs(x) { return x > 0 ? x : -x }
