#!/usr/bin/env python2

from plyfile import PlyData
import sys
import numpy as np
import efit

def center(f):
    f = PlyData.read(f)
    f = f["vertex"]
    f = np.array([f[p] for p in ('x', 'y', 'z')]).T
    [center, radii, evecs, v, chi2] = efit.ellipsoid(f)
    print radii[0], radii[1], radii[2]

for f in sys.argv[1:]:
    center(f)
