#!/usr/bin/env python2

from plyfile import PlyData
import sys
import numpy as np
import efit

def center(f):
    f = PlyData.read(f)
    f = f["vertex"]
    f = np.array([f[p] for p in ('x', 'y', 'z')]).T
    [center, radii, evecs, v, chi2] = efit.ellipsoid(f)
    print radii[0], radii[1], radii[2]

def keller(f):
    na = np.array

    f = PlyData.read(f)
    f = f["vertex"]
    # x = na(f['x'])
    # y = na(f['y'])
    # vx = na(f['u'])
    # vy = na(f['v'])
    print f['u']

for f in sys.argv[1:]:
    # center(f)
    keller(f)
