#!/usr/bin/env python2

from plyfile import PlyData
import sys
import numpy as np
import efit

def write(f, xyz, uvw):
    D = np.hstack( (xyz, uvw) )
    np.savetxt(f, D)

def read(f):
    f = PlyData.read(f)
    f = f["vertex"]
    xyz = np.array([f[p] for p in ('x', 'y', 'z')]).T
    uvw = np.array([f[p] for p in ('u', 'v', 'w')]).T
    return [xyz, uvw]

def ellipsoid(xyz):
    """ return a/b and rotation matrix """
    X, Y = 0, 1
    [center, radii, evecs, v, chi2] = efit.ellipsoid(xyz)
    q = radii[X]/radii[Y]
    return center, q

def keller(xyz, uvw, q):
    X, Y = 0, 1
    x  = xyz[:, X];  y = xyz[:, Y]
    vx = uvw[:, X]; vy = uvw[:, Y]
    return efit.keller_phi(x, y, vx, vy, q)

for f in sys.argv[1:]:
    [xyz, uvw] = read(f)
    center, q = ellipsoid(xyz)
    fr, phi, res = keller(xyz, uvw, q)
    print fr, 180*phi/np.pi, res
