# Generated with by ../tools/deps.awk *.cu *.h
# (do not include '*.h' files in other '*.h' files)

common.o: .conf.h common.h
dpd-forces.o: .conf.h common.h dpd-forces.h
dpd.o: .conf.h common.h dpd-forces.h dpd.h last_bit_float.h solvent-exchange.h
io.o: .conf.h common.h io.h last_bit_float.h
last_bit_float.o: last_bit_float.h
main.o: .conf.h argument-parser.h common.h dpd.h simulation.h solvent-exchange.h
minmax.o: .conf.h common.h minmax.h
simulation.o: .conf.h common-kernels.h common.h contact.decl.h contact.impl.h containers.decl.h containers.impl.h dpd-forces.h dpd.h fsi.decl.h fsi.impl.h io.h kernelscontact.decl.h kernelscontact.impl.h kernelsfsi.decl.h kernelsfsi.impl.h last_bit_float.h minmax.h redisparticleskernels.decl.h redisparticleskernels.impl.h redistribute-particles.decl.h redistribute-particles.impl.h redistribute-rbcs.decl.h redistribute-rbcs.impl.h scan.h simulation.decl.h simulation.h simulation.impl.h solute-exchange.decl.h solute-exchange.impl.h solutepup.decl.h solutepup.impl.h solvent-exchange.h wall.decl.h wall.impl.h
solvent-exchange.o: .conf.h common.h solvent-exchange.h
