# Generated with by ../tools/deps.awk *.cu *.h
# (do not include '*.h' files in other '*.h' files)

common.o: .conf.h common.h
dpd-forces.o: .conf.h common.h dpd-forces.h
io.o: .conf.h common.h io.h last_bit_float.h
last_bit_float.o: last_bit_float.h
main.o: .conf.h argument-parser.h common.h simulation.h
minmax.o: .conf.h common.h minmax.h
simulation.o: .conf.h bipsbatch.decl.h bipsbatch.impl.h common-kernels.h common.h common.tmp.h contact.decl.h contact.impl.h containers.decl.h containers.impl.h dpd-forces.h dpd.decl.h dpd.impl.h fsi.decl.h fsi.impl.h io.h k/cnt.h k/fsi.h k/rex.h k/sdist.h k/wall.h last_bit_float.h minmax.h packinghalo.decl.h packinghalo.impl.h redistribute-particles.decl.h redistribute-particles.impl.h redistribute-rbcs.decl.h redistribute-rbcs.impl.h scan.h simulation.decl.h simulation.h simulation.impl.h simulation.krn.h solute-exchange.decl.h solute-exchange.impl.h wall.decl.h wall.impl.h
