$B/algo/minmax.o: $S/algo/minmax.cu; $N -I$S/algo -I$S/.
$B/algo/scan/imp.o: $S/algo/scan/imp.cu; $N -I$S/algo/scan -I$S/.
$B/clist/imp.o: $S/clist/imp.cu; $N -I$S/clist -I$S/.
$B/cnt/imp.o: $S/cnt/imp.cu; $N -I$S/cnt -I$S/.
$B/color/flux.o: $S/color/flux.cu; $N -I$S/color -I$S/.
$B/comm/imp.o: $S/comm/imp.cu; $N -I$S/comm -I$S/.
$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/dbg/imp.o: $S/dbg/imp.cu; $N -I$S/dbg -I$S/.
$B/distr/flu/imp.o: $S/distr/flu/imp.cu; $N -I$S/distr/flu -I$S/.
$B/distr/rbc/imp.o: $S/distr/rbc/imp.cu; $N -I$S/distr/rbc -I$S/.
$B/distr/rig/imp.o: $S/distr/rig/imp.cu; $N -I$S/distr/rig -I$S/.
$B/dpdr/imp.o: $S/dpdr/imp.cu; $N -I$S/dpdr -I$S/.
$B/dpdr/int.o: $S/dpdr/int.cpp; $X -I$S/dpdr -I$S/.
$B/exch/flu/imp.o: $S/exch/flu/imp.cu; $N -I$S/exch/flu -I$S/.
$B/exch/mesh/imp.o: $S/exch/mesh/imp.cu; $N -I$S/exch/mesh -I$S/.
$B/exch/obj/imp.o: $S/exch/obj/imp.cu; $N -I$S/exch/obj -I$S/.
$B/field.o: $S/field.cpp; $X -I$S/.
$B/flu/imp.o: $S/flu/imp.cu; $N -I$S/flu -I$S/.
$B/frag/imp.o: $S/frag/imp.cpp; $X -I$S/frag -I$S/.
$B/fsi/imp.o: $S/fsi/imp.cu; $N -I$S/fsi -I$S/.
$B/generate/rig/imp.o: $S/generate/rig/imp.cu; $N -I$S/generate/rig -I$S/.
$B/glb/imp.o: $S/glb/imp.cu; $N -I$S/glb -I$S/.
$B/glb/wvel/imp.o: $S/glb/wvel/imp.cu; $N -I$S/glb/wvel -I$S/.
$B/hforces/imp.o: $S/hforces/imp.cu; $N -I$S/hforces -I$S/.
$B/inter/imp.o: $S/inter/imp.cu; $N -I$S/inter -I$S/inter/_ussr -I$S/.
$B/io/bop/imp.o: $S/io/bop/imp.cpp; $X -I$S/io/bop -I$S/.
$B/io/com.o: $S/io/com.cpp; $X -I$S/io -I$S/.
$B/io/diag.o: $S/io/diag.cpp; $X -I$S/io -I$S/.
$B/io/field/h5/imp.o: $S/io/field/h5/imp.cpp; $X -I$S/io/field/h5 -I$S/.
$B/io/field/imp.o: $S/io/field/imp.cpp; $X -I$S/io/field -I$S/.
$B/io/fields_grid.o: $S/io/fields_grid.cpp; $X -I$S/io -I$S/.
$B/io/field/xmf/imp.o: $S/io/field/xmf/imp.cpp; $X -I$S/io/field/xmf -I$S/.
$B/io/mesh.o: $S/io/mesh.cpp; $X -I$S/io -I$S/.
$B/io/off.o: $S/io/off.cpp; $X -I$S/io -I$S/.
$B/io/ply.o: $S/io/ply.cpp; $X -I$S/io -I$S/.
$B/io/restart.o: $S/io/restart.cpp; $X -I$S/io -I$S/.
$B/io/rig.o: $S/io/rig.cpp; $X -I$S/io -I$S/.
$B/lforces/imp.o: $S/lforces/imp.cu; $N -I$S/lforces -I$S/.
$B/lforces/transpose/imp.o: $S/lforces/transpose/imp.cu; $N -I$S/lforces/transpose -I$S/.
$B/main.o: $S/main.cpp; $X -I$S/.
$B/math/linal.o: $S/math/linal.cpp; $X -I$S/math -I$S/.
$B/meshbb/imp.o: $S/meshbb/imp.cu; $N -I$S/meshbb -I$S/.
$B/mesh/bbox.o: $S/mesh/bbox.cu; $N -I$S/mesh -I$S/.
$B/mesh/collision.o: $S/mesh/collision.cu; $N -I$S/mesh -I$S/.
$B/mesh/dist.o: $S/mesh/dist.cpp; $X -I$S/mesh -I$S/.
$B/mesh/props.o: $S/mesh/props.cpp; $X -I$S/mesh -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/msg.o: $S/msg.cpp; $X -I$S/.
$B/rbc/com/imp.o: $S/rbc/com/imp.cu; $N -I$S/rbc/com -I$S/.
$B/rbc/force/imp.o: $S/rbc/force/imp.cu; $N -I$S/rbc/force -I$S/.
$B/rbc/main/imp.o: $S/rbc/main/imp.cpp; $X -I$S/rbc/main -I$S/.
$B/restrain/imp.o: $S/restrain/imp.cu; $N -I$S/restrain -I$S/.
$B/restrain/stat/imp.o: $S/restrain/stat/imp.cpp; $X -I$S/restrain/stat -I$S/.
$B/restrain/sum/imp.o: $S/restrain/sum/imp.cpp; $X -I$S/restrain/sum -I$S/.
$B/rigid/imp.o: $S/rigid/imp.cu; $N -I$S/rigid -I$S/.
$B/rig/imp.o: $S/rig/imp.cu; $N -I$S/rig -I$S/.
$B/rnd/imp.o: $S/rnd/imp.cpp; $X -I$S/rnd -I$S/.
$B/scheme/imp.o: $S/scheme/imp.cu; $N -I$S/scheme -I$S/.
$B/sdf/imp.o: $S/sdf/imp.cu; $N -I$S/sdf -I$S/.
$B/sdf/int.o: $S/sdf/int.cu; $N -I$S/sdf -I$S/.
$B/sim/imp.o: $S/sim/imp.cu; $N -I$S/sim -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
$B/vcontroller/imp.o: $S/vcontroller/imp.cu; $N -I$S/vcontroller -I$S/.
$B/wall/exch/imp.o: $S/wall/exch/imp.cpp; $X -I$S/wall/exch -I$S/.
$B/wall/force/imp.o: $S/wall/force/imp.cu; $N -I$S/wall/force -I$S/.
$B/wall/imp.o: $S/wall/imp.cu; $N -I$S/wall -I$S/.
