= introduction
:lext: .adoc

== what is _uDeviceX_?

It is a dissipate particle dynamic particle (DPD) simulation code
which can model multiphase flows, rigid and soft objects, boundary
conditions can be periodic or "wall". Wall boundary can be set from a
user provided file.

_uDeviceX_ was ACM 2015 Gordon Bell Award Finalist.

It is written in C++ using
link:https://en.wikipedia.org/wiki/CUDA[CUDA]
and
link:https://en.wikipedia.org/wiki/Message_Passing_Interface[MPI]
and requires NVIDIA GPUs. Simulation are set from a configuration file
and from command line options. Here is an example

----
udx conf.cfg 'time = { dt = 0.1 }'
----

Configuration files and command line options follow the syntax of
link:https://hyperrealm.github.io/libconfig[libconfig library]. Some
parameters have default values and are set in
`$HOME/.udx/defult.cfg`. _uDeviceX_ outputs DPD particles,
trajectories of the objects, and averaged flow fields.

== code

Code is organized in _units_ which are executables.  _uDeviceX_
installs several command line tools which have prefix `u.`, for
example `u.run`.

== tests

_uDeviceX_ comes with tests. Each test is a shell script with some
conventions. To run a test

----
atest example.test
----

Typically test compiles and run one of the units and produce a text
file. `atest` compares the text file with a previously stored
reference and report the result. Comparision can be exact or "fuzzy".

== systems of coordinates

There are several systems of coordinates in _uDeviceX_. Let focus on
`X` direction, `Y` and `Z` are similar. A _global_ system is used as a
reference and in _global_ system left edge of the simulation domain is
0 and right edge is `xdomain()`. Each subdomain which belong to one
MPI process has its own _local_ system of coordinates. Most of the
calculations are done in _local_ system, for example arrays of
`Particles` are using _local_ system. Left and right edges of the
subdomains are `xlo()` and `xhi()` and subdomains size is `xs()`. The
following holds:

----
xs() == xhi() - xlo()
xdomain() == xs() * nx
----
where `nx` is a number of subdomains in `X` direction.
