#!/usr/bin/python3

import udxconf
import sys

c = udxconf.load(sys.stdin)

# change
c.time.wall = 0.2
c.dbg.clean = False

# create a namespace
g = udxconf.namespace()
g.q = 56
g.p = 56
c.g = g

print(udxconf.dumps(c))
