#!/bin/sh

set -eu

EXCLUDE="all.adoc summary.adoc dev/main.adoc user/main.adoc units/main.adoc"
CONTR='Alexeev, D.; Amoudruz, L.; Bernaschi, M.; Bisson, M.; Conti, C.; Economides, A.; Fatica, M.; Hadjidoukas, P.; Joubert, W.; Karniadakis G.; Koumoutsakos, P.; Kulakova, L.; Litvinov, S.; Lykov, K.; Pivkin, I.; Rossinelli, D.; Tang, Y.-H.'

usg() {
    echo 1>&2 'usg: u.doc.all <doc dir> > index.adoc'
    echo 1>&2 'combine all adoc files into one'
    exit 1
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

d="$1"

find0 () { # like find(1) but exclude files
    find "$@" | "${AWK-awk}" -v e="$EXCLUDE" '
    BEGIN { ini() }
    { gsub(/^\.\//, "")
      if (!($0 in a)) print
    }
    function ini(  t, i, n) { 
      n = split(e, t)
      for (i = 1; i <= n; i++) a[t[i]]
    }      
    function msg(s) { print s | "cat >&2" }
    '
}
get_docs() (
    find0 $1 -type f -name '*.adoc'
)

header() (
    echo ':lext: .adoc'
    echo ':toclevels: 4'
    echo '= uDeviceX Documentation'
    echo $CONTR
    echo
    echo 'image::include/pach.png[]'
    echo
)

make_links() (
    for f
    do echo "include::$f[]"
    done
)

section() {
    local dir name
    dir="$1"; shift
    name="$1"; shift
    ADOC="`get_docs $dir`"
    echo "== $name"
    echo ':leveloffset:  2'
    for l in `make_links $ADOC | sort`
    do echo $l
       echo
    done
    echo ':leveloffset:  0'
}

dump() {
    header
    section $d/dev   Developer
    section $d/user  User
    section $d/units Units
}

dump
