#!/bin/sh
G="git@github.com:amlucas/udoc.git"

ROOT="/udoc"
DOC=doc_

make clean && make -j ROOT=${ROOT}

T="./public"
rm -rf $T
# html, css, include, directories
H=`find . -type f -name "*.html"`
C=`find . -type f -name "*.css"`
I=`find include -type f`
D=`find . -type d`

# create tmp doc direcory
for d in $D; do
     mkdir -p "${T}/${d}"
done

for h in $H $C $I; do
    cp -f $h "${T}/${h}"
done

# copy to remote git repo

git clone $G ${DOC}

rm -rf ${DOC}/*
mv $T/* ${DOC}

# push to remote
COMMITID=`git rev-parse HEAD`
mydir=`pwd`
cd ${DOC}
# upd readme
echo "https://amlucas.github.io/udoc/" > README.adoc
git add *
git commit -a -m "automatic deploy from commit ${COMMITID}"
git push origin master

# cleanup
cd ${mydir}
rm -rf $T ${DOC}
