#!/bin/sh

set -eu

usg() {
    echo "usg: u.doc.deps [FILE.adoc].. > deps.mk"
    exit 0
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

make_path() {
    dir="$1"; shift
    for f
    do echo "${dir}/$f"
    done
}

filter_deps() {
    for i
    do if echo "$i" | grep "adoc"
       then echo "$i"
       fi
    done
}

deps() {
    for f
    do target="${f%.adoc}.html"
       DEPS=`u.doc.inc "$f" | sort | xargs`
       if test $? -ne 0; then echo >&2 'u.doc.inc faild'; exit 2; fi
       echo "$target: $f $DEPS"
    done
}

deps "$@"
