#!/bin/sh

set -eu

. u.doc.util

usg() {
    msg 'usg: u.doc.deps [FILE.adoc].. > deps.mk'
    exit 0
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

for f
do target="${f%.adoc}.html"
   DEPS=`u.doc.inc "$f" | sort | xargs`
   if test $? -ne 0; then echo >&2 'u.doc.inc failed'; exit 2; fi
   echo "$target: $f $DEPS"
done
