#!/bin/sh

set -eu

usg() {
    echo "usg: u.doc.deps [FILE.adoc].. > deps.mk"
    exit 0
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

make_path() {
    dir="$1"; shift
    for f
    do echo "${dir}/$f"
    done
}

filter_deps() {
    for i
    do if echo "$i" | grep "adoc"
       then echo "$i"
       fi
    done
}

deps() {
    for f
    do target="${f%.adoc}.html"
       DIR=`dirname $f`
       DEPS=`grep "$f" -e "include::" | cut -d':' -f 3 | cut -d'[' -f 1`
       DEPS=`filter_deps $DEPS`
       DEPS=`make_path $DIR $DEPS | sort | xargs`
       echo "$target: $f $DEPS"
    done
}

deps "$@"
