#!/bin/sh

I=index.adoc

get_docs() (
    find $1 -type f \( -iname "*.adoc" ! -iname "*.inc.adoc" \)
)

header() (
    echo "= index"
    echo ":lext: .adoc"
    echo
)

make_links() (
    for f in $@; do
	echo "* link:${f%.*}{lext}[]"
    done
)

section() {
    ADOC=`get_docs $1`
    echo "== $1"
    make_links $ADOC
    echo
}

dump() {
    header
    section dev
    section user
    section units
}

dump > $I
