#!/bin/sh

usg() {
    echo "usg: u.doc.index <doc dir> > index.adoc"
    exit 1
}

if test $# -ne 0 -a "$1" = -h; then usg; fi

d=$1

get_docs() (
    find $1 -type f \( -iname "*.adoc" ! -iname "*.inc.adoc" \)
)

header() (
    echo "= index"
    echo ":lext: .adoc"
    echo
)

make_links() (
    for f in $@; do
	echo "* link:${f%.*}{lext}[]"
    done
)

section() {
    ADOC=`get_docs $1`
    echo "== $1"
    make_links $ADOC | sort
    echo
}

dump() {
    header
    section $d/dev
    section $d/user
    section $d/units
}

dump
