#!/bin/sh

# exlucde
MAIN=main.adoc

usg() {
    echo 1>&2 'usg: u.doc.main <doc dir> > index.adoc'
    echo 1>&2 'combine all adoc files into one'
    exit 1
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

d="$1"

get_docs() (
    find $1 -type f -name '*.adoc' ! -name '*.inc.adoc' ! -name $MAIN
)

header() (
    echo ':lext: .adoc'
    echo ':leveloffset:  1'
    echo '= index'
    echo
)

make_links() (
    for f
    do echo "include::$f[]"
    done
)

section() {
    ADOC="`get_docs $1`"
    echo "== $1"
    make_links $ADOC | sort
    echo
}

dump() {
    header
    section $d/dev
    section $d/user
    section $d/units
}

dump
