#!/bin/sh

usg() {
    echo 1>&2 'usg: u.doc.main <doc dir> > index.adoc'
    echo 1>&2 'combine all adoc files into one'
    exit 1
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

d="$1"

get_docs() (
    find $1 -type f -name '*.adoc' ! -name '*.inc.adoc'
)

header() (
    echo "= index"
    echo ":lext: .adoc"
    echo
)

make_links() (
    for f in $@; do
	echo "* link:${f%.*}{lext}[]"
    done
)

section() {
    ADOC="`get_docs $1`"
    echo "== $1"
    make_links $ADOC | sort
    echo
}

dump() {
    header
    section $d/dev
    section $d/user
    section $d/units
}

dump
