#!/bin/sh

usg() {
    echo "usg: u.doc.targets <doc dir> > targets.mk"
    exit 1
}

if test $# -ne 0 -a "$1" = -h; then usg; fi

d=$1


ADOC=`find $d -type f \( -iname "*.adoc" ! -iname "*.inc.adoc" \)`

ext_html() (
    for f in $@; do
	echo "${f%.*}.html"
    done
)

PAGES=`ext_html $ADOC | xargs`

echo "PAGES = $PAGES"
