#!/bin/sh

usg() {
    echo "usg: u.doc.targets <doc dir> <f1.adoc f2.adoc...> > targets.mk"
    exit 1
}

if test $# -ne 0 -a "$1" = -h; then usg; fi

d=$1
shift

ext_html() (
    for f in $@; do
	echo "${f%.*}.html"
    done
)

PAGES=`ext_html $@ | sort | xargs`

echo "PAGES = $PAGES"
