#!/bin/sh

usg() {
    echo 'usg: u.doc.targets [f1.adoc].. > targets.mk'
    exit 1
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

ext_html() (
    for f in $@; do
	echo "${f%.*}.html"
    done
)

PAGES=`ext_html $@ | sort | xargs`

echo "PAGES = $PAGES"
