#!/bin/sh

set -eu

msg () { echo >&2 "$@"; }
e ()   { msg ": $@"; eval "$@"; }

h=`u.host`
if test $h = acer
then e xdg-open localhost:8000/"${1-index.html}"
else e open -a Firefox http://localhost:8000/"${1-index.html}"
fi
