#!/bin/sh

set -eu

usg() {
    echo 'usage: u.conf [source dir] [unit dir] default.h <<<!
[variables]
[commands]
...
!
Creates Makefile, runfile, bin[.N] directories; populates bin[.N] with
`components of makefiles and conf.h' >&2
    exit
}

### error codes
ERR_NO_RUNS=3
ERR_BIN_MAKE=4
ERR_MISSING_MK=5
ERR_ARGP=6

msg() { printf '%s\n' "$*" >&2; }
err() { msg "$@"; usg; }

if test $# -ne 0 && test "$1" = -h; then usg; fi

S=.
if test $# -ne 0 -a -d "$1"; then S="$1"; shift; fi

U=u/x  # default unit
if test $# -ne 0 -a -d "$S/$1"; then U="$1"; shift; fi

c=/dev/stdin  # config file
if test $# -ne 0; then c="$1"; shift; fi

t=/tmp/u.conf.$$.conf
trap 'rm -rf $t' 0 1 2 3 15
cat "$c" > "$t"
c=$t

### S: source directory; h: header file; c: config file #####
u.conf.make "$S" "$U" "$c"; rc=$?
if test $rc -eq $ERR_NO_RUNS;    then err 'no run commands in config'; fi
if test $rc -eq $ERR_BIN_MAKE;   then err 'cannot create bin[...]/Makefile'; fi
if test $rc -eq $ERR_MISSING_MK; then err 'cannot find system config'; fi

u.conf.conf     "$c"; rc=$?
if test $rc -eq $ERR_ARGP;       then err 'u.argp fails'; fi

u.conf.run     "$c"; rc=$?
