#!/bin/sh

set -eu

. u.conf.util

usg() {
    echo 'usage: u.conf SRC.DIR UNIT.DIR <<<!
[variables]
...
!
Creates Makefile, conf.h, conf.mk and sys.mk files' >&2
    exit
}

prog=u.conf

### error codes
ERR_NO_RUNS=3
ERR_BIN_MAKE=4
ERR_MISSING_MK=5
ERR_ARGP=6

if test $# -ne 0 && test "$1" = -h; then usg; fi
if test $# -eq 0; then err 'missing SRC.DIR'; fi
S="$1"; shift

if test $# -eq 0; then err 'missing UNIT.DIR'; fi
U="$1"; shift

### S: source directory; h: header file; c: config file #####
e u.conf.make "$S" "$U"; rc=$?
if test $rc -eq $ERR_NO_RUNS;    then err 'no run commands in config'; fi
if test $rc -eq $ERR_BIN_MAKE;   then err 'cannot create bin[...]/Makefile'; fi
if test $rc -eq $ERR_MISSING_MK; then err 'cannot find system config'; fi

trap 'rm $t; exit 2' 1 2 3 4 15; touch $t
"$AWK" '{ printf "%s \n", $0 }' > $t
u.argp `cat $t` '>' conf.h
if test $? -ne 0; then err 'u.argp failed'; fi

rm $t
