#!/bin/bash

S="$1"; shift # source
U="$1"; shift # unit
B="$1"; shift  # bin

ERR_BIN_MAKE=4
ERR_MISSING_MK=5

msg() { printf '%s\n' "$*" >&2; }

write_make() {
    echo "\
S = $S
U = $U
B = $B"'
include $B/sys.mk
include $S/make/common.mk
include $S/$U/make/obj.mk

include $S/make/main.mk

include $S/$U/make/rule.mk
include $S/$U/make/dir.mk
include $S/$U/make/dep.mk' > "$m"
}

write_sys () (
    dn=amlucas dh=panda
    n=`whoami` h=`u.host`

    c0="$S/make/sys/$n.$h"
    if test ! -f "$c0"; then c0="$S/make/sys/$dn.$h";  fi
    if test ! -f "$c0"; then c0="$S/make/sys/$dn.$dh"; fi
    if test ! -f "$c0"; then exit 1             ; fi
    cp "$c0"  "$c"
)

mkdir -p     "$B"

m="$B/Makefile"
c="$B/sys.mk"

write_make; rc=$?
if test $rc -ne 0; then exit $ERR_BIN_MAKE; fi

write_sys; rc=$?
if test $rc -ne 0; then exit $ERR_MISSING_MK; fi


