#!/usr/bin/awk -f

BEGIN {
    ERR_NO_RUNS = 3

    S = ARGV[1]; shift()
    U = ARGV[1]; shift()
    c = ARGV[1]; shift()
    nbin = 0 # bin dirs
    parse()
    bins()
    if (nbin > 1) make("Makefile")
}

function bins() {
    if      (nbin == 0) exit ERR_NO_RUNS
    else if (nbin == 1) make(".")
}

function make(b,  sp) {
    sp = " "
    cmd("u.conf.make0" sp qq(S) sp qq(U) sp b)
}

function cmd(s,  rc) {
    rc = system(s)
    if (rc != 0) exit rc
}

function parse() {
    while (getline < c > 0) {
	comm() # stip comments
	if (emptyp()) continue
	if (runp())   nbin += 1
    }
    close(c)
}

function runp() { return $1 == "run" } # run predicate
function comm() { sub(/#.*/, "") }     # stip comments
function emptyp() { return $0 ~ /^[ \t]*$/ }
function qq(s)    { return "'"  s  "'" } # quotes a string

function msg(s) { printf "%s\n", s | "cat >&2" }
function shift(  i) { for (i = 2; i < ARGC; i++) ARGV[i-1] = ARGV[i]; ARGC-- }
