#!/bin/sh

prog_name=u.run

usg () {
    msg 'usage: u.run NX NY NZ ./udx [ARGS]'
    msg '       u.run          ./udx [ARGS]'
    msg 'how commands runs is modified by the variables:'
    msg '  MEM: cuda-memcheck'
    msg '  VAL: valgrind'
    msg '  PROF: nvprof'
    msg '  TIME: time'
    exit
}

msg () { printf >&2 '%s\n' "$@" ; }
err () { msg "$prog_name: $@"; exit 2; }

if test $# -ne 0 && test "$1" = -h; then usg; fi

# integer?
intp() { echo "$1" | grep -q '^[0-9]*$'; }
mult () { "${AWK-awk}" -v x=$x -v y=$y -v z=$z 'BEGIN {print x*y*z}'; }

x=1 y=1 z=1
if test $# -ne 0 && intp "$1"; then x=$1; shift; fi
if test $# -ne 0 && intp "$1"; then y=$1; shift; fi
if test $# -ne 0 && intp "$1"; then z=$1; shift; fi
if test $# -eq 0; then usg; fi
n=`mult`

h=`u.host`
u.run."$h" $n $x $y $z "$@"

s=$?
if test $? -ne 0; then msg "u.run.$h failed"; fi
exit $s
