= map

Helper for packing data to send buffers. This is common to all
quantities.
As opposed to the _distr_ module, the mapping is not _one to one_.
A single quantity can be exchanged with up to 7 neighboring nodes if
it is in a corner (exchange with 3 faces, 3 edges and one corner).

== data structure

A single structure is able to build a map for up to `nw` objects
(e.g. rbc and rigid give `nw = 2`)

[source,cpp]
----
include::{src}/exch/map/type.h[tag=struct]
----

for `nw` objects and `nfrags` fragments, the `counts`, `starts` and
`offsets` arrays all have the same size `n = (nw + 1) * (nfrags + 1)`
for convenience.

The `nfrags + 1` part is for the starts, which is exclusive scan of
counts in the fragment dimension. Therefore the last element is the sum of counts, i.e. number
of entities for a given object.

The `nw + 1` part is for offsets, which are an exclusive prefix sum of
counts in the object id dimension: the last row is the number of
entities of all objects leaving per fragment.

*example:* Given `nw = 2` objects, with `nfrags = 5` fragments, with the following
 counts:
----
object 0: 0 2 2 1 4
object 1: 1 1 0 0 3
-> counts = 0 2 2 1 4 _  1 1 0 0 3 _  _ _ _ _ _ _
-> starts = 0 0 2 4 5 9  0 1 1 1 1 4  _ _ _ _ _ _
----
where `_` stands for "not set".

The offset array is then given by (we rewrite counts row by row for better understanding):
----
counts  = 0 2 2 1 4 _
          1 1 0 0 3 _
          _ _ _ _ _ _

offsets = 0 0 0 0 0 _
          0 2 2 1 4 _
	  1 3 2 1 7 _
----

`starts` and `offsets` are results of the scan operation (see below).

The index `j` used to retrieve the ith entity of a given object in a
given fragment is then given by

----
j = offsets[oid][fid] + starts[oid][fid] + i
----
where `oid` is the object id, `fid` the fragment.
note that above, `[oid][fid]` is implemented as `[oid * (nfrags + 1) + fid]`.

The id is then `ids[fid][j]`.

== interface

=== Host interface:

[source,cpp]
----
include::{src}/exch/map/imp.h[tag=int]
----
<1> allocate the map structure on device
<2> deallocate the map structure
<3> reset the map structure
<4> scan the map structure to get starts and offsets
<5> copy counts (total number of entities per fragment) from device to host

=== Device interface:

[source,cpp]
----
include::{src}/exch/map/dev.h[tag=int]
----
<1> get code (local fragment id) from position
<2> get code (local fragment id) from box positions
<3> add an entity to the map. Does not add if the capacity is exceeded
<4> get destination fragments from code

