#!/bin/bash

# udx commands

msg () { printf >&2 '%s\n' "$@"; }
if test $# != 0
then msg 'returns udx hostname'
     msg '   if UHOST is set it is returned'
     exit
fi

if test -n "$UHOST"
then printf '%s\n' "$UHOST"
     exit
fi

msg `hostname`

dh=panda # default host
h=`hostname`
case "$h" in
    daint*|nid*) h=daint    ;;
    asp|acer)    h=acer     ;;
    lo-login*)   h=leonhard ;;
    *)           h=$dh
esac

printf '%s\n' "$h"
