#!/bin/bash

# udx commands

msg () { printf '%s\n' "$@" | cat 1>&2; }
if test $# != 0
then msg 'returns udx hostname'
     msg '   if UHOST is set it is returned'
     exit
fi

if test -n "$UHOST"
then printf '%s\n' "$UHOST"
     exit
fi

dh=panda # default host
h=`hostname`
case "$h" in
    daint*) h=daint       ;;
    acer)                 ;;
    lo-login*) h=leonhard ;;
    *)      h=$dh
esac

printf '%s\n' "$h"
