#!/bin/sh

msg () { echo >&2 "$@"; }
usg() {
    msg 'usage: u.strtdir [basedir]'
    msg 'create directory tree where udx dumps restart files'
    msg '  basedir: base directory the structure (default ".")'
    exit
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

# default basedir
B=. 
if test $# -ne 0; then B=${1%/}; shift; fi

for code in flu.pp flu.ii flu.cc wall.pp rig.pp rig.ss rbc.pp rbc.ii; do
    mkdir -p "$B/$code"
done
