#!/bin/sh

prog=u.geomview0
. u.conf.util

: ${AWK=awk}

err0 () {
    echo "(exit)"
    err "$@"
}

oogl="$1"; shift

Output=0 image=
if test $# -eq 0
then Output=0
else Output=1 image="$1"; shift
fi

"$AWK" -v prog=$prog -v oogl="$oogl" -v Output=$Output -v image="$image" -v DBG="$DBG" '
function keys(s,   a, n) {
    n = sub(/^\(/, "", s)
    if (n != 1) return ERR
    n = sub(/\)$/, "", s)
    if (n != 1) return ERR
    n = split(s, a)
    if (a[1] == "rawevent")
       key(a[2])
    return OK
}

function key(k) {
    if      (k == KEY_Q) g("exit")
    else if (k == KEY_P) g("ui-panel geomview on")
    else if (k == KEY_S) {
	msg("write snap.ppm")
	g("snapshot Camera snap.ppm")
    }
    else err("unknown key: " k)
}

function ini() {
    KEY_Q = 113; KEY_S = 115; KEY_P = 112
    OK = 0; EOF = 1; ERR = -1
}

function reg_key(k) { g(sprintf("interest (rawevent %s)", k)) }
function geom() {
    g(sprintf("geometry obj < %s", oogl))
    g("bbox-draw obj no")
    reg_key(KEY_Q); reg_key(KEY_S); reg_key(KEY_P)
}

function g(s) {
    if ("" DBG != "0") msg("gcl: " s)
    printf "(%s)\n", s | "cat"
    close("cat")
}

function g0(s) {
    msg(s)
    printf "%s\n", s | "cat"
    close("cat")    
}

BEGIN {
    ini()
    geom()
    if (Output) {
       g(sprintf("snapshot Camera %s", image))
       g("exit")
    }
    for (;;) {
	status = getline s
	if (status == ERR) break
	if (keys(s) != OK) {
	    msg("fail to parse: " s)
	    break
	}
    }
}
function msg(s) { printf "%s: %s\n", prog, s | "cat >&2" }
function err(s) { msg(s); g("exit") }
' "$@"
