#!/bin/sh

prog=u.geomview
prog0=u.geomview0
. u.conf.util

: ${AWK=awk}
: ${GEOMVIEW=geomview}
: ${WX=800}
: ${WY=600}

usg () {
    msg "$prog0 [-o image.ppm] FILE.off [IC.file]"
    msg 'geomview wrapper to see udx initial conditions'
    msg 'if -o is given saves image and exits'
    msg 'Keys:'
    msg '    q: quit'
    msg '    s: save snapshot'
    msg '    p: panel'
    msg '   WX: resolution in x direction'
    msg '   WY: resolution in y direction'
    exit
}

offp() {
    "$AWK" '{ if ("" $0 != "OFF") exit 1; else exit 0 }' "$1"
}

gview () {
    if test $Output -eq 0
    then e "${GEOMVIEW}" -wpos $WX,$WY -noinit -nopanels -b 1 1 1  -run "$prog0" "$t"
    else e "${GEOMVIEW}" -wpos $WX,$WY -noinit -nopanels -b 1 1 1  -run "$prog0" "$t" "$image" --
    fi
}

main_off () {
    cat >$t <<!
{ appearance {
      +edge
      material { ks 0.0 }
  }
  < "$off"
}
!
    gview
}

main_ic () {
    ic="$1"; shift
    if ! test -f "$ic"
    then err "not a file '$ic'"
    fi
    
    i=/tmp/geomview.ic.$$
    trap 'e rm $i; exit 2' 1 2 3 4 15
    e u.geomview.transpose $ic '>' $i
    if test $? -ne 0
    then err "not an initial conditions file '$ic'"
    fi
cat >$t <<!
{ appearance {
      +edge
      material { ks 0.0 }
  }
  { INST
    geom       { < "$off" }
    transforms { < "$i"  }
  }
}
!
    gview
    e rm $i
}

if test $# -ne 0 && test "$1" = -h
then usg
fi

if ! e "$GEOMVIEW" --version '2>/dev/null' '1>/dev/null'
then err "$GEOMVIEW is not found"
fi

Output=0
for i
do if test "$i" = -o
   then shift
	if test $# -eq 0; then err '-o requres a file name'; fi
	Output=1 image="$1"; shift
   else shift
	set -- "$@" "$i"
   fi
done

if test $# -eq 0; then err 'needs OFF'; fi

off="$1"; shift
if ! test -f "$off"
then err "not a file '$off'"
fi

if ! offp "$off"
then err "not an off file '$off'"
fi

t=/tmp/geomview.$$
trap 'e rm $t; exit 2' 1 2 3 4 15

if test $# -eq 0
then main_off
else main_ic "$@"
fi

rm -f $t
