#!/bin/sh

prog=u.geomview
prog0=u.geomview0
. u.conf.util

: ${AWK=awk}
: ${GEOMVIEW=geomview}

offp() {
    "$AWK" '{ if ("" $0 != "OFF") exit 1; else exit 0 }' "$1"
}

gview () {
    e "${GEOMVIEW}" -wpos 800,600 -noinit -nopanels -b 1 1 1  -run "$prog0" "$t"
}

main_off () {
    cat >$t <<!
{ appearance {
      +edge
      material { ks 0.0 }
  }
  < "$off"
}
!
    gview
}

main_ic () {
    ic="$1"; shift
    if ! test -f "$ic"
    then err "not a file '$ic'"
    fi
    
    i=/tmp/geomview.ic.$$
    trap 'rm $i; exit 2' 1 2 3 4 15
    e ./trans $ic '>' $i
    if test $? -ne 0
    then err "not an initial conditions file '$ic'"
    fi
cat >$t <<!
{ appearance {
      +edge
      material { ks 0.0 }
  }
  { INST
    geom       { < "$off" }
    transforms { < "$i"  }
  }
}
!
    gview
    rm $i
}

if test $# -eq 0
then err 'needs OFF'
fi

if ! e "$GEOMVIEW" --version '2>/dev/null' '1>/dev/null'
then err "$GOEMVIEW is not found"
fi

off="$1"; shift
if ! test -f "$off"
then err "not a file '$off'"
fi

if ! offp "$off"
then err "not an off file '$off'"
fi

t=/tmp/geomview.$$
trap 'rm $t; exit 2' 1 2 3 4 15

if test $# -eq 0
then main_off
else main_ic "$@"
fi

rm -f $t
