#!/bin/sh

prog=u.geomview.transpose
. u.conf.util

: ${AWK=awk}

"$AWK" -v prog=$prog '
BEGIN { n = 4; i = j = 0 }
{ for (m = 1; m <= NF; m++) {
	e = $m
	if (!numberp(e))
	    err(sprintf("not numbers \"%s\" (%s)", $0, FILENAME))
	a[i, j++] = e
	if (j == n) {j = 0; i++ }
	if (i == n) {dump(); i = j = 0 }
    }
}
function dump(   i, j) {
    for (i = 0; i < n; i++)
	for (j = 0; j < n; j++)
	    printf "%s ", a[j, i]
    printf "\n"
}

function numberp(e) { return e == e + 0.0 }
function err(s)     {
    printf "%s: %s\n", prog, s | "cat >&2"
    exit 2
}
' "$@"
