$B/coords/imp.o: $S/coords/imp.cpp; $X -I$S/. -I$S/coords
$B/d/api.o: $S/d/api.cu; $N -I$S/. -I$S/d
$B/io/field/h5/imp.o: $S/io/field/h5/imp.cpp; $X -I$S/. -I$S/io/field/h5
$B/io/field/imp.o: $S/io/field/imp.cpp; $X -I$S/. -I$S/io/field
$B/io/field/xmf/imp.o: $S/io/field/xmf/imp.cpp; $X -I$S/. -I$S/io/field/xmf
$B/math/linal/imp.o: $S/math/linal/imp.cpp; $X -I$S/. -I$S/math/linal
$B/math/rnd/imp.o: $S/math/rnd/imp.cpp; $X -I$S/. -I$S/math/rnd
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/. -I$S/math/tform
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/. -I$S/mpi
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/. -I$S/mpi
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/. -I$S/mpi
$B/parser/imp.o: $S/parser/imp.cpp; $X -I$S/. -I$S/parser
$B/sdf/array3d/imp.o: $S/sdf/array3d/imp.cu; $N -I$S/. -I$S/sdf/array3d
$B/sdf/bounce/imp.o: $S/sdf/bounce/imp.cu; $N -I$S/. -I$S/sdf/bounce
$B/sdf/dev.o: $S/sdf/dev.cu; $N -I$S/. -I$S/sdf
$B/sdf/field/imp.o: $S/sdf/field/imp.cpp; $X -I$S/. -I$S/sdf/field
$B/sdf/imp.o: $S/sdf/imp.cpp; $X -I$S/. -I$S/sdf
$B/sdf/label/imp.o: $S/sdf/label/imp.cu; $N -I$S/. -I$S/sdf/label
$B/sdf/tex3d/imp.o: $S/sdf/tex3d/imp.cu; $N -I$S/. -I$S/sdf/tex3d
$B/sdf/tform/imp.o: $S/sdf/tform/imp.cpp; $X -I$S/. -I$S/sdf/tform
$B/u/sdf/main.o: $S/u/sdf/main.cu; $N -I$S/. -I$S/u/sdf
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/. -I$S/utils
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/. -I$S/utils
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/. -I$S/utils
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/. -I$S/utils
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/. -I$S/utils
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/. -I$S/utils
$B/wvel/conf.o: $S/wvel/conf.cpp; $X -I$S/. -I$S/wvel
$B/wvel/imp.o: $S/wvel/imp.cpp; $X -I$S/. -I$S/wvel
