$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/glob/imp.o: $S/glob/imp.cpp; $X -I$S/glob -I$S/.
$B/io/field/h5/imp.o: $S/io/field/h5/imp.cpp; $X -I$S/io/field/h5 -I$S/.
$B/io/field/imp.o: $S/io/field/imp.cpp; $X -I$S/io/field -I$S/.
$B/io/field/xmf/imp.o: $S/io/field/xmf/imp.cpp; $X -I$S/io/field/xmf -I$S/.
$B/math/linal/imp.o: $S/math/linal/imp.cpp; $X -I$S/math/linal -I$S/.
$B/math/rnd/imp.o: $S/math/rnd/imp.cpp; $X -I$S/math/rnd -I$S/.
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/math/tform -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/sdf/array3d/imp.o: $S/sdf/array3d/imp.cu; $N -I$S/sdf/array3d -I$S/.
$B/sdf/bounce/imp.o: $S/sdf/bounce/imp.cu; $N -I$S/sdf/bounce -I$S/.
$B/sdf/dev.o: $S/sdf/dev.cu; $N -I$S/sdf -I$S/.
$B/sdf/field/imp.o: $S/sdf/field/imp.cpp; $X -I$S/sdf/field -I$S/.
$B/sdf/imp.o: $S/sdf/imp.cpp; $X -I$S/sdf -I$S/.
$B/sdf/label/imp.o: $S/sdf/label/imp.cu; $N -I$S/sdf/label -I$S/.
$B/sdf/tex3d/imp.o: $S/sdf/tex3d/imp.cu; $N -I$S/sdf/tex3d -I$S/.
$B/sdf/tform/imp.o: $S/sdf/tform/imp.cpp; $X -I$S/sdf/tform -I$S/.
$B/u/sdf/main.o: $S/u/sdf/main.cu; $N -I$S/u/sdf -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/utils -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
$B/wvel/imp.o: $S/wvel/imp.cpp; $X -I$S/wvel -I$S/.
