$B/coords/conf.o: $S/coords/conf.cpp; $X -I$S/coords -I$S/.
$B/coords/imp.o: $S/coords/imp.cpp; $X -I$S/coords -I$S/.
$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/io/field/h5/imp.o: $S/io/field/h5/imp.cpp; $X -I$S/io/field/h5 -I$S/.
$B/io/field/imp.o: $S/io/field/imp.cpp; $X -I$S/io/field -I$S/.
$B/io/field/xmf/imp.o: $S/io/field/xmf/imp.cpp; $X -I$S/io/field/xmf -I$S/.
$B/math/linal/imp.o: $S/math/linal/imp.cpp; $X -I$S/math/linal -I$S/.
$B/math/rnd/imp.o: $S/math/rnd/imp.cpp; $X -I$S/math/rnd -I$S/.
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/math/tform -I$S/.
$B/math/tri/imp.o: $S/math/tri/imp.cpp; $X -I$S/math/tri -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/conf/imp.o: $S/conf/imp.cpp; $X -I$S/parser -I$S/.
$B/u/sdf/main.o: $S/u/sdf/main.cu; $N -I$S/u/sdf -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/utils -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
$B/wall/sdf/array3d/imp.o: $S/wall/sdf/array3d/imp.cu; $N -I$S/wall/sdf/array3d -I$S/.
$B/wall/sdf/bounce/imp.o: $S/wall/sdf/bounce/imp.cu; $N -I$S/wall/sdf/bounce -I$S/.
$B/wall/sdf/field/imp.o: $S/wall/sdf/field/imp.cpp; $X -I$S/wall/sdf/field -I$S/.
$B/wall/sdf/imp.o: $S/wall/sdf/imp.cu; $N -I$S/wall/sdf -I$S/.
$B/wall/sdf/label/imp.o: $S/wall/sdf/label/imp.cu; $N -I$S/wall/sdf/label -I$S/.
$B/wall/sdf/tex3d/imp.o: $S/wall/sdf/tex3d/imp.cu; $N -I$S/wall/sdf/tex3d -I$S/.
$B/wall/sdf/tform/imp.o: $S/wall/sdf/tform/imp.cpp; $X -I$S/wall/sdf/tform -I$S/.
$B/wall/wvel/conf.o: $S/wall/wvel/conf.cpp; $X -I$S/wall/wvel -I$S/.
$B/wall/wvel/imp.o: $S/wall/wvel/imp.cpp; $X -I$S/wall/wvel -I$S/.
