#!/bin/sh

usg () {
    msg 'usage: u.batch NX NY NZ ./udx [Time] [Args..]'
    msg '       u.batch          ./udx [Time]'
    msg '       Time: HH:MM:SS : default is 30:00'
    msg '       Args: passed to ./udx'
    exit
}

msg () { printf '%s\n' "$@" >&2; }

if test $# -ne 0 && test "$1" = -h; then usg; fi
intp() { echo "$1" | grep -q '^[0-9]*$'; }
mult () { awk -v x=$x -v y=$y -v z=$z 'BEGIN {print x*y*z}'; }

x=1 y=1 z=1
if test $# -ne 0 && intp "$1"; then x=$1; shift; fi
if test $# -ne 0 && intp "$1"; then y=$1; shift; fi
if test $# -ne 0 && intp "$1"; then z=$1; shift; fi
if test $# -eq 0; then usg; fi
n=`mult`

h=`u.host`
u.batch."$h" $n $x $y $z "$@"
