#!/bin/sh

. u.edb.util
prog=u.edb.util

usg () {
    msg "$prog command [args..]"
    msg 'print a command to run remote gdb session in emacs("emacs debug")'
    exit
}

if test $# -ne 0 && test "$1" = -h; then usg; fi
