O_C = \
algo/edg/imp.o\
algo/kahan_sum/imp.o\
algo/key_list/imp.o\
algo/scalars/imp.o\
algo/vectors/imp.o\
bop/bop_common.o\
bop/bop_mpi.o\
bop/bop_serial.o\
bop/header.o\
bop/utils.o\
comm/imp.o\
conf/imp.o\
control/den/conf.o\
control/inflow/conf.o\
control/outflow/conf.o\
control/vel/conf.o\
coords/conf.o\
coords/imp.o\
dbg/conf.o\
distr/flu/status/imp.o\
fluforces/imp.o\
flu/imp.o\
frag/imp.o\
he/err.o\
he/hash.o\
he/he.o\
he/memory.o\
he/read.o\
he/util.o\
inter/color/conf.o\
inter/color/imp.o\
io/bop/imp.o\
io/com/imp.o\
io/diag/mesh/imp.o\
io/diag/part/imp.o\
io/grid/h5/imp.o\
io/grid/imp.o\
io/grid/xmf/imp.o\
io/mesh/imp.o\
io/mesh_read/edg/imp.o\
io/mesh_read/imp.o\
io/point/imp.o\
io/restart/imp.o\
io/rig/imp.o\
io/txt/imp.o\
io/vtk/imp.o\
io/vtk/mesh/imp.o\
io/write/imp.o\
libconfig/grammar.o\
libconfig/libconfig.o\
libconfig/scanctx.o\
libconfig/scanner.o\
libconfig/strbuf.o\
libconfig/strvec.o\
libconfig/util.o\
libconfig/wincompat.o\
math/linal/imp.o\
math/rnd/imp.o\
math/tform/imp.o\
math/tri/imp.o\
mesh/angle/imp.o\
mesh/area/imp.o\
mesh/bbox/imp.o\
mesh/cylindrical/imp.o\
mesh/dist/imp.o\
mesh/edg_len/imp.o\
mesh/eng_julicher/imp.o\
mesh/eng_kantor/imp.o\
mesh/force/kantor0/imp.o\
mesh/force/kantor1/imp.o\
mesh/gen/imp.o\
mesh/gen/matrices/imp.o\
mesh/props/imp.o\
mesh/scatter/imp.o\
mesh/spherical/imp.o\
mesh/triangles/imp.o\
mesh/tri_area/imp.o\
mesh/vert_area/imp.o\
mesh/volume/imp.o\
mpi/glb.o\
mpi/wrapper.o\
pair/conf.o\
pair/imp.o\
rbc/adj/imp.o\
rbc/force/bending/imp.o\
rbc/force/conf.o\
rbc/force/rnd/api/imp.o\
rbc/force/rnd/imp.o\
rbc/imp.o\
rbc/params/conf.o\
rbc/params/imp.o\
rbc/shape/imp.o\
rig/gen/imp.o\
rigid/conf.o\
rig/imp.o\
scheme/force/conf.o\
scheme/restrain/conf.o\
scheme/time_line/imp.o\
scheme/time_step/imp.o\
sim/imp.o\
sim/objects/imp.o\
sim/objinter/imp.o\
sim/opt/imp.o\
sim/walls/imp.o\
struct/farray/imp.o\
struct/parray/imp.o\
struct/pfarrays/imp.o\
utils/cc.o\
utils/error.o\
utils/imp.o\
utils/mc.o\
utils/msg.o\
utils/nvtx/imp.o\
utils/os.o\
utils/string/imp.o\
wall/exch/imp.o\
wall/sdf/field/imp.o\
wall/sdf/tform/imp.o\
wall/wvel/conf.o\
wall/wvel/imp.o\

O_G = \
algo/edg/imp.o\
algo/kahan_sum/imp.o\
algo/key_list/imp.o\
algo/scalars/imp.o\
algo/vectors/imp.o\
bop/bop_common.o\
bop/bop_mpi.o\
bop/bop_serial.o\
bop/header.o\
bop/utils.o\
comm/imp.o\
conf/imp.o\
control/den/conf.o\
control/inflow/conf.o\
control/outflow/conf.o\
control/vel/conf.o\
coords/conf.o\
coords/imp.o\
dbg/conf.o\
distr/flu/status/imp.o\
fluforces/imp.o\
flu/imp.o\
frag/imp.o\
he/err.o\
he/hash.o\
he/he.o\
he/memory.o\
he/read.o\
he/util.o\
inter/color/conf.o\
inter/color/imp.o\
io/bop/imp.o\
io/com/imp.o\
io/diag/mesh/imp.o\
io/diag/part/imp.o\
io/grid/h5/imp.o\
io/grid/imp.o\
io/grid/xmf/imp.o\
io/mesh/imp.o\
io/mesh_read/edg/imp.o\
io/mesh_read/imp.o\
io/point/imp.o\
io/restart/imp.o\
io/rig/imp.o\
io/txt/imp.o\
io/vtk/imp.o\
io/vtk/mesh/imp.o\
io/write/imp.o\
math/linal/imp.o\
math/rnd/imp.o\
math/tform/imp.o\
math/tri/imp.o\
mesh/angle/imp.o\
mesh/area/imp.o\
mesh/bbox/imp.o\
mesh/cylindrical/imp.o\
mesh/dist/imp.o\
mesh/edg_len/imp.o\
mesh/eng_julicher/imp.o\
mesh/eng_kantor/imp.o\
mesh/force/kantor0/imp.o\
mesh/force/kantor1/imp.o\
mesh/gen/imp.o\
mesh/gen/matrices/imp.o\
mesh/props/imp.o\
mesh/scatter/imp.o\
mesh/spherical/imp.o\
mesh/triangles/imp.o\
mesh/tri_area/imp.o\
mesh/vert_area/imp.o\
mesh/volume/imp.o\
mpi/glb.o\
mpi/wrapper.o\
pair/conf.o\
pair/imp.o\
rbc/adj/imp.o\
rbc/force/bending/imp.o\
rbc/force/conf.o\
rbc/force/rnd/api/imp.o\
rbc/force/rnd/imp.o\
rbc/imp.o\
rbc/params/conf.o\
rbc/params/imp.o\
rbc/shape/imp.o\
rig/gen/imp.o\
rigid/conf.o\
rig/imp.o\
scheme/force/conf.o\
scheme/restrain/conf.o\
scheme/time_line/imp.o\
scheme/time_step/imp.o\
sim/imp.o\
sim/objects/imp.o\
sim/objinter/imp.o\
sim/opt/imp.o\
sim/walls/imp.o\
struct/farray/imp.o\
struct/parray/imp.o\
struct/pfarrays/imp.o\
utils/cc.o\
utils/error.o\
utils/imp.o\
utils/mc.o\
utils/msg.o\
utils/nvtx/imp.o\
utils/os.o\
utils/string/imp.o\
wall/exch/imp.o\
wall/sdf/field/imp.o\
wall/sdf/tform/imp.o\
wall/wvel/conf.o\
wall/wvel/imp.o\

