= body forces

Force applied to every particles with active flag `push`.
It is defined by two structures:

* `BForce`, contains all informations needed for the  force
  field. It is hold and maintained on host.
* `BForce_v` (_BForce view_), containing only the information needed at
   a specific time. It is passed to device kernels.


== interface

allocate/deallocate the structure:

[source, c++]
----
include::{src}/scheme/force/imp.h[tag=mem]
----

initialize to a given force function:

[source, c++]
----
include::{src}/scheme/force/imp.h[tag=ini]
----

<1> no force
<2> constant force `f`
<3> double poiseuille
<4> shear
<5> 4 roller mill
<6> radial force

initialize from configuration:

[source, c++]
----
include::{src}/scheme/force/imp.h[tag=cnf]
----

interface:

[source, c++]
----
include::{src}/scheme/force/imp.h[tag=interface]
----
<1> change value of the force
<2> apply body force to particles

== configuration

=== none

no body force (default value)

[source, cfg]
----
bforce = {
    type = "none"
}
----

=== constant

constant force

[source, cfg]
----
bforce = {
    type = "constant"
    f    = [1.0, 0.0, 0.0]
}
----

=== double poiseuille

`fx = y > yc ? a : -a`

[source, cfg]
----
bforce = {
    type = "double_poiseuille"
    a    = 1.0
}
----

=== shear

`fx = a * (y - yc)`

[source, cfg]
----
bforce = {
    type = "shear"
    a    = 1.0
}
----

=== 4 roller mill

----
    f.x =  2*sin(x)*cos(y) * a;
    f.y = -2*cos(x)*sin(y) * a;
----

while `x` and `y` are coordinates relative to the domain center and
normalized to have `x = Pi` and `x = -Pi` at the domain edges.

[source, cfg]
----
bforce = {
    type = "four_roller"
    a    = 1.0
}
----

=== radial

`fr = a * er / r`, where `fr` is radial force, `er` is unit radial
vector at position `r` and `r` is radial position.

[source, cfg]
----
bforce = {
    type = "rad"
    a    = 1.0
}
----
