BIN = $(HOME)/bin
B = $(BIN)

P = u.re.push u.re.list u.re.clear u.re.peek u.re.peek0 u.re.peek1
C = u.re.conf

install:
	@echo install re tools to $B
	@mkdir -p $B
	@cp -- $P $B
	@cp -- $C $B

.PHONY: install
