$B/algo/edg/imp.o: $S/algo/edg/imp.cpp; $X -I$S/. -I$S/algo/edg
$B/conf/imp.o: $S/conf/imp.cpp; $X -I$S/. -I$S/conf
$B/d/api.o: $S/d/api.cu; $N -I$S/. -I$S/d
$B/io/mesh_read/imp.o: $S/io/mesh_read/imp.cpp; $X -I$S/. -I$S/io/mesh_read
$B/math/linal/imp.o: $S/math/linal/imp.cpp; $X -I$S/. -I$S/math/linal
$B/math/rnd/imp.o: $S/math/rnd/imp.cpp; $X -I$S/. -I$S/math/rnd
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/. -I$S/math/tform
$B/math/tri/imp.o: $S/math/tri/imp.cpp; $X -I$S/. -I$S/math/tri
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/. -I$S/mpi
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/. -I$S/mpi
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/. -I$S/mpi
$B/rbc/adj/imp.o: $S/rbc/adj/imp.cpp; $X -I$S/. -I$S/rbc/adj
$B/rbc/shape/imp.o: $S/rbc/shape/imp.cpp; $X -I$S/. -I$S/rbc/shape
$B/u/rbc/shape/main.o: $S/u/rbc/shape/main.cpp; $X -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/. -I$S/utils
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/. -I$S/utils
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/. -I$S/utils
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/. -I$S/utils
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/. -I$S/utils
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/. -I$S/utils
