#!/bin/bash

# Open files in visit
# Usage:
# ov file.ply
# ov f1.ply f2.ply

f=/tmp/ov.$$.py
clear () {
    rm -f $f
}

cat > "$f" <<EOF
OpenDatabase("$1")
v()
EOF

trap "clear; exit" 0 1 2 13 15
vpython -i "$f"
clear
