#!/bin/bash

special () {
    printf '%s\n' $* | awk '!/glb\.cu$/' | awk '!/bund\.cu$/'
}

D=../u/x

# run from src
l=`find . -name '*.cu' -o -name '*.h' -o -name '*.cpp'`
l0=`special $l`

d=$D/make/dep.mk
o=$D/make/obj.mk
m=$D/make/dir.mk
r=$D/make/rule.mk

u.deps $l > $d
u.obj  $l > $o
u.mdir $l > $m
u.rule $l0 > $r

echo upd: $d $o $m $r >&2
