#!/usr/bin/awk -f

BEGIN {
    d = 3 # dimension
}

{
    x = $1; y = $2; z = $3
    x += 1; y += 1; z += 1
    id[x, y, z] = num(i++)
}

function loopx(x,   r) {
    if (x) s = s ",\n"
    s = s "{"
    for (r = 0; r < d; r++) loopy(x, r)
    s = s "}"
}

function loopy(x, y,   r) {
    if (y) s = s ", "
    s = s "{"
    for (r = 0; r < d; r++) loopz(x, y, r)
    s = s "}"    
}

function loopz(x, y, z) {
    if (z) s = s ", "
    s = s sprintf("%d", id[x,y,z])
}

END {
    for (r = 0; r < d; r++) loopx(r)

    s = sprintf("{\n%s};\n", s)
    gsub(/\n/, "\n ", s)

    print s
}

function num(x) { return x + 0 }
