#!/usr/bin/awk -f

# format size ("n")

NF == 3 {
    x = $1; y = $2; z = $3
    print format(x, y, z)
}

function format(x, y, z,   e, a, n) {
    if ((e = ex(x)) != 1) a[++n] = e
    if ((e = ey(y)) != 1) a[++n] = e
    if ((e = ez(z)) != 1) a[++n] = e
    if      (n == 0) return fmt0()
    else if (n == 1) return fmt1(a)
    else if (n == 2) return fmt2(a)
    else if (n == 3) return fmt3(a)
}

function fmt0()  { return         "1" }
function fmt1(a) { return sprintf("(%s)",           a[1]) }
function fmt2(a) { return sprintf("(%s)*(%s)",      a[1], a[2]) }
function fmt3(a) { return sprintf("(%s)*(%s)*(%s)", a[1], a[2], a[3]) }

function ex(d) { return encode(d, "XS") } # encode
function ey(d) { return encode(d, "YS") }
function ez(d) { return encode(d, "ZS") }
function encode(d, s) { return (d == 0 ? s : 1) }

