#!/usr/bin/awk -f

function ini() {
    nc = 0; C[++nc] = "BLUE"; C[++nc] = "RED"
    nk = 0; K[++nk] = "SOLVENT"; K[++nk] = "SOLID"; K[++nk] = "WALL"
    n = 1000
}

function rnd(l, h) { return (h-l)*rand() + l}
function r()      { return rnd(-1 ,  1) }
function v()      { return rnd(-10, 10) }
function gen0()      {
    x = r(); y = r(); z = r()
    vx = v(); vy = v(); vz = v()
    k = kind(); c = color()
}

function genA() {
    gen0();
    if (k == "WALL")
	genA()
    ka = k
}

function genB() {
    gen0();
    if (ka == "WALL" && ka == "WALL")
	genB()
}

function write() {
    print x, y, z, vx, vy, vz, k, c
}
function randint(n) { return int(n * rand()) + 1 }
function color()    { return C[randint(nc)] }
function kind()     { return K[randint(nk)] }

BEGIN {
    ini()
    while (n--) {
	genA(); write()
	genB(); write()
    }
}
