#!/bin/sh

. u.test.util

prog=u.test.pack0

cat0 () {
    "$AWK" '
/^# FILE:.*: / { err(FILENAME ":" NR ": " $0) }
              { print   }
function msg(s) { printf "%s\n", s | "cat >&2" }
function err(s) {
    printf s "\n" | "cat >&2"
    exit(2)
}

' "$1"
}

perm () { # permission: first word
    ls -l "$1" | sed 's/ .*//g' | sed 's/\.$//g'
}

for i in `e find "$@" -type f | sort`
do
   p=`e perm "$i"`
   echo "# FILE:$p: $i"
   e cat0 "$i"
   if test $?  -ne 0
   then err "cannot pack '$i'"
   fi
done
