#!/bin/sh

. u.test.util

prog=u.test.touch
prog0=u.test.touch0

usg () {
    msg "$prog MODE [FILE].."
    msg 'create empty [FILE].. with MODE (a line returned by ls -l)'
    msg "$prog -rw-rw-r-- file.txt"
    exit 0
}

split0 () {
    "$AWK" -v m="$1" '
BEGIN { split(m, a, "")
	++i
	print a[++i] a[++i] a[++i],
	    a[++i] a[++i] a[++i],
	    a[++i] a[++i] a[++i]
}'
}

split () { # set user, group, owner
    local p
    p=`split0 $1`
    set -- $p
    u=$1 g=$2 o=$3
}

if test $# -ne 0 && test "$1" = -h; then usg; fi

if test $# -eq 0; then err 'missing MODE argument'; fi
m="$1"; shift

case $m in
    -[r-][w-][x-][r-][w-][x-][r-][w-][x-]) ;;
    *) err "wrong MODE argument '$m'"        ;;
esac

# set [u]ser, [g]roup, [o]wner
split $m

for f
do $prog0 $u $g $o $f
   if test $? -ne 0; then err "$prog0 faild"; fi
done
