#!/bin/sh

# install libconfig to directory $p

set -eu

p0='$HOME/prefix/libconfig'
p=`eval echo $p0`

v=1.7.1
wget https://hyperrealm.github.io/libconfig/dist/libconfig-$v.tar.gz
tar zxvf libconfig-$v.tar.gz
cd libconfig-$v
./configure --prefix="$p" --disable-cxx
make -j
make install
make check

echo
echo '****** add to ~/.bashrc ******'
echo 'PKG_CONFIG_PATH=$PKG_CONFIG_PATH:'"$p0/lib/pkgconfig"
echo 'export PKG_CONFIG_PATH'
echo '******************************'
