#!/bin/bash

# arg-parser replacement
# tools/argp.awk should be on the PATH
#
# Usage:
# argp .conf.test.h -rbcs -wall_creation=5.0     > .conf.h

# everything after are arguments to awk program not to awk itself
argp.awk -- "$@"
