load("format") $
load("cgrind") $

evl(k, i, x):= if k = 1 then I[i,i+1] else
         (x - i) / (k - 1) * evl(k - 1, i, x) +
         (i + k - x) / (k - 1) * evl(k - 1, i + 1, x);

/* I(A, B, x):=if A <= x and x < B then 1 else 0; */
e: evl(4, 0, x);
e: format(e, %poly(I[0,1], I[1,2], I[2,3], I[3, 4]));

foo(i):=float(horner(coeff(e, i)));

for i thru 4 do grind([i-1, i, foo(I[i-1, i])])$

/* draw2d(explicit(f(x), x, 0, 4)); */
