#!/bin/bash

# uses clarity/udeps
# run from src
l=`find . -name '*.cu' -o -name '*.h'`

err () { printf "udeps: %s\n" "$1"; exit 1; }
if test -z "$l"; then err 'no *.cu and *.h files'; fi
u.deps $l > make/Makefile.dep
echo make/Makefile.dep updated >&2
