#!/bin/bash

u=u/x # default unit

build () {
    u.u0 "$u" | D=_ G=. c.main "$u"/make "$u"/make/_
}


list () {
    u.u0 "$u" | D=_ G=. c.act            "$u"/make/_
}

collapse () {
    u.u0 "$u" | D=_ G=. c.collapse        "$u"/make/_
}

arg () {
    List=0 Collapse=0
    while :
    do
	if   test $# -eq 0;  then break
	elif test "$1" = -l; then List=1; shift
	elif test "$1" = -c; then Collapse=1; shift
	else u="$1"; shift
	fi
    done
}

check () {
    if test ! -d "$u"
    then printf "udeps: $u is not a directory\n" >&2
	 exit 1
    fi
}

run () {
    if   test $List     -eq 1; then list;
    elif test $Collapse -eq 1; then collapse;
    else build
    fi
}

arg "$@"
check
run




