#!/bin/sh

: ${AWK=awk}
me=poc/pick

"$AWK" -v me=$me '
function process(s,   a, n) {
    n = sub(/^\(/, "", s)
    if (n != 1) return ERR
    n = sub(/\)$/, "", s)
    if (n != 1) return ERR
    n = split(s, a)

    if (a[1] == "rawevent" && a[2] == 113) {
	print "(exit)" | "cat"
	close("cat")
    }
    
    return OK
}

function ini() { OK = 0; EOF = 1; ERR = -1 }
function geom() {
    print "(interest (pick primitive))"   | "cat"
    print "(interest (rawevent 113))"     | "cat"
    print "(interest (rawevent 32))"      | "cat"
    print "(interest (rawevent 8))"       | "cat"
    print "(geometry thing < hdodec.off)" | "cat"
    print "(normalization world none)"    | "cat"
    close("cat")
}

BEGIN {
    ini()
    geom()

    msg("ready")
    for (;;) {
	status = getline s
	if (status == ERR) break
	if (process(s) != OK) {
	    msg("failt to parse: " s)
	    break
	}
    }
    msg("end")
}
function msg(s) { printf "%s: %s\n", me, s | "cat >&2" }
' "$@"
