#!/bin/sh

prog=poc/geomview/punto
. u.conf.util

: ${AWK=awk}

offp() {
    "$AWK" '{ if ("" $0 != "OFF") exit 1; else exit 0 }' "$1"
}

if test $# -ne 1
then err 'needs OFF'
fi

off="$1"; shift
if ! test -f "$off"
then err "not a file '$off'"
fi

if ! offp "$off"
then err "not an off file '$off'"
fi

t=/tmp/geomview.$$
trap 'rm $t; exit' 1 2 3 4 15

cat >$t <<!
{ appearance {
      +edge
      material { ks 0.0 }
  }
  < "$off"
}
!

geomview -noinit -nopanels -b 1 1 1  -run ./punto0 "$t"
