#!/bin/sh

prog=poc/geomview/punto
. u.conf.util

: ${AWK=awk}

err0 () {
    echo "(exit)"
    err "$@"
}

offp() {
    "$AWK" '{ if ("" $0 != "OFF") exit 1; else exit 0 }' "$1"
}

if test $# -ne 1
then err0 'needs OFF'
fi

off="$1"; shift
if ! test -f "$off"
then err0 "not a file '$off'"
fi

if ! offp "$off"
then err0 "not an off file '$off'"
fi

"$AWK" -v prog=$prog -v off=$off '
function keys(s,   a, n) {
    n = sub(/^\(/, "", s)
    if (n != 1) return ERR
    n = sub(/\)$/, "", s)
    if (n != 1) return ERR
    n = split(s, a)

    if (a[1] == "rawevent" && a[2] == 113)
	g("exit")
    msg(s)
    return OK
}

function ini() { OK = 0; EOF = 1; ERR = -1 }
function geom() {
    g(sprintf("geometry obj { appearance { +edge } < \"%s\" }", off))
    g("bbox-draw obj no")
}

function g(s) {
    printf "(%s)\n", s | "cat"
    close("cat")
}

function g0(s) {
    msg(s)
    printf "%s\n", s | "cat"
    close("cat")    
}

BEGIN {
    ini()
    geom()

    msg("ready")
    for (;;) {
	status = getline s
	if (status == ERR) break
	if (keys(s) != OK) {
	    msg("failt to parse: " s)
	    break
	}
    }
    msg("end")
}
function msg(s) { printf "%s: %s\n", prog, s | "cat >&2" }
' "$@"
