#!/usr/bin/sh

# Sergey's current run

. $HOME/.udx/u.sh
. ./gx.generic.sh

inc ./gx.HOST.sh

set -e

pre() {
    clean
    nv=498

    c=1 # geometry smoothing kernel size
    sdf=$googlex/$c/big.sdf # set in gx.*.sh
    rbc=cells/sph.$nv.off
    sld=data/cylinder.ply
    copy $sdf $rbc $sld

    Contactforces=contactforces
    Solids=solids
    Rbcs=rbcs
    Walls=walls

    NX=8  NY=8  NZ=1
    XS=64 YS=64 ZS=24
    geom # set NN, LX, LY, LZ, Domain

    df=0.5
    fraction=0.2 radius=2.3 sc=0.2 ang=rnd
    plcmt.ro $LX $LY $LZ $radius $fraction $sc $ang ic_solid.txt rbcs-ic.txt

    argp .conf.gx.base.h $Domain              \
	 $Rbcs RBCnv=$nv                      \
	 $Solids $Contactforces               \
	 tend=50000 part_freq=100              \
	 $Walls wall_creation=100             \
	 pushflow     driving_force=$df       \
	 field_dumps part_dumps field_freq=99999  > .conf.h
}

setup
pre
ini
compile
run
