#include <mpi.h>
#include "m.h"

namespace m { /* MPI (man MPI_Cart_get) */
const int d = 3;
int periods[d] = {true, true, true};
/* set in main */
int  rank, coords[d], dims[d];
const bool reorder = false;
MPI_Comm cart;

/* generated by mpi/transform/decl2wrap  */
#include "m.impl.h"

}
