common.o: $S/common.h $S/conf.common.h $S/conf.h $S/m.h
dpd/dpd.o: $S/dpd-forces.h $S/dpd/cuda-dpd.h $S/dpd/dpd-rng.h $S/hacks.h
dpd/dpd-rng.h: $S/dpd/tiny-float.h
dpd-forces.o: $S/conf.common.h $S/conf.h $S/dpd-forces.h $S/dpd/cuda-dpd.h
field.o: $S/common.h $S/conf.h $S/field.h $S/io.h $S/m.h
glb.o: $S/common.h $S/conf.common.h $S/conf.h $S/glb.h $S/m.h
io.o: $S/common.h $S/conf.common.h $S/conf.h $S/io.h $S/m.h
k/rbc.h: $S/params/rbc.inc0.h
main.o: $S/bund.h $S/common.h $S/conf.h $S/glb.h $S/m.h
mbounce.o: $S/common.h $S/conf.h $S/mbounce.h $S/roots.impl.h
mesh.o: $S/common.h $S/mesh.h
m.o: $S/m.h
mrescue.o: $S/collision.h $S/common.h $S/conf.h $S/mrescue.h
ply.o: $S/common.h $S/ply.h
rminmax.o: $S/common.h $S/conf.h $S/m.h $S/rminmax.h
sminmax.o: $S/common.h $S/conf.h $S/m.h $S/sminmax.h
solid.o: $S/common.h $S/conf.common.h $S/conf.h $S/gsl.impl.h $S/k/solid.h $S/mesh.h $S/solid.h
tcells.o: $S/common.h $S/conf.h $S/m.h $S/tcells.h
