./dev/compile.html: ./dev/compile.adoc 
./dev/conventions.html: ./dev/conventions.adoc 
./dev/cstyle/emacs.html: ./dev/cstyle/emacs.adoc 
./dev/gource.html: ./dev/gource.adoc 
./dev/main.html: ./dev/main.adoc 
./dev/modules/algo/minmax.html: ./dev/modules/algo/minmax.adoc 
./dev/modules/algo/scan.html: ./dev/modules/algo/scan.adoc 
./dev/modules/bforce.html: ./dev/modules/bforce.adoc 
./dev/modules/clist.html: ./dev/modules/clist.adoc 
./dev/modules/color/main.html: ./dev/modules/color/main.adoc ./dev/modules/color/main.inc.adoc ./dev/modules/color/main.inc.adoc ./dev/modules/color/modules.inc.adoc ./dev/modules/color/modules.inc.adoc
./dev/modules/comm.html: ./dev/modules/comm.adoc 
./dev/modules/contact.html: ./dev/modules/contact.adoc 
./dev/modules/d.html: ./dev/modules/d.adoc 
./dev/modules/distr.html: ./dev/modules/distr.adoc 
./dev/modules/fluforces.html: ./dev/modules/fluforces.adoc 
./dev/modules/math/main.html: ./dev/modules/math/main.adoc ./dev/modules/math/linal.inc.adoc ./dev/modules/math/linal.inc.adoc ./dev/modules/math/rnd.inc.adoc ./dev/modules/math/rnd.inc.adoc ./dev/modules/math/tform.inc.adoc ./dev/modules/math/tform.inc.adoc
./dev/modules/parser.html: ./dev/modules/parser.adoc 
./dev/modules/partlist.html: ./dev/modules/partlist.adoc 
./dev/modules/rbc/forces.html: ./dev/modules/rbc/forces.adoc 
./dev/modules/rbc/main.html: ./dev/modules/rbc/main.adoc 
./dev/modules/rbc/rnd.html: ./dev/modules/rbc/rnd.adoc 
./dev/modules/sdf/main.html: ./dev/modules/sdf/main.adoc 
./dev/modules/utils/main.html: ./dev/modules/utils/main.adoc ./dev/modules/utils/cc.inc.adoc ./dev/modules/utils/cc.inc.adoc ./dev/modules/utils/error.inc.adoc ./dev/modules/utils/error.inc.adoc ./dev/modules/utils/kl.inc.adoc ./dev/modules/utils/kl.inc.adoc ./dev/modules/utils/mc.inc.adoc ./dev/modules/utils/mc.inc.adoc
./dev/modules/wvel.html: ./dev/modules/wvel.adoc 
./dev/wrap.html: ./dev/wrap.adoc 
./index.html: ./index.adoc 
./main.html: ./main.adoc 
./units/comm.html: ./units/comm.adoc 
./units/error.html: ./units/error.adoc 
./units/hw/dev.html: ./units/hw/dev.adoc 
./units/hw/hst.html: ./units/hw/hst.adoc 
./units/linal.html: ./units/linal.adoc 
./units/main.html: ./units/main.adoc 
./units/meshbb.html: ./units/meshbb.adoc 
./units/mpi.html: ./units/mpi.adoc 
./units/pair.html: ./units/pair.adoc 
./units/rbc/force.html: ./units/rbc/force.adoc 
./units/rbc/main.html: ./units/rbc/main.adoc 
./units/rbc/rnd.html: ./units/rbc/rnd.adoc 
./units/scan.html: ./units/scan.adoc 
./units/sdf.html: ./units/sdf.adoc 
./units/x.html: ./units/x.adoc 
./user/main.html: ./user/main.adoc 
