#!/bin/sh

r="off.refine -s"

off.icosahedron | $r | $r | $r                > 0.off
off.icosahedron | $r | $r | $r | $r           > 1.off
off.icosahedron | $r | $r | $r | $r | $r      > 2.off
off.icosahedron | $r | $r | $r | $r | $r | $r > 3.off
