#!/bin/bash

# A wrapper to tsdf.awk

t=/tmp/tsdf.$$
if ! mkdir $t
then
    echo >&2 "tsdf: fail to create dir '$t'"
    exit 2
fi

trap 'rm -rf $t; exit 2' 1 2 3 15
TD=$t tsdf.awk -- "$@"

rm -rf $t
