#!/bin/sh

. u.cp.util

prog=u.cp.ic
prog0=u.cp.ic0

usg () {
    msg "$prog [-l] ic.from ic.to"
    msg 'copy initial conditions files to ic.to'
    msg '-l list all ic files'
    msg "$prog cyl1/cyl.dat ic.dat"
    msg "$prog cyl1/cyl     ic.dat"
    exit
}

list () (
    cd "$D/ic"
    find . -type f | sort | \
	sed -e 's,^\./,,g' -e 's,\.ic$,,g'
)

if test $# -ne 0 && test "$1" = -h; then usg; fi
if test ! -d "$D"; then err "not a directory $D"; fi

if test $# -eq 1 && test "$1" = -l
then list
     exit
fi

if test $# -ne 2 ; then err "needs two arguments"; fi

exec $prog0 "$@"
