#!/bin/sh

. u.cp.util

prog=u.cp.rbc
prog0=u.cp.rbc0

usg () {
    msg "$prog template.from template.to"
    msg 'copy cell template to template.to'
    msg "$prog sc/498.off rbc.off"
    msg "$prog 2562.off   rbc.off"
    exit
}

if test $# -ne 0 && test "$1" = -h; then usg; fi
exec $prog0 "$@"
