#!/bin/sh

. u.cp.util

prog=u.cp.sdf
prog0=u.cp.sdf0

usg () {
    msg "$prog [-l] sdf.from sdf.to"
    msg 'copy sdf file to sdf.to'
    msg '-l list all sdf files'
    msg "$prog cyl1/cyl.dat sdf.dat"
    msg "$prog cyl1/cyl     sdf.dat"
    exit
}

list () (
    cd "$D/sdf"
    find . -type f | sort | \
	sed -e 's,^\./,,g' -e 's,\.dat$,,g' -e 's,\.sdf$,,g'
)

if test $# -ne 0 && test "$1" = -h; then usg; fi
if test ! -d "$D"; then err "not a directory $D"; fi

if test $# -eq 1 && test "$1" = -l
then list
     exit
fi

if test $# -ne 2 ; then err "needs two arguments"; fi

exec $prog0 "$@"
