$B/algo/minmax/imp.o: $S/algo/minmax/imp.cu; $N -I$S/algo/minmax -I$S/.
$B/algo/scan/imp.o: $S/algo/scan/imp.cu; $N -I$S/algo/scan -I$S/.
$B/clist/imp.o: $S/clist/imp.cu; $N -I$S/clist -I$S/.
$B/cnt/imp.o: $S/cnt/imp.cu; $N -I$S/cnt -I$S/.
$B/color/flux.o: $S/color/flux.cu; $N -I$S/color -I$S/.
$B/comm/imp.o: $S/comm/imp.cpp; $X -I$S/comm -I$S/.
$B/control/den/imp.o: $S/control/den/imp.cu; $N -I$S/control/den -I$S/.
$B/control/inflow/imp.o: $S/control/inflow/imp.cu; $N -I$S/control/inflow -I$S/.
$B/control/outflow/imp.o: $S/control/outflow/imp.cu; $N -I$S/control/outflow -I$S/.
$B/control/vel/imp.o: $S/control/vel/imp.cu; $N -I$S/control/vel -I$S/.
$B/d/api.o: $S/d/api.cu; $N -I$S/d -I$S/.
$B/dbg/imp.o: $S/dbg/imp.cu; $N -I$S/dbg -I$S/.
$B/distr/flu/imp.o: $S/distr/flu/imp.cu; $N -I$S/distr/flu -I$S/.
$B/distr/map/imp.o: $S/distr/map/imp.cu; $N -I$S/distr/map -I$S/.
$B/distr/rbc/imp.o: $S/distr/rbc/imp.cu; $N -I$S/distr/rbc -I$S/.
$B/distr/rig/imp.o: $S/distr/rig/imp.cu; $N -I$S/distr/rig -I$S/.
$B/exch/flu/imp.o: $S/exch/flu/imp.cu; $N -I$S/exch/flu -I$S/.
$B/exch/mesh/imp.o: $S/exch/mesh/imp.cu; $N -I$S/exch/mesh -I$S/.
$B/exch/obj/imp.o: $S/exch/obj/imp.cu; $N -I$S/exch/obj -I$S/.
$B/fluforces/bulk/imp.o: $S/fluforces/bulk/imp.cu; $N -I$S/fluforces/bulk -I$S/.
$B/fluforces/bulk/transpose/imp.o: $S/fluforces/bulk/transpose/imp.cu; $N -I$S/fluforces/bulk/transpose -I$S/.
$B/fluforces/halo/imp.o: $S/fluforces/halo/imp.cu; $N -I$S/fluforces/halo -I$S/.
$B/fluforces/imp.o: $S/fluforces/imp.cu; $N -I$S/fluforces -I$S/.
$B/flu/imp.o: $S/flu/imp.cpp; $X -I$S/flu -I$S/.
$B/frag/imp.o: $S/frag/imp.cpp; $X -I$S/frag -I$S/.
$B/fsi/imp.o: $S/fsi/imp.cu; $N -I$S/fsi -I$S/.
$B/generate/rig/imp.o: $S/generate/rig/imp.cpp; $X -I$S/generate/rig -I$S/.
$B/glob/imp.o: $S/glob/imp.cpp; $X -I$S/glob -I$S/.
$B/inter/imp.o: $S/inter/imp.cu; $N -I$S/inter -I$S/inter/_france -I$S/.
$B/io/bop/imp.o: $S/io/bop/imp.cpp; $X -I$S/io/bop -I$S/.
$B/io/com/imp.o: $S/io/com/imp.cpp; $X -I$S/io/com -I$S/.
$B/io/diag/imp.o: $S/io/diag/imp.cpp; $X -I$S/io/diag -I$S/.
$B/io/field/h5/imp.o: $S/io/field/h5/imp.cpp; $X -I$S/io/field/h5 -I$S/.
$B/io/field/imp.o: $S/io/field/imp.cpp; $X -I$S/io/field -I$S/.
$B/io/fields_grid/imp.o: $S/io/fields_grid/imp.cpp; $X -I$S/io/fields_grid -I$S/.
$B/io/field/xmf/imp.o: $S/io/field/xmf/imp.cpp; $X -I$S/io/field/xmf -I$S/.
$B/io/mesh/imp.o: $S/io/mesh/imp.cpp; $X -I$S/io/mesh -I$S/.
$B/io/mesh/write/imp.o: $S/io/mesh/write/imp.cpp; $X -I$S/io/mesh/write -I$S/.
$B/io/off/imp.o: $S/io/off/imp.cpp; $X -I$S/io/off -I$S/.
$B/io/ply/imp.o: $S/io/ply/imp.cpp; $X -I$S/io/ply -I$S/.
$B/io/restart/imp.o: $S/io/restart/imp.cpp; $X -I$S/io/restart -I$S/.
$B/io/rig/imp.o: $S/io/rig/imp.cpp; $X -I$S/io/rig -I$S/.
$B/main.o: $S/main.cpp; $X -I$S/.
$B/math/linal/imp.o: $S/math/linal/imp.cpp; $X -I$S/math/linal -I$S/.
$B/math/rnd/imp.o: $S/math/rnd/imp.cpp; $X -I$S/math/rnd -I$S/.
$B/math/tform/imp.o: $S/math/tform/imp.cpp; $X -I$S/math/tform -I$S/.
$B/meshbb/imp.o: $S/meshbb/imp.cu; $N -I$S/meshbb -I$S/.
$B/mesh/bbox.o: $S/mesh/bbox.cu; $N -I$S/mesh -I$S/.
$B/mesh/collision.o: $S/mesh/collision.cu; $N -I$S/mesh -I$S/.
$B/mesh/dist.o: $S/mesh/dist.cpp; $X -I$S/mesh -I$S/.
$B/mesh/props.o: $S/mesh/props.cpp; $X -I$S/mesh -I$S/.
$B/mpi/glb.o: $S/mpi/glb.cpp; $X -I$S/mpi -I$S/.
$B/mpi/type.o: $S/mpi/type.cpp; $X -I$S/mpi -I$S/.
$B/mpi/wrapper.o: $S/mpi/wrapper.cpp; $X -I$S/mpi -I$S/.
$B/parser/imp.o: $S/parser/imp.cpp; $X -I$S/parser -I$S/.
$B/rbc/adj/imp.o: $S/rbc/adj/imp.cpp; $X -I$S/rbc/adj -I$S/.
$B/rbc/com/imp.o: $S/rbc/com/imp.cu; $N -I$S/rbc/com -I$S/.
$B/rbc/edg/imp.o: $S/rbc/edg/imp.cpp; $X -I$S/rbc/edg -I$S/.
$B/rbc/force/area_volume/imp.o: $S/rbc/force/area_volume/imp.cu; $N -I$S/rbc/force/area_volume -I$S/.
$B/rbc/force/imp.o: $S/rbc/force/imp.cu; $N -I$S/rbc/force -I$S/.
$B/rbc/gen/imp.o: $S/rbc/gen/imp.cpp; $X -I$S/rbc/gen -I$S/.
$B/rbc/main/anti/imp.o: $S/rbc/main/anti/imp.cpp; $X -I$S/rbc/main/anti -I$S/.
$B/rbc/main/imp.o: $S/rbc/main/imp.cpp; $X -I$S/rbc/main -I$S/.
$B/rbc/rnd/api/imp.o: $S/rbc/rnd/api/imp.cpp; $X -I$S/rbc/rnd/api -I$S/.
$B/rbc/rnd/imp.o: $S/rbc/rnd/imp.cpp; $X -I$S/rbc/rnd -I$S/.
$B/rbc/stretch/imp.o: $S/rbc/stretch/imp.cu; $N -I$S/rbc/stretch -I$S/.
$B/rigid/imp.o: $S/rigid/imp.cu; $N -I$S/rigid -I$S/.
$B/rig/imp.o: $S/rig/imp.cpp; $X -I$S/rig -I$S/.
$B/scheme/force/imp.o: $S/scheme/force/imp.cu; $N -I$S/scheme/force -I$S/.
$B/scheme/move/imp.o: $S/scheme/move/imp.cu; $N -I$S/scheme/move -I$S/.
$B/scheme/restrain/imp.o: $S/scheme/restrain/imp.cpp; $X -I$S/scheme/restrain -I$S/.
$B/scheme/restrain/sub/imp.o: $S/scheme/restrain/sub/imp.cu; $N -I$S/scheme/restrain/sub -I$S/.
$B/scheme/restrain/sub/stat/imp.o: $S/scheme/restrain/sub/stat/imp.cpp; $X -I$S/scheme/restrain/sub/stat -I$S/.
$B/scheme/restrain/sub/sum/imp.o: $S/scheme/restrain/sub/sum/imp.cpp; $X -I$S/scheme/restrain/sub/sum -I$S/.
$B/sdf/array3d/imp.o: $S/sdf/array3d/imp.cu; $N -I$S/sdf/array3d -I$S/.
$B/sdf/bounce/imp.o: $S/sdf/bounce/imp.cu; $N -I$S/sdf/bounce -I$S/.
$B/sdf/field/imp.o: $S/sdf/field/imp.cpp; $X -I$S/sdf/field -I$S/.
$B/sdf/imp.o: $S/sdf/imp.cu; $N -I$S/sdf -I$S/.
$B/sdf/label/imp.o: $S/sdf/label/imp.cu; $N -I$S/sdf/label -I$S/.
$B/sdf/tex3d/imp.o: $S/sdf/tex3d/imp.cu; $N -I$S/sdf/tex3d -I$S/.
$B/sdf/tform/imp.o: $S/sdf/tform/imp.cpp; $X -I$S/sdf/tform -I$S/.
$B/sim/imp.o: $S/sim/imp.cpp; $X -I$S/sim -I$S/.
$B/utils/cc.o: $S/utils/cc.cpp; $X -I$S/utils -I$S/.
$B/utils/error.o: $S/utils/error.cpp; $X -I$S/utils -I$S/.
$B/utils/imp.o: $S/utils/imp.cpp; $X -I$S/utils -I$S/.
$B/utils/mc.o: $S/utils/mc.cpp; $X -I$S/utils -I$S/.
$B/utils/msg.o: $S/utils/msg.cpp; $X -I$S/utils -I$S/.
$B/utils/os.o: $S/utils/os.cpp; $X -I$S/utils -I$S/.
$B/wall/exch/imp.o: $S/wall/exch/imp.cpp; $X -I$S/wall/exch -I$S/.
$B/wall/force/imp.o: $S/wall/force/imp.cu; $N -I$S/wall/force -I$S/.
$B/wall/imp.o: $S/wall/imp.cu; $N -I$S/wall -I$S/.
$B/wvel/imp.o: $S/wvel/imp.cpp; $X -I$S/wvel -I$S/.
