#!/bin/sh
set -eu

A="$1"; shift
B="$1"; shift

awk -v A=$A -v B=$B '
function read_line(q,   s, n) {
    n = split(q, s)
    x = s[2]; y = s[3]; z = s[4]
    return n
}
BEGIN {
    while (1) {
	ra = getline a < A
	rb = getline b < B
	if (ra <= 0) break
	if (rb <= 0) break
	n = read_line(a); xa = x; ya = y; za = z
	if (n > 0) {
	    read_line(b); xb = x; yb = y; zb = z
	    dx = xb - xa; dy = yb - ya; dz = zb - za
	    print a, dx, dy, dz
	} else {
	    printf "\n"
	}
    }
}
'
