#!/bin/sh
set -u

prog=u.punto.dt

# input, sorted, rest
. u.punto.util

n="$1"; shift
i="$1"; shift

if ! test -r "$i"; then err "not a file '$i'"; fi

s=/tmp/s.dt.$$; >$s; trap 'e rm $s' 1 2 3 4 15
r=/tmp/r.dt.$$; >$r; trap 'e rm $r' 1 2 3 4 15

e u.punto.sort "$i"    '>' $s
if test $? -ne 0; then err 'u.punto.sort failed'; fi

e u.punto.rest  $n  $s '>' $r
if test $? -ne 0; then err 'u.punto.rest failed'; fi

e u.punto.diff  $r $s
if test $? -ne 0; then err 'u.punto.diff failed'; fi

e rm $s $r
