= restart

Dump and read restart files to restart simulation at a given time.
Uses the <<third_bop, bop>> file format.

== naming

The restart files are named as:

----
BASE/CODE/ID.bop
BASE/CODE/ID.values
----

* `BASE`: compile time option, can be different for dump and read. See
  `BASE_STRT_DUMP` and `BASE_STRT_READ`. Set to "strt" by default.
* `CODE`: specified by the user, see `code` parameter in the
  <<io_restart_int>>. By convention, it corresponds to the quantity name
  followed by an additional specifier, such as "flu.pp" for particles
  of the solvent.
* `ID`: a string specific to the time step. Common value is the dump
  index starting from 0. Special values are described in  <<io_restart_int>>

[[io_restart_int]]
== interface

Writing a single file for all ranks:

[source,cpp]
----
include::{src}/io/restart/imp.h[tag=write]
----
<1> write particle data
<2> write integer data
<3> write rigid data

The reader functions are symmetric to the writer:

[source,cpp]
----
include::{src}/io/restart/imp.h[tag=read]
----

The parameters are:

* a communicator of all ranks dumping or reading the file
* `code`: a string containing the directory name
* `id`: the index of dump (starting at 0). Special values can be
   passed:

[source,cpp]
----
include::{src}/io/restart/imp.h[tag=id]
----

The _final_ and _begin_ special ids will replace the `id` part with the string
"final". It is used to dump the last restart file.
The _templ_ special id will replace the `id` part with the string
"templ". It is used for special quantities which do not change during
the whole simulation, such as wall frozen particles or rigid frozen particles.

