#!/usr/bin/env python2

import sys

prog = "u.hdf2bov0"

def msg(s): sys.stderr.write(s)
def err(s):
    msg("%s: %s\n" % (prog, s))
    sys.exit(2)

try: import h5py as h5
except ImportError: err("fail to import python module `h5py`")

def shift(a): return a.pop(0)
def fopen(n):
    try: f = h5.File(n, "r")
    except IOError: err("%s fails to open `%s`" % (prog, n))
    return f

def size(w, name):
    try: z, y, x, u = w.shape
    except ValueError: err("expecting 4 dimensions in file `%s`" % name)
    return z, y, x, u

argv = sys.argv
argc = len(argv)
shift(argv)

b = shift(argv) # bov and hdf
h = shift(argv)

print h, b

f = fopen(h)
print f.keys()

z, y, x, u = size(f['u'], h)
