#!/usr/bin/env python2

import sys
from os.path import splitext

prog = "u.hdf2bov0"

def msg(s): sys.stderr.write('%s: %s\n' % (prog, s))
def err(s): msg(s); sys.exit(2)
try: import h5py as h5
except ImportError: err("fail to import python module `h5py`")

def shift(a): return a.pop(0)
def fopen(n):
    try: f = h5.File(n, "r")
    except IOError: err("%s fails to open `%s`" % (prog, n))
    return f

argv = sys.argv
argc = len(argv)
shift(argv)

b = shift(argv) # [b]ov [h]df [d]ataset [v]alue
h = shift(argv)
d = shift(argv)

f = fopen(h)
if not d in f:
    k = ' '.join(f.keys())
    msg("no dataset '%s' in file '%s'" % (d, h))
    msg("datasets are")
    err(k)

D = f[d] # data

try: z, y, x, u = D.shape
except ValueError:
    msg("expecting four dimensions for dataset '%s' in file '%s' " % (d, h))
    err("found %s" % str(D.shape))

v = splitext(b)[0] + ".values"
print b, v

f.close()
