#!/usr/bin/env python2

from plyfile import PlyData
import sys
import numpy as np
import efit

def read(f):
    f = PlyData.read(f)
    f = f["vertex"]
    xyz = np.array([f[p] for p in ('x', 'y', 'z')]).T
    return xyz

def shift(xyz, center):
    X, Y, Z = 0, 1, 2
    x = xyz[:, X]; y = xyz[:, Y]; z = xyz[:, Z]
    x -= center[X]; y -= center[Y]; z -= center[Z]
    xyz[:, X] = x; xyz[:, Y] = y; xyz[:, Z] = z

def write(xyz):
    np.savetxt('o', xyz)
    
def rot(xyz, evecs): xyz[:] = np.dot(xyz, evecs)[:]

f = sys.argv[1]
xyz = read(f)

[center, radii, evecs, v, chi2] = efit.ellipsoid(xyz)
shift(xyz, center)
rot(xyz, evecs)

write(xyz)

