#!/bin/sh

msg () { echo >&2 "$@"; }
err () { msg "$@"; exit 2; }

# program and file
p="$1"; shift
f="$1"; shift

t=/tmp/dawk.$$; >$t
trap 'rm $t' 1 2 3 4 15

u.dawk0 "$f" "$p" > $t
if test $? -ne 0; then err 'u.dawk0 failed'; fi

"${AWK-awk}" -f "$t" "$f"

rm $t
