#!/bin/sh

"${AWK-awk}" '
function read(   i) {
    getline < f
    n = split($0, a)
}
function repl(   i) {
    for (i = 1; i <= n; i++)
	gsub("[$]" a[i] "[$]", "$" i, p)
    print p
}
BEGIN {
    f = ARGV[1]; p = ARGV[2]
    read()
    repl()
}

function msg(s) { printf "%s\n", s | "cat >&2" }
function err(s) { msg(s); exit 2 }
' "$@"
