#!/bin/sh

prog=u.dawk "${AWK-awk}" '
function ini() {
    prog = ENVIRON["prog"]
    f = ARGV[1]; p = ARGV[2]
}
function read_err(   s) {
    s = sprintf("file %s is empty", f)
    err(s)
}
function read(   i, rc) {
    rc = getline < f
    if (rc <= 0) read_err()
    n = split($0, a)
}
function repl(   i) {
    for (i = 1; i <= n; i++)
	gsub("[$]" a[i] "[$]", "$" i, p)
    print p
}
BEGIN {
    ini()
    read()
    repl()
}

function msg(s) { printf "%s: %s\n", prog, s | "cat >&2" }
function err(s) { msg(s); exit 2 }
' "$@"
