#!/bin/sh

. u.scatter.util

prog=u.scatter
prog0=u.scatter0

usg () {
    msg "$prog PATTERN ACTION [ARGS].. [-- [FILE]..]"
    msg 'construct and run commands for file lists [FILE].. like'
    msg '  action args f0 f1 output'
    exit
}

if test $# -ne 0 && test "$1" = -h
then usg
fi

$prog0
