#!/bin/sh

. u.scatter.util

prog=u.scatter
prog0=u.scatter0

usg () {
    msg "$prog PATTERN [ARGS].. [-- [FILE]..]"
    msg "construct and run command for
    exit
}

if test $# -ne 0 && test "$1" = -h
then usg
fi

$prog0
