#!/bin/sh

. u.scatter.util

prog=u.scatter0

"$AWK" -v prog="$prog" '
function read_arg(   a, i) {
    i = 0
    for (;;) {
	if (ARGC < 1) break
	a = ARGV[1]; shift()
	if (eq(a, "--")) break
	arg[i++] = a
    }
}
function assert_block(nb, n,   c1, c2, c) {
    if (nb == 0) return
    c1 = (nb - 1, n - 1) in files
    c2 = (nb - 1,     n) in files
    c = c1 && !c2
    if (!c) err(sprintf("wrong size=%d for file block=%d", n, nb))
}
function read_files0(nb,   a, i) {
    i = 0
    for (;;) {
	if (ARGC == 1) break
	a = ARGV[1]; shift()
	if (eq(a, "--")) break
	files[nb, i++] = a
    }
    assert_block(nb, i)
}
function read_files(   nb) {
    nb = 0 # number of file blocks
    for (;;) {
	if (ARGC == 1) break
	read_files0(nb++)
    }
}
BEGIN {
    pat = ARGV[1]; shift()
    act = ARGV[1]; shift()
    read_arg()
    read_files()
    for (ib = 0; (ib, 0) in files; ib++) {
	for (i = 0; (ib, i) in files; i++) {
	    print ib, i, files[ib, i]
	}
    }
}
function shift(  i) { for (i = 2; i < ARGC; i++) ARGV[i-1] = ARGV[i]; ARGC-- }
function msg(s) { printf "%s\n", s | "cat >&2" }
function err(s) {
    printf "%s: %s\n", prog, s | "cat >&2"
    exit(2)
}
function eq(a, b) { return a "" == b "" }
' "$@"
