#!/bin/sh

. u.scatter.util

prog=u.scatter
prog0=u.scatter0

usg () {
    msg "$prog PATTERN ACTION [ARGS].. [-- [FILE]..]"
    msg 'construct and run commands for file lists [FILE].. like'
    msg '  action args f0 f1 output'
    msg '  ouput is constructed from PATTERN with % replaced by `basename file`'
    msg 'Examples:'
    msg 'u.scatter out/% echo preved -- f1 f2 -- g1 g2'
    exit
}

if test $# -ne 0 && test "$1" = -h
then usg
fi

if test $# -eq 0; then err 'needs PATTERN'; fi
pat="$1"; shift

if test $# -eq 0; then err 'needs ACTION'; fi
act="$1"; shift

Found=0
for i
do shift
   if test "$i" = --; then Found=1; fi
   set -- "$@" "$i"
done

if test $Found -eq 0; then err "needs at least one --"; fi

$prog0 "$pat" "$act" "$@"

if test $? -ne 0; then err "$prog0 failed"; fi
